Only add primary column when needed.
WordPress/wordpress-develop pull request #1085
Opened 2021-03-09 22:49 UTC by peterwilsoncc

https://core.trac.wordpress.org/ticket/34564

2022-06-20 10:12 UTC, spacedmonkey commented on src/wp-admin/includes/class-wp-list-table.php
> +			}
What is happening here?

2022-06-20 10:20 UTC, spacedmonkey approved these changes

2022-08-04 09:50 UTC, mukeshpanchal27 approved these changes
Looks great!

2022-08-08 23:33 UTC, costdev requested changes

2022-08-08 23:33 UTC, costdev commented on tests/phpunit/tests/admin/wpListTable.php
> +		$this->assertSame( $expected_hook_count, $hook->get_call_count() );
```suggestion
		$this->assertSame( $expected, $column_info->invoke( $list_table ), 'The actual columns did not match the expected columns' );
		$this->assertSame( $expected_hook_count, $hook->get_call_count(), 'The hook was not called the expected number of times' );
```

2022-08-08 23:33 UTC, costdev commented on tests/phpunit/tests/admin/wpListTable.php
> +	 * @param array  $expected   The expected column headers.
```suggestion
	 * @param string $list_class          The name of the WP_List_Table child class.
	 * @param array  $headers             A list of column headers.
	 * @param array  $expected            The expected column headers.
	 * @param int    $expected_hook_count The expected number of times the hook is called.
```

2022-08-08 23:44 UTC, costdev commented on tests/phpunit/tests/admin/wpListTable.php
> +		$list_table = _get_list_table( $list_class );
```suggestion
		$list_table = _get_list_table( $list_class, array( 'screen' => 'test-screen' ) );
```
Passing a `screen` value in the args removes the need to set the `hook_suffix` global.

2022-08-08 23:48 UTC, costdev approved these changes

2022-08-09 00:33 UTC, peterwilsoncc commented
Merged https://core.trac.wordpress.org/changeset/53868 / 11cc06cd22

2022-08-09 00:33 UTC, closed without merging