REST API: Avoid unnecessarily preparing item links
WordPress/wordpress-develop pull request #1179
Opened 2021-04-07 19:07 UTC by dlh01

Trac ticket: https://core.trac.wordpress.org/ticket/52992

2021-10-21 16:08 UTC, anton-vlasenko requested changes
Could you please resolve the merge conflicts?

2022-06-16 17:41 UTC, spacedmonkey commented on src/wp-includes/rest-api/endpoints/class-wp-rest-post-types-controller.php
> +			);
I think we should take the opportunity to break this logic out to `prepare_links` method.

2022-06-16 17:49 UTC, spacedmonkey commented
Missed links. 

https://github.com/WordPress/wordpress-develop/blob/df8c3d0e089f77eb5c6fa971ba4ae9956255893e/src/wp-includes/rest-api/endpoints/class-wp-rest-sidebars-controller.php#L371

https://github.com/WordPress/wordpress-develop/blob/bd08b221273b8b367a18fef8c9efb873819ac89d/src/wp-includes/rest-api/endpoints/class-wp-rest-templates-controller.php#L665

https://github.com/WordPress/wordpress-develop/blob/78cf2760354fe508d4abaf19403514034cbef1c9/src/wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php#L338

https://github.com/WordPress/wordpress-develop/blob/df8c3d0e089f77eb5c6fa971ba4ae9956255893e/src/wp-includes/rest-api/endpoints/class-wp-rest-widgets-controller.php#L729

2022-06-16 17:50 UTC, spacedmonkey commented on src/wp-includes/rest-api/endpoints/class-wp-rest-taxonomies-controller.php
> +			$response->add_links(
See https://github.com/WordPress/wordpress-develop/pull/1179/files#r899365716

2022-06-26 00:57 UTC, dlh01 commented
Will open a fresh PR against `trunk`.

2022-06-26 00:57 UTC, closed without merging