#53490 adds missing test for xmlrpc function in functions.php
WordPress/wordpress-develop pull request #1419
Opened 2021-06-23 18:19 UTC by pbearne

adds missing test for xmlrpc function in functions.php

Trac ticket: https://core.trac.wordpress.org/ticket/53490

2021-11-15 20:31 UTC, audrasjb commented
Hi, thanks for the pull request. I committed some changes to this PR to address some Coding Standards issues.

2021-11-15 22:07 UTC, audrasjb approved these changes

2022-04-01 02:44 UTC, costdev commented on tests/phpunit/tests/functions/xmlrpc.php
> +class Tests_function_xmlrpc extends WP_UnitTestCase {
```suggestion
class Tests_Functions_XMLRPC extends WP_UnitTestCase {
```

2022-04-01 02:45 UTC, costdev requested changes
Just one change to the class name and I think these look good.

2022-05-02 00:16 UTC, SergeyBiryukov commented
Thanks for the PR! I have updated the test method descriptions to be a bit more detailed.

Merged in https://core.trac.wordpress.org/changeset/53326.

2022-05-02 00:16 UTC, closed without merging