Add PHPCS fixes to `tests/phpunit/tests` root files.
WordPress/wordpress-develop pull request #1716
Opened 2021-09-27 09:31 UTC by costdev

Apply PHPCS fixes to `tests/phpunit/tests` root files.

Trac ticket: https://core.trac.wordpress.org/ticket/54177

2021-10-16 15:24 UTC, jrfnl requested changes, later dismissed
@costdev Thanks for this PR. There are a few methods which I believe can be made `private`, but otherwise looks good.

Reviewed:
* Test methods and data provider methods need to be `public`. ✔️ 
* Test fixture methods (`set_up*()`, `tear_down*()`) to comply with the visibility of the same methods in the parent class. ✔️ 
* Verified for all methods which don't start with `test_` that the visibility is correct and left inline comments to document the verification (and some suggestions).

**Note**:
The visibility for `set_up()` and `tear_down()` _should_ be `protected` to be in line with the same in PHPUnit, however, that is currently not possible as these methods in the parent `WP_UnitTestCase_Base` class are `public`.

I'd recommend changing the visibility of these methods in the `WP_UnitTestCase_Base` class in a future PR and then fixing up all method overloads in concrete test classes to match.

This would not be a BC-break as integration tests from extenders will continue to work fine as overloading a method and widening the visibility is allowed in PHP.

2021-10-16 17:41 UTC, costdev commented on tests/phpunit/tests/user.php
> +	public function _illegal_user_logins_data() {
Thanks! I've renamed this data provider to `data_illegal_user_logins()` and updated references to it in the latest iteration.

2021-10-16 17:42 UTC, costdev commented on tests/phpunit/tests/media.php
> +	public function _return_alt_caption() {
Thanks! I've removed the underscore and updated references in latest iteration.

2021-10-16 17:42 UTC, costdev commented on tests/phpunit/tests/kses.php
> +	public function _wp_kses_allowed_html_filter( $html, $context ) {
Thanks! I've removed the underscore and updated references in latest iteration.

2021-10-16 17:42 UTC, costdev commented on tests/phpunit/tests/cron.php
> +	public function _filter_pre_schedule_event_filter( $null, $event ) {
Thanks! I've removed the underscore and updated references in latest iteration.

2021-10-16 17:43 UTC, costdev commented on tests/phpunit/tests/query.php
> +	public function _tag_queried_object( &$query ) {
Thanks! I've removed the underscore and updated references in the latest iteration.

2021-10-16 17:46 UTC, costdev commented on tests/phpunit/tests/filters.php
> +	public function _self_removal( $tag ) {
Thanks! I've reviewed the similar method and test in `tests/actions.php`, but I'm not entirely sure how to go about adapting this. Suggesting that this is postponed until either later in this PR or for a future PR.

2021-10-16 17:54 UTC, costdev commented on tests/phpunit/tests/shortcode.php
> +	public function _filter_strip_shortcodes_tagnames() {
Thanks! I've removed the underscore and updated references in latest iteration.

2021-10-16 17:54 UTC, costdev commented on tests/phpunit/tests/shortcode.php
> +	public function _filter_atts2( $out, $pairs, $atts ) {
Thanks! I've removed the underscore and updated references in latest iteration.

2021-10-16 19:25 UTC, jrfnl commented on tests/phpunit/tests/link.php
> +	public function _get_pagenum_link_cb( $url ) {
Hmm... looks like that commit is missing....

2021-10-16 19:29 UTC, jrfnl commented on tests/phpunit/tests/filters.php
> +	public function _self_removal( $tag ) {
Let's open an issue about it and remove the unused function for now.

2021-10-16 19:31 UTC, jrfnl commented on tests/phpunit/tests/rewrite.php
> +	public function _filter_http_home_url( $url, $path, $orig_scheme, $_blog_id ) {
Hmm... looks like that commit is missing....

2021-10-16 19:33 UTC, jrfnl commented on tests/phpunit/tests/media.php
> +	public function _return_alt_caption() {
Hmm... looks like that commit is missing....

2021-10-16 19:34 UTC, costdev commented on tests/phpunit/tests/link.php
> +	public function _get_pagenum_link_cb( $url ) {
Nope, incoming, just reviewing the changes :)

2021-10-16 19:36 UTC, jrfnl commented on tests/phpunit/tests/shortcode.php
> +	public function _filter_strip_shortcodes_tagnames() {
Hmm... looks like that commit is missing....

2021-10-16 19:36 UTC, jrfnl commented on tests/phpunit/tests/shortcode.php
> +	public function _filter_atts( $out, $pairs, $atts ) {
Hmm... looks like that commit is missing....

2021-10-16 19:36 UTC, jrfnl commented on tests/phpunit/tests/shortcode.php
> +	public function _filter_atts2( $out, $pairs, $atts ) {
Hmm... looks like that commit is missing....

2021-10-16 19:38 UTC, jrfnl commented on tests/phpunit/tests/user.php
> +	public function _illegal_user_logins_data() {
Hmm... looks like that commit is missing....

2021-11-04 14:11 UTC, hellofromtonya commented on tests/phpunit/tests/user.php
> +	public function _illegal_user_logins_data() {
I confirmed that this change was indeed done https://github.com/WordPress/wordpress-develop/blob/dfa581a91186c901e8a9969b75439aa5b67fa514/tests/phpunit/tests/user.php#L775. Marking this as resolved.

2021-11-04 14:43 UTC, hellofromtonya approved these changes
Looks good. All changes @jrfnl requested are done and verified. Ready for `commit`.

2021-11-04 15:24 UTC, hellofromtonya commented
Committed via https://core.trac.wordpress.org/changeset/52010.

2021-11-04 15:24 UTC, closed without merging