Add Filter in wp_http_validate_url to control which ports are allowed for remote requests
WordPress/wordpress-develop pull request #1790
Opened 2021-10-29 16:07 UTC by aaronjorbin

By default we only allow ports 80, 443, and 8080 to be used for (safe) remote requests. This adds a way to change these hardcode ports so we can better control which ports are allowed or not.

Trac ticket: https://core.trac.wordpress.org/ticket/54331

2021-11-02 09:15 UTC, costdev requested changes
Hi @aaronjorbin!

PR looks good to me. This review suggests some minor changes to pass coding standards in CI and some minor changes to the documentation. Nice work!

2021-11-02 09:15 UTC, costdev commented on src/wp-includes/http.php
> +
PHPCS Fix - Removed additional empty line:
```suggestion

```

2021-11-02 09:15 UTC, costdev commented on src/wp-includes/http.php
> +	 * Controls list of ports considered safe in HTTP Api
Slight grammatical changes and API changed to uppercase for consistency:
```suggestion
	 * Controls the list of ports considered safe in the HTTP API.
```

2021-11-02 09:15 UTC, costdev commented on src/wp-includes/http.php
> +	 * @param array  $allowed_porst Array of integers for valid ports
Corrected typo and added period to the end of the comment for consistency:
```suggestion
	 * @param array  $allowed_ports Array of integers for valid ports.
```

2021-11-02 09:15 UTC, costdev commented on src/wp-includes/http.php
> +	if ( in_array( $port, $allowed_ports, true ) ){
PHPCS fix:
```suggestion
	if ( in_array( $port, $allowed_ports, true ) ) {
```

2021-11-03 02:41 UTC, costdev commented on src/wp-includes/http.php
> +	$allowed_ports = apply_filters( 'http_allowed_safe_ports', array( 80, 443, 8080 ), $host, $url );
`$host` will be undefined when `$same_host` is `true`.

Suggest adding this at line 577:
```
} else {
    $host = $parsed_url['host'];
}
```

2021-11-03 02:43 UTC, costdev commented on src/wp-includes/http.php
> +	$allowed_ports = apply_filters( 'http_allowed_safe_ports', array( 80, 443, 8080 ), $host, $url );
`$host` will be undefined when `$same_host` is `true`.

Suggest adding this at line 577:
```
} else {
    $host = $parsed_url['host'];
}
```

2022-01-05 20:08 UTC, hellofromtonya commented
Rolled into PR #1826 which was committed via https://core.trac.wordpress.org/changeset/52084 and https://core.trac.wordpress.org/changeset/52085.

2022-01-05 20:08 UTC, closed without merging