Code Modernization: Avoid checking if a null email address exists in WP_REST_Users_Controller.
WordPress/wordpress-develop pull request #1801
Opened 2021-11-02 17:38 UTC by anomiex

This fixes a "Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated" warning on PHP 8.1.

PHP has started requiring that built-in method arguments that are not explicitly declared as nullable may no longer be passed null. In this case it seems to make more sense to avoid calling WordPress's own `email_exists()` function with null, as that method is declared as taking only strings and a null email is never going to exist anyway.

Trac ticket: https://core.trac.wordpress.org/ticket/53635

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2021-11-02 18:06 UTC, hellofromtonya requested changes
I'm not seeing a test scenario for a `null`, `''`, or invalid email in the existing phpunit tests. Would be good to add these tests as part of this fix.

2021-11-02 20:01 UTC, anomiex commented on src/wp-includes/rest-api/endpoints/class-wp-rest-users-controller.php
> +		$owner_id = empty( $request['email'] ) ? false : email_exists( $request['email'] );
I'm not sure it's possible to get a non-string in here, other than null when the parameter isn't supplied at all. The parameter is declared as a "string" type in the schema, wouldn't anything else have already been rejected with a 'rest_invalid_param' error response? But 🤷 it doesn't matter to me, it's not my code.

The `isset` semantics don't seem to actually be needed either. `$request` is a `WP_REST_Request` and its `offsetGet` implementation doesn't try to raise any warnings for unset options. Personally I usually avoid `isset` or `empty` in such cases in favor of null or truthiness checks, but I saw use of `empty` elsewhere in the method so I went with it to match the style.

2021-11-02 20:08 UTC, anomiex commented
FYI, you are in fact running into the deprecation this is fixing in your existing tests. See for example https://github.com/WordPress/wordpress-develop/runs/4083354600?check_suite_focus=true#step:20:403

And a test that would try to pass an empty string as an email address won't actually reach this code, as that gets rejected as "invalid email address" during parameter validation. I can still add such a test if you insist, but it wouldn't actually test the code being changed here.

2021-11-03 02:51 UTC, jrfnl commented
I looked at that failing test before and my assessment at the time was that this is an issue with the way the test is set up, not with the actual code.

`self::$user` is not being correctly mocked in the `wpSetUpBeforeClass()` method in the `WP_Test_REST_Users_Controller` class which leads to the `null` for the email address.
This is not a situation which should ever occur in "real life" and should therefore not be solved in the `src` code, but by improving the test.

2021-11-03 15:11 UTC, anomiex commented
You may want to check again. The problem isn't whether the user has an email address set, it's whether the incoming REST request specifies a value for the 'email' parameter (i.e. to update the email).

You should be able to prove that to yourself easily enough: Add something like
```php
if ( null === $request['email'] ) return new WP_Error( 'email_is_null', 'Email is null', array( 'status' => '500' ) );
```
just before the `email_exists()` call, then try to make a REST request to update the description of an existing user that does have an email address.

2022-01-03 21:28 UTC, anomiex commented
I see that you've closed https://core.trac.wordpress.org/ticket/53635 without addressing the issue this PR fixes. What's the way forward now?

2022-01-03 21:45 UTC, hellofromtonya commented
>I see that you've closed https://core.trac.wordpress.org/ticket/53635 without addressing the issue this PR fixes. What's the way forward now?

@anomiex Trac ticket https://core.trac.wordpress.org/ticket/54730 is now open for continuing PHP 8.x compatibility fixes during the 6.0 cycle. I updated the description in this PR to point at the new ticket.

2022-02-14 13:56 UTC, anomiex commented
Looks like #2133 will fix this too, by making the called functions no longer object to being passed null. If that gets merged, this can be closed.

2022-02-14 14:48 UTC, hellofromtonya commented
>Looks like https://github.com/WordPress/wordpress-develop/pull/2133 will fix this too, by making the called functions no longer object to being passed null. If that gets merged, this can be closed.

Once #2133 gets merged, then yes, it will resolve this PR's deprecation notice without further changes. Plus #2133 resolves the issue at the lower level, i.e. where the deprecation notice is triggered. I think overall this PR can be closed in favor of #2133.

Note: There's an improvement opportunity, though out of scope for the purpose of this PR:

- Guard `email_exists()` to invoke `get_user_by()` only when a string type is passed to `email_exists()`, i.e. providing a teeny tiny micro-optimization when a non-string is passed. (This tweak deserves a separate PR and tests.)

2022-02-14 14:48 UTC, closed without merging