Cpt wp global styles fixes
WordPress/wordpress-develop pull request #1832
Opened 2021-11-08 18:05 UTC by kebbet

Trac ticket: https://core.trac.wordpress.org/ticket/54336

Adresses https://core.trac.wordpress.org/ticket/54336#comment:13 and https://core.trac.wordpress.org/ticket/54336#comment:14

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2021-11-09 09:57 UTC, oandregal approved these changes
Changes make sense to me. Thanks for the follow up.

2021-11-09 10:02 UTC, oandregal commented
@kebbet would you remove the changes for the calendar block? It's unrelated to global styles and it's causing some tests to fail. That may need a separate PR where we can investigate in isolation, while the global styles changes can already be merged.

2021-11-09 10:16 UTC, kebbet commented
> @kebbet would you remove the changes for the calendar block? It's unrelated to global styles and it's causing some tests to fail. That may need a separate PR where we can investigate in isolation, while the global styles changes can already be merged.

@oandregal Reverted.

2021-11-09 10:38 UTC, kebbet commented
And a separate PR for calendar block: https://github.com/WordPress/wordpress-develop/pull/1845

2021-11-09 22:54 UTC, swissspidy commented
@jorgefilipecosta FYI

2021-11-09 22:56 UTC, swissspidy commented on src/wp-includes/post.php
> +			'description'  => __( 'Custom post type to include global styles in themes.' ),
Maybe just 

```suggestion
			'description'  => __( 'Global styles to include in themes.' ),
```

2021-11-09 22:56 UTC, swissspidy requested changes

2021-11-09 22:56 UTC, swissspidy commented on src/wp-includes/post.php
> +			'description'           => __( 'Custom post type for navigation menus.' ),
Really no reason to mention "custom post type" here.

```suggestion
			'description'           => __( 'Navigation menus.' ),
```

could even just omit it, tbh

2021-11-10 19:58 UTC, desrosj commented
I believe all of this is now merged in to WP trunk as of https://core.trac.wordpress.org/log/?revs=52106%2C52108-52110%2C52128. Please let me know if anything was left out!

Apologies again that I missed this PR initially and left out props. Thank you all for these contributions!

2021-11-10 19:58 UTC, closed without merging