FSE REST permissions endpoint.
WordPress/wordpress-develop pull request #1950
Opened 2021-11-26 02:35 UTC by peterwilsoncc

Unlinked to the ticket while I work a few things out: mainly that I am not about to break everything.

cc @spacedmonkey @TimothyBJacobs @costdev

2021-11-26 22:08 UTC, costdev requested changes
Just a couple of quick notes on return values vs documentation.

2021-11-26 22:08 UTC, costdev commented on src/wp-includes/rest-api/endpoints/class-wp-rest-global-styles-controller.php
> +		return current_user_can( 'read_post', $request['id'] );
This returns `false` when the user does not have read access, but this method should return `true|WP_Error` for consistency within the REST API.

[See here](https://github.com/WordPress/wordpress-develop/blob/7b9e33a1e76c5052b57f7a701e5ec228b3751dea/src/wp-includes/rest-api/endpoints/class-wp-rest-menus-controller.php#L101) for an example `WP_Error`.

2021-11-26 22:08 UTC, costdev commented on src/wp-includes/rest-api/endpoints/class-wp-rest-global-styles-controller.php
> +		return current_user_can( 'edit_post', $request['id'] );
This returns `false` when the user does not have write access, but this method should return `true|WP_Error` for consistency within the REST API.

[See here](https://github.com/WordPress/wordpress-develop/blob/7b9e33a1e76c5052b57f7a701e5ec228b3751dea/src/wp-includes/rest-api/endpoints/class-wp-rest-menus-controller.php#L101) for an example `WP_Error`.

2021-11-29 02:20 UTC, peterwilsoncc commented
Thanks @costdev I'll close this down in favor of Jonny's in #1955 as it seems much closer to completion.

2021-11-29 02:20 UTC, closed without merging