Add wp_after_insert_post call in menu items controller.
WordPress/wordpress-develop pull request #1951
Opened 2021-11-26 10:20 UTC by spacedmonkey

Trac ticket: https://core.trac.wordpress.org/ticket/54498

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2021-11-26 15:16 UTC, adamziel approved these changes

2021-11-28 23:13 UTC, peterwilsoncc requested changes
This will need some changes to `wp_update_nav_menu_item()` to prevent `wp_insert_post()` from firing the hook when it's called. It will probably need a new parameter similar to those added to several functions in [wp-45114](https://core.trac.wordpress.org/ticket/45114).

Without these changes, the endpoint will fire the action twice: once when the post object is created/updated and once when the rest api calls it.

2021-11-29 22:14 UTC, peterwilsoncc approved these changes
This is dandy, thank you.

2021-11-30 02:36 UTC, peterwilsoncc commented
Committed in https://core.trac.wordpress.org/changeset/52276

2021-11-30 02:36 UTC, closed without merging