Ensure that fields are respected in get_theme_item
WordPress/wordpress-develop pull request #2027
Opened 2021-12-07 21:35 UTC by spacedmonkey

Trac ticket: https://core.trac.wordpress.org/ticket/54595

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2021-12-09 03:29 UTC, peterwilsoncc commented
The test `Tests_Rewrite::test_url_to_postid_custom_post_type` failed in PHP 7.2 only, so I have re-run them to see if it was a random error/time based.

Would it be possible to put in some unit tests to ensure the change is working as expected?

2021-12-13 02:27 UTC, costdev requested changes
Just a couple of tidy-up suggestions.

2021-12-13 02:27 UTC, costdev commented on src/wp-includes/rest-api/endpoints/class-wp-rest-global-styles-controller.php
> +			$data['settings'] = $settings;
```suggestion
			$data['settings'] = $theme->get_settings();
```

2021-12-13 02:27 UTC, costdev commented on src/wp-includes/rest-api/endpoints/class-wp-rest-global-styles-controller.php
> +			$data['styles'] = $styles;
```suggestion
			$data['styles'] = $theme->get_raw_data()['styles'];
```

2021-12-13 15:56 UTC, spacedmonkey commented on src/wp-includes/rest-api/endpoints/class-wp-rest-global-styles-controller.php
> -			'collection' => array(
There is no collection, so this should never have been here.

2021-12-13 15:57 UTC, spacedmonkey commented
Added unit tests.

2021-12-13 22:19 UTC, hellofromtonya commented
@spacedmonkey These same changes will be needed in Gutenberg to avoid these changes from being overwritten during a backport update.

2021-12-13 22:23 UTC, hellofromtonya approved these changes
Tested locally and works as expected. Approving for commit 👍

2021-12-13 23:34 UTC, costdev approved these changes

2021-12-14 16:34 UTC, spacedmonkey commented
Merged!

2021-12-14 16:34 UTC, closed without merging