Ticket 49701 - Test coverage for Quick Edit UI for taxonomies with show_ui=false and show_on_quick_edit=true
WordPress/wordpress-develop pull request #205
Opened 2020-03-27 21:41 UTC by figureone

Added tests for hierarchical and nonhierarchical taxonomies with `show_ui = false` and `show_on_quick_edit = true`.

Trac ticket: https://core.trac.wordpress.org/ticket/49701

2022-05-02 00:49 UTC, peterwilsoncc commented
I've re-targeted this to `trunk` to account for the new default branch name and merged in an update to get the tests running.

2022-05-02 07:16 UTC, costdev requested changes
Just needs `@covers` annotations and then I think this one is good to go. 👍

2022-05-02 07:16 UTC, costdev commented on tests/phpunit/tests/taxonomy.php
> +	 * @ticket 49701
```suggestion
	 * @ticket 49701
	 *
	 * @covers ::get_inline_data
```

2022-05-02 07:16 UTC, costdev commented on tests/phpunit/tests/taxonomy.php
> +	 * @ticket 49701
```suggestion
	 * @ticket 49701
	 *
	 * @covers ::get_inline_data
```

2022-05-03 15:53 UTC, audrasjb commented
I committed changes suggested by @costdev to the PR :)
Now leaving this to @SergeyBiryukov for final commit :)

2022-05-09 00:36 UTC, peterwilsoncc commented
These tests were merged in https://core.trac.wordpress.org/changeset/53368, thank you!

2022-05-09 00:36 UTC, closed without merging