Fix Windows paths resulting from `get_attached_file`.
WordPress/wordpress-develop pull request #2442
Opened 2022-03-21 23:53 UTC by dream-encode

Trac ticket: https://core.trac.wordpress.org/ticket/36308.

2022-04-19 05:53 UTC, costdev commented on tests/phpunit/tests/post.php
> +	 *
```suggestion
	 * @covers ::wp_get_attached_file
```

2022-05-26 18:54 UTC, SergeyBiryukov approved these changes

2022-05-26 20:17 UTC, costdev requested changes
Just one suggestion to use a data provider for the new test method.

2022-05-26 20:17 UTC, costdev commented on tests/phpunit/tests/post/getAttachedFile.php
> +	public function test_get_attached_file_with_windows_paths() {
Using a data provider for the `file`, `expected` values, and possibly the `message` value, will ensure that both assertions run even if one happens to fail, and makes it easier to add more tests for this in future if needed.

2022-08-11 22:59 UTC, johnbillion requested changes
This looks good and there's a good amount of test coverage, but I'd also like to see the tests in `Tests_Post_GetAttachedFile` use a data provider 👍

2022-08-11 23:29 UTC, costdev commented
> This looks good and there's a good amount of test coverage, but I'd also like to see the tests in `Tests_Post_GetAttachedFile` use a data provider 👍 

Hi @johnbillion, see [PR 3049](https://github.com/WordPress/wordpress-develop/pull/3049) which is a refresh of this PR that uses a data provider in `Test_Post_GetAttachedFile`

2022-08-12 20:45 UTC, johnbillion commented
Closing in favour of #3049 👍

2022-08-12 20:45 UTC, closed without merging