Add new actions before and after loading the located template
WordPress/wordpress-develop pull request #2462
Opened 2022-03-25 20:21 UTC by Tabrisrp

This patch adds new actions before and after loading the located template in `locate_template()`.

The template filename is passed as an additional parameter to the action, as that can be useful for callbacks on these hooks.

The hooks name and the `@since` value are suggestions, I couldn't find if there is a standard for hooks names in core, as there is some prefixed with `wp_`, and others that are not.

Trac ticket: https://core.trac.wordpress.org/ticket/54541

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2022-04-08 04:03 UTC, peterwilsoncc reviewed
I've added a couple of minor notes inline, nothing to big.

I think @johnbillion wanted to review this too so maybe wait until you hear from John before taking any action. John's been around longer than me so may have additional advice.

2022-04-08 04:03 UTC, peterwilsoncc commented on src/wp-includes/template.php
> +		 * Fires before the located template is loaded
```suggestion
		 * Fires before the located template is loaded.
```

WP documentation standards are to include a period after the description.

:1234: Applies to the description for the after hook too.

2022-04-08 04:03 UTC, peterwilsoncc commented on src/wp-includes/template.php
> +		do_action( 'before_load_template', $located );
```suggestion
		do_action( 'wp_before_load_template', $located );
```

The prefix will help avoid any naming collisions with plugins and themes.

🔢 Applies to the after hook's name too.

2022-06-02 14:41 UTC, martinkrcho commented
@Tabrisrp , would you be able to apply the changes suggested by @peterwilsoncc? Then we could get @johnbillion to review and I would be more than happy to contribute with some unit tests.

2022-06-03 20:29 UTC, Tabrisrp commented on src/wp-includes/template.php
> +		do_action( 'after_load_template', $located );
```suggestion
		do_action( 'wp_after_load_template', $located );
```

2022-06-03 20:30 UTC, Tabrisrp commented on src/wp-includes/template.php
> +		 * Fires after the located template is loaded
```suggestion
		 * Fires after the located template is loaded.
```

2022-06-03 20:30 UTC, Tabrisrp commented
@martinkrcho Done!

2022-06-03 20:32 UTC, Tabrisrp commented on src/wp-includes/template.php
> +		 * @since 6.0.0
```suggestion
		 * @since 6.1.0
```

2022-06-03 20:32 UTC, Tabrisrp commented on src/wp-includes/template.php
> +		 * @since 6.0.0
```suggestion
		 * @since 6.1.0
```

2022-06-06 02:06 UTC, peterwilsoncc reviewed
Thank you. This code looks good to me.

I think John has limited availability at the moment, so let's give him a week or two to add any thougths to this ticket.

2022-06-21 08:54 UTC, johnbillion requested changes
This looks good but it would be good to pass some additional contextual parameters to the actions. I think the `$template_names`, `$require_once`, and `$args` parameters are all potentially useful to these hooks, so let's pass them in please.

2022-06-23 18:52 UTC, johnbillion approved these changes

2022-06-23 19:01 UTC, johnbillion commented
Committed in https://core.trac.wordpress.org/changeset/53560

2022-06-23 19:01 UTC, closed without merging