55461 Improve cache key generation in WP_Network_Query
WordPress/wordpress-develop pull request #2486
Opened 2022-03-31 12:45 UTC by manuelRod

Improve cache key generation in WP_Network_Query unsetting update_network_cache

Trac ticket: https://core.trac.wordpress.org/ticket/55461

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2022-04-05 17:54 UTC, spacedmonkey approved these changes

2022-04-05 23:15 UTC, johnbillion approved these changes

2022-04-06 03:26 UTC, JJJ requested changes

2022-04-06 03:26 UTC, JJJ commented on src/wp-includes/class-wp-network-query.php
> +		unset( $_args['fields'], $_args['update_network_cache'] );
See: https://github.com/WordPress/wordpress-develop/pull/2485#discussion_r843425289

2022-04-07 02:39 UTC, felixarntz approved these changes
Great!

2022-04-07 18:04 UTC, spacedmonkey commented
Committed 🎉

2022-04-07 18:04 UTC, closed without merging