added tests for wp_nonce_field and wp_referer_field
WordPress/wordpress-develop pull request #2596
Opened 2022-04-14 22:10 UTC by pbearne

Trac ticket: https://core.trac.wordpress.org/ticket/55578

2022-04-30 05:33 UTC, costdev requested changes
Thanks for the tests Paul! I have suggested some changes in this review.

Will you have time to review this before RC1 on Tuesday 3rd May?

2022-04-30 05:33 UTC, costdev commented on tests/phpunit/tests/functions/wpNonceField.php
> +				'#^<input type="hidden" id="_wpnonce" name="_wpnonce" value=".{10}" /><input type="hidden" name="_wp_http_referer" value="" />$#',
```suggestion
				'action'           => - 1,
				'name'             => '_wpnonce',
				'referer'          => true,
				'expected_reg_exp' => '#^<input type="hidden" id="_wpnonce" name="_wpnonce" value=".{10}" /><input type="hidden" name="_wp_http_referer" value="" />$#',
```
Adding keys for each parameter in the datasets makes it easier for others to add datasets in the future.

2022-04-30 05:33 UTC, costdev commented on tests/phpunit/tests/functions/wpNonceField.php
> +				- 1,
Can we change `- 1` to `-1`, i.e. without the space?

2022-04-30 05:33 UTC, costdev commented on tests/phpunit/tests/functions/wpRefererField.php
> +		$this->expectOutputRegex( '#^<input type="hidden" name="_wp_http_referer" value="/test/" />$#' );
As this doesn't contain any regular expression syntax except the start and end of a line, `expectOutputString()` can be used instead.

```php
wp_referer_field();

$this->expectOutputString( '<input type="hidden" name="_wp_http_referer" value="/test/" />' );
```

2022-04-30 05:33 UTC, costdev commented on tests/phpunit/tests/functions/wpRefererField.php
> +		$this->assertMatchesRegularExpression( '#^<input type="hidden" name="_wp_http_referer" value="/test/" />$#', wp_referer_field( false ) );
As this doesn't contain any regular expression syntax except the start and end of a line, `assertSame()` can be used instead.

```php
$this->assertSame( '<input type="hidden" name="_wp_http_referer" value="/test/" />', wp_referer_field( false ) );
```

2022-04-30 05:33 UTC, costdev commented on tests/phpunit/tests/functions/wpNonceField.php
> +	 * @dataProvider data_wp_nonce_field
The `action`, `name`, `referer` and `expected_regexp` parameters should be documented like so:

```php
* @param int|string $action           Action name.
* @param string     $name             Nonce name.
* @param bool       $referer          Whether to set the referer field fior validation.
* @param string     $expected_reg_exp The expected regular expression.
```

2022-04-30 05:33 UTC, costdev commented on tests/phpunit/tests/functions/wpNonceField.php
> +		);
Can we add a dataset that makes sure `$name` always goes through `esc_attr()`?

For example, a `$name` of `a&b` should become `a&amp;b`

2022-04-30 05:33 UTC, costdev commented on tests/phpunit/tests/functions/wpNonceField.php
> +	 * @ticket 55578
```suggestion
	 * Data provider.
	 *
	 * @return array
```
The `@ticket` annotation isn't needed for data providers.

2022-05-02 23:31 UTC, pbearne commented on tests/phpunit/tests/functions/wpNonceField.php
> +		);
added

2022-10-07 22:19 UTC, audrasjb commented
Committed in https://core.trac.wordpress.org/changeset/54420

2022-10-07 22:19 UTC, closed without merging