Fix validation of array of fields + adjust tests
WordPress/wordpress-develop pull request #2656
Opened 2022-04-30 17:10 UTC by felipeelia

This PR addresses the adjustments outlined by [@peterwilsoncc](https://profiles.wordpress.org/peterwilsoncc)

Trac ticket: https://core.trac.wordpress.org/ticket/53177

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2022-05-01 01:20 UTC, peterwilsoncc requested changes
When reviewing the tests, I noticed a typo in the query `include[space]` rather than `include`. 

This results in all users been returned each time, instead of just the one admin you are aiming for. That's why you needed to check for user `1` rather than the user ID `self::$admin_ids[0]`

To force the right check, I'd recommend setting the included user to `1`

In the data provider
* set the email to `WP_TESTS_EMAIL` 
* set the URL to `wp_guess_url()`

Other details for the admin user are hard coded within the test suite.

2022-05-01 13:09 UTC, felipeelia commented
Good catch @peterwilsoncc, didn't notice the `include[space]` there. I've addressed all those things in my last commit. Do you mind giving it another look? Thanks!

2022-05-01 23:39 UTC, peterwilsoncc approved these changes

2022-05-02 00:12 UTC, peterwilsoncc commented
Merged in https://core.trac.wordpress.org/changeset/53327, thank you!

2022-05-02 00:12 UTC, closed without merging