PHP 8.2 | WP_Test_Stream: explicitly declare all properties
WordPress/wordpress-develop pull request #2868
Opened 2022-06-23 14:15 UTC by jrfnl

Dynamic (non-explicitly declared) properties are deprecated as of PHP 8.2 and are expected to become a fatal error in PHP 9.0.

The `WP_Test_Stream` class is a stream wrapper for use in the tests and must comply with the PHP requirements for such stream wrappers.

In this case, the class did not declare the required `public` `$context` property, which led to deprecation notices about the property being dynamically created from the `Tests_Image_Editor_Imagick::test_streams()` and `Tests_Image_Meta::test_stream` tests.

Refs:
* https://www.php.net/manual/en/class.streamwrapper.php#streamwrapper.props

Trac ticket: https://core.trac.wordpress.org/ticket/56033

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2022-08-24 16:42 UTC, anton-vlasenko requested changes
@jrfnl ~~I tried to find places in the project where this property (`WP_Test_Stream::$context`) is used but could not find them.
Maybe I missed something?
If there are no such places I would propose to close this PR.~~

2022-08-25 19:51 UTC, anton-vlasenko commented
## Test Report
This report validates that the indicated patch addresses the issue.

Patch tested: https://github.com/WordPress/wordpress-develop/pull/2868

### Environment
* OS: macOS 12.5.1
* Web Server: Apache
* PHP: 8.2.0-dev
* WordPress: 6.1-alpha-53344-src
* Browser: Safari 15.6
* Theme: Twenty Twenty-Two
* Active Plugins:
  * Gutenberg 13.9.0-rc3

### Steps to reproduce:
1. Make sure you are on PHP 8.2. 
2. Make sure `Imagick` extension is enabled.
3. Run the `Tests_Image_Meta::test_stream` test method.
```bash
php vendor/bin/phpunit -c phpunit.xml.dist --filter test_stream
```
4. ❌ The test method will fail with these error messages:
```
There were 4 errors:

1) Tests_Image_Editor_Imagick::test_streams
Creation of dynamic property WP_Test_Stream::$context is deprecated
src/wp-includes/class-wp-image-editor-imagick.php:131
tests/phpunit/tests/image/editorImagick.php:597

2) Tests_Image_Meta::test_stream with data set "Orientation only metadata" ('testimagemeta://wp_read_image...e1.jpg', array('0', '', '', '', '0', '', '0', '0', '0', '', '3', array()))
Creation of dynamic property WP_Test_Stream::$context is deprecated
src/wp-admin/includes/image.php:734
tests/phpunit/tests/image/meta.php:181

3) Tests_Image_Meta::test_stream with data set "Exif from a Nikon D70 with IPTC data added later" ('testimagemeta://wp_read_image...e2.jpg', array('6.3', 'IPTC Creator', 'NIKON D70', 'IPTC Caption', '1090516475', 'IPTC Copyright', '18', '200', '0.04', 'IPTC Headline', '0', array()))
Creation of dynamic property WP_Test_Stream::$context is deprecated
src/wp-admin/includes/image.php:734
tests/phpunit/tests/image/meta.php:181

4) Tests_Image_Meta::test_stream with data set "Exif from a DMC-LX2 camera with keywords" ('testimagemeta://wp_read_image...e3.jpg', array('8', 'Photoshop Author', 'DMC-LX2', 'Photoshop Description', '1306315327', 'Photoshop Copyrright Notice', '6.3', '100', '0.0025', 'Photoshop Document Ttitle', '1', array('beach', 'baywatch', 'LA', 'sunset')))
Creation of dynamic property WP_Test_Stream::$context is deprecated
src/wp-admin/includes/image.php:734
tests/phpunit/tests/image/meta.php:181
```

### After applying the patch:
- ✅ The test method passes.

✅ Everything works as expected.

2022-08-25 19:51 UTC, anton-vlasenko approved these changes
LGTM!

2022-08-28 10:10 UTC, SergeyBiryukov commented
Thanks for the PR! Merged in [r53949](https://core.trac.wordpress.org/changeset/53949).

2022-08-28 10:10 UTC, closed without merging