#56215 - Introduce the `is_term_publicly_viewable()` function
WordPress/wordpress-develop pull request #2974
Opened 2022-07-13 22:22 UTC by johnbillion

Trac ticket: https://core.trac.wordpress.org/ticket/56215

2022-07-14 02:53 UTC, peterwilsoncc reviewed
I think this is a good addition as a sibling to `is_post_publicly_viewable()`.

LGTM but a reordering request in the tests.

2022-07-14 02:53 UTC, peterwilsoncc commented on tests/phpunit/tests/term/isTermPubliclyViewable.php
> +
Are you able to move this above `test_is_term_publicly_viewable()`? I think convention is to keep the test and data methods consecutive whenever possible.

2022-07-17 01:25 UTC, costdev requested changes

2022-07-17 01:25 UTC, costdev commented on tests/phpunit/tests/term/isTermPubliclyViewable.php
> + * @group term
```suggestion
 * @group term
 *
 * @covers ::is_term_publicly_viewable
```

2022-07-17 01:25 UTC, costdev commented on tests/phpunit/tests/term/isTermPubliclyViewable.php
> +	public function test_is_term_publicly_viewable( $taxonomy, $expected, $parent_key = '' ) {
`$parent_key` isn't documented or used in the test method.

2022-08-13 22:42 UTC, johnbillion commented
https://core.trac.wordpress.org/changeset/53893

2022-08-13 22:42 UTC, closed without merging