Handle PHP Notice when get_post_type_object() returns null in is_post_type_archive()
WordPress/wordpress-develop pull request #3027
Opened 2022-07-26 14:51 UTC by srtfisher

Trac ticket: https://core.trac.wordpress.org/ticket/56287

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2022-08-14 04:32 UTC, costdev requested changes
Thanks for the PR and unit tests! I've left some small change requests in this review.

2022-08-14 04:32 UTC, costdev commented on .vscode/settings.json
> +{
This file should be removed from the PR.

2022-08-14 04:32 UTC, costdev commented on tests/phpunit/tests/query.php
> +	 * @ticket 56287
```suggestion
	 * Tests that is_post_type_archive() returns false for an undefined post type.
	 *
	 * @ticket 56287
	 *
	 * @covers ::is_post_type_archive
```

2022-08-14 04:32 UTC, costdev commented on tests/phpunit/tests/query.php
> +	public function test_is_post_type_archive_handles_null_post_type() {
```suggestion
	public function test_is_post_type_archive_should_return_false_for_an_undefined_post_type() {
```
Describing _how_ `is_post_type_archive()` should handle this case in the test name makes it easier to see what's being tested. Replacing `null_post_type` with `an_undefined_post_type` is clearer and also matches the test docblock.

2022-08-15 19:06 UTC, srtfisher commented
@costdev Thanks for the review! Changes made.

2022-08-15 19:28 UTC, costdev approved these changes
PR looks good to me provided manual testing works as expected. :+1:

2022-10-10 22:54 UTC, audrasjb approved these changes
Looks good.

2022-10-10 23:01 UTC, audrasjb commented
Committed in https://core.trac.wordpress.org/changeset/54464

2022-10-10 23:01 UTC, closed without merging