WP_Query ID caching follow up
WordPress/wordpress-develop pull request #3137
Opened 2022-08-25 23:55 UTC by peterwilsoncc

https://core.trac.wordpress.org/ticket/22176

cc @spacedmonkey, @tillkruss -- still a work in progress in case something else comes in but making sure you have eyes on it.

2022-08-26 00:12 UTC, peterwilsoncc commented on src/wp-includes/class-wp-query.php
> +			if ( ! empty( $this->tax_query->queries ) ) {
I considered testing for any SQL clauses as an alternative here:

```php
if ( isset( $this->tax_query ) ) {
	$tax_query_sql = $this->tax_query->get_sql( $wpdb->posts, 'ID' );
	if (
		! empty( $tax_query_sql['join'] ) ||
		! empty( $tax_query_sql['where'] )
	) {
		$last_changed .= wp_cache_get_last_changed( 'terms' );
	}
}
```

2022-08-27 05:00 UTC, costdev requested changes
Thanks for putting the PR together Peter!

Just a few suggestions in this review.

2022-08-27 05:00 UTC, costdev commented on tests/phpunit/tests/query/cacheResults.php
> +	 * @ticket 22176
Is there an appropriate `@covers` tag for these tests? If not, `@coversNothing` should be used.

2022-08-27 05:00 UTC, costdev commented on tests/phpunit/tests/query/cacheResults.php
> +	public function test_query_cache_exclude_term() {
The test names don't describe the expected result. This means reviewing the contents of the test methods to try to ascertain what's being tested and what's expected, and can lead to misunderstandings.

I'd suggest using:
- `test_query_cache_should_exclude_post_with_excluded_term()`.
- `test_query_cache_should_exclude_post_when_excluded_term_is_added_after_caching()`.
- `test_query_cache_should_not_exclude_post_when_excluded_term_is_removed_after_caching()`.

P.S. If any of these test method names are incorrect, that may prove my initial point 😝

2022-08-27 05:00 UTC, costdev commented on tests/phpunit/tests/query/cacheResults.php
> +		$post_ids_q1 = get_posts( $args );
This and `$post_ids_q2` are just named `$post_ids` in the other two test methods. I think it would be beneficial to keep the naming scheme consistent. By using `$post_ids_q1/$post_ids_q2`, a later reference to `$post_ids` isn't confused with the first reference.

2022-09-06 01:20 UTC, peterwilsoncc commented
@costdev 

* In 06f2e1bd74c55da6a6afa140bfec39fa35cd33d2 I've added `@covers WP_Query::get_posts` at the class level
* In fc62eae67c5f98fdcf490cc6c3a9b4413ed477a4 I've renamed the methods
* In d0a7e8bea8eb5f21aa6340037f668ca19a6b39c1 I've modified the variable names to indicate which query the posts belong to

2022-09-06 10:26 UTC, costdev approved these changes
LGTM :+1:

2022-09-09 02:05 UTC, peterwilsoncc commented
Merged in https://core.trac.wordpress.org/changeset/54111 / 48f17267fb

2022-09-09 02:05 UTC, closed without merging