Bundled Themes: Bump themes versions for WP 6.1.
WordPress/wordpress-develop pull request #3148
Opened 2022-08-28 15:33 UTC by robinwpdeveloper

Trac ticket: [56450](https://core.trac.wordpress.org/ticket/56450)

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2022-09-30 16:04 UTC, desrosj requested changes
Thanks for this, @robinwpdeveloper!

When themes have date-based versions for scripts and styles, the last modified date for that specific file should be used. This allows cache busting to occur each time the files are updated, but leaves them the same when no changes occur.

The release date for these will actually be November 1, 2022. So that needs to be updated everywhere that is referenced (except where noted otherwise).

Also, in Twenty Ten and Twenty Eleven, the stylesheet version is noted inline in `header.php` and needs to be updated.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentynineteen/package-lock.json
> +  "lockfileVersion": 2,
It looks like you've updated the lock file using npm 7 or newer. Could you please redo this using npm 6? 

Until [Core-56658](https://core.trac.wordpress.org/ticket/56658) is addressed, NodeJS 14.x/npm 6.x should be used for all related tasks and formats.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyeleven/functions.php
> +	wp_enqueue_style( 'twentyeleven-block-style', get_template_directory_uri() . '/blocks.css', array(), '20221025' );
This one should be `20220927` (last [changed here](https://core.trac.wordpress.org/changeset/54340/)).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyeleven/readme.txt
> +* Released: October 25, 2022
Release date should be `November 1, 2022`. This is true for every other theme in this PR, but I'll only comment on this one.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyfifteen/functions.php
> +	wp_enqueue_style( 'genericons', get_template_directory_uri() . '/genericons/genericons.css', array(), '20221025' );
This one should actually be `20201026`. The last change is [here](https://core.trac.wordpress.org/changeset/49309/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyfifteen/functions.php
> +	wp_enqueue_style( 'twentyfifteen-ie7', get_template_directory_uri() . '/css/ie7.css', array( 'twentyfifteen-style' ), '20221025' );
This [stylesheet has had no changes since the date currently noted](https://core.trac.wordpress.org/log/trunk/src/wp-content/themes/twentyfifteen/css/ie7.css), so should be left the same.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyfifteen/functions.php
> +	wp_enqueue_script( 'twentyfifteen-skip-link-focus-fix', get_template_directory_uri() . '/js/skip-link-focus-fix.js', array(), '20221025', true );
This [script file has had no changes since the date currently noted](https://core.trac.wordpress.org/log/trunk/src/wp-content/themes/twentyfifteen/js/skip-link-focus-fix.js), so should be left the same.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyfifteen/functions.php
> +		wp_enqueue_script( 'twentyfifteen-keyboard-image-navigation', get_template_directory_uri() . '/js/keyboard-image-navigation.js', array( 'jquery' ), '20221025' );
This [script file has had no changes since the date currently noted](https://core.trac.wordpress.org/log/trunk/src/wp-content/themes/twentyfifteen/js/keyboard-image-navigation.js), so should be left the same.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyfourteen/functions.php
> +	wp_enqueue_style( 'twentyfourteen-style', get_stylesheet_uri(), array(), '20221025' );
This file has not been updated recently, but this should always be bumped to ensure the headers in the file are retrieved (which reflects the new, correct version number and tested up to versions). This was missed in the last few releases. This one is good to stay.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyfourteen/functions.php
> +	wp_enqueue_style( 'twentyfourteen-block-style', get_template_directory_uri() . '/css/blocks.css', array( 'twentyfourteen-style' ), '20221025' );
This should be `20210622`, last changed [here](https://core.trac.wordpress.org/changeset/51205/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyfourteen/functions.php
> +	wp_enqueue_style( 'twentyfourteen-ie', get_template_directory_uri() . '/css/ie.css', array( 'twentyfourteen-style' ), '20221025' );
This should be This should be `20140711`, last changed [here](https://core.trac.wordpress.org/changeset/29101/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyfourteen/functions.php
> +		wp_enqueue_script( 'twentyfourteen-keyboard-image-navigation', get_template_directory_uri() . '/js/keyboard-image-navigation.js', array( 'jquery' ), '20221025' );
No [recent changes](https://core.trac.wordpress.org/log/trunk/src/wp-content/themes/twentyfourteen/js/keyboard-image-navigation.js). Please leave as it was previously.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyfourteen/functions.php
> +		wp_enqueue_script( 'twentyfourteen-slider', get_template_directory_uri() . '/js/slider.js', array( 'jquery' ), '20221025', true );
No [recent changes](https://core.trac.wordpress.org/log/trunk/src/wp-content/themes/twentyfourteen/js/slider.js). Please leave as it was previously.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyfourteen/functions.php
> +	wp_enqueue_script( 'twentyfourteen-script', get_template_directory_uri() . '/js/functions.js', array( 'jquery' ), '20221025', true );
This one should be `20210122`, last changed [here](https://core.trac.wordpress.org/changeset/50001/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyfourteen/functions.php
> -	wp_enqueue_style( 'twentyfourteen-block-editor-style', get_template_directory_uri() . '/css/editor-blocks.css', array(), '20201208' );
This one should be changed to `20210216`, last changed [here](https://core.trac.wordpress.org/changeset/50358/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentynineteen/functions.php
> +		wp_enqueue_script( 'twentynineteen-priority-menu', get_theme_file_uri( '/js/priority-menu.js' ), array(), '20221025', true );
Both of these dates should be set to `20200129`, last changed [here](https://core.trac.wordpress.org/changeset/47122/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyseventeen/functions.php
> +		wp_enqueue_style( 'twentyseventeen-colors-dark', get_theme_file_uri( '/assets/css/colors-dark.css' ), array( 'twentyseventeen-style' ), '20221025' );
This one should be `20191025`, last changed [here](https://core.trac.wordpress.org/changeset/46586/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyseventeen/functions.php
> +		wp_enqueue_style( 'twentyseventeen-ie9', get_theme_file_uri( '/assets/css/ie9.css' ), array( 'twentyseventeen-style' ), '20221025' );
This should be left as it was.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyseventeen/functions.php
> +	wp_enqueue_style( 'twentyseventeen-ie8', get_theme_file_uri( '/assets/css/ie8.css' ), array( 'twentyseventeen-style' ), '20221025' );
This should be left as it was.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyseventeen/functions.php
> +	wp_enqueue_script( 'html5', get_theme_file_uri( '/assets/js/html5.js' ), array(), '20221025' );
This should be left as it was.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyseventeen/functions.php
> +	wp_enqueue_script( 'twentyseventeen-skip-link-focus-fix', get_theme_file_uri( '/assets/js/skip-link-focus-fix.js' ), array(), '20221025', true );
This should be left as it was.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyseventeen/functions.php
> +		wp_enqueue_script( 'twentyseventeen-navigation', get_theme_file_uri( '/assets/js/navigation.js' ), array( 'jquery' ), '20221025', true );
This one should be `20210122`, last changed [here](https://core.trac.wordpress.org/changeset/50001).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyseventeen/functions.php
> +	wp_enqueue_script( 'twentyseventeen-global', get_theme_file_uri( '/assets/js/global.js' ), array( 'jquery' ), '20221025', true );
This one should be `20211130`, last changed [here](https://core.trac.wordpress.org/changeset/52285/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentysixteen/functions.php
> +	wp_enqueue_style( 'genericons', get_template_directory_uri() . '/genericons/genericons.css', array(), '20221025' );
This one was correct.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentysixteen/functions.php
> +	wp_enqueue_style( 'twentysixteen-block-style', get_template_directory_uri() . '/css/blocks.css', array( 'twentysixteen-style' ), '20221025' );
This one was correct.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentysixteen/functions.php
> +	wp_enqueue_style( 'twentysixteen-ie', get_template_directory_uri() . '/css/ie.css', array( 'twentysixteen-style' ), '20221025' );
This one was correct.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentysixteen/functions.php
> +	wp_enqueue_style( 'twentysixteen-ie8', get_template_directory_uri() . '/css/ie8.css', array( 'twentysixteen-style' ), '20221025' );
This one was correct.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentysixteen/functions.php
> +	wp_enqueue_style( 'twentysixteen-ie7', get_template_directory_uri() . '/css/ie7.css', array( 'twentysixteen-style' ), '20221025' );
This one was correct.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentysixteen/functions.php
> +		wp_enqueue_script( 'twentysixteen-keyboard-image-navigation', get_template_directory_uri() . '/js/keyboard-image-navigation.js', array( 'jquery' ), '20221025' );
This one was correct.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentysixteen/functions.php
> +	wp_enqueue_script( 'twentysixteen-skip-link-focus-fix', get_template_directory_uri() . '/js/skip-link-focus-fix.js', array(), '20221025', true );
This one was correct.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentysixteen/functions.php
> +	wp_enqueue_script( 'twentysixteen-script', get_template_directory_uri() . '/js/functions.js', array( 'jquery' ), '20221025', true );
This one should be `20211130`, last changed [here](https://core.trac.wordpress.org/changeset/52285/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentysixteen/functions.php
> +	wp_enqueue_style( 'twentysixteen-block-editor-style', get_template_directory_uri() . '/css/editor-blocks.css', array(), '20221025' );
This one should be `20210216`, last changed [here](https://core.trac.wordpress.org/changeset/50358/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyten/functions.php
> +	wp_enqueue_style( 'twentyten-block-editor-style', get_template_directory_uri() . '/editor-blocks.css', array(), '20221025' );
This one was correct.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyten/functions.php
> +	wp_enqueue_style( 'twentyten-block-style', get_template_directory_uri() . '/blocks.css', array(), '20221025' );
This one should be `20190704`, last changed [here](https://core.trac.wordpress.org/changeset/45592/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentythirteen/functions.php
> +	wp_enqueue_script( 'twentythirteen-script', get_template_directory_uri() . '/js/functions.js', array( 'jquery' ), '20221025', true );
This one should be `20210122`, last changed [here](https://core.trac.wordpress.org/changeset/50001/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentythirteen/functions.php
> +	wp_enqueue_style( 'twentythirteen-block-style', get_template_directory_uri() . '/css/blocks.css', array( 'twentythirteen-style' ), '20221025' );
This should be `20210622`, last changed [here](https://core.trac.wordpress.org/changeset/51205/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentythirteen/functions.php
> +	wp_enqueue_style( 'twentythirteen-ie', get_template_directory_uri() . '/css/ie.css', array( 'twentythirteen-style' ), '20221025' );
This one was correct.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentythirteen/functions.php
> +	wp_enqueue_style( 'twentythirteen-block-editor-style', get_template_directory_uri() . '/css/editor-blocks.css', array(), '20221025' );
This one should be `20210621`, last changed [here](https://core.trac.wordpress.org/changeset/51192/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentythirteen/functions.php
> +	wp_enqueue_script( 'twentythirteen-customizer', get_template_directory_uri() . '/js/theme-customizer.js', array( 'customize-preview' ), '20221025', true );
This one should be `20200516`, last changed [here](https://core.trac.wordpress.org/changeset/47808/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentytwelve/functions.php
> +	wp_enqueue_script( 'twentytwelve-navigation', get_template_directory_uri() . '/js/navigation.js', array( 'jquery' ), '20221025', true );
This one was correct.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentytwelve/functions.php
> +	wp_enqueue_style( 'twentytwelve-block-style', get_template_directory_uri() . '/css/blocks.css', array( 'twentytwelve-style' ), '20221025' );
This one was correct.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentytwelve/functions.php
> +	wp_enqueue_style( 'twentytwelve-ie', get_template_directory_uri() . '/css/ie.css', array( 'twentytwelve-style' ), '20221025' );
This one was correct.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentytwelve/functions.php
> +	wp_enqueue_style( 'twentytwelve-block-editor-style', get_template_directory_uri() . '/css/editor-blocks.css', array(), '20221025' );
This should be `20200713`, last changed [here](https://core.trac.wordpress.org/changeset/48459/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyfifteen/functions.php
> +	wp_enqueue_style( 'twentyfifteen-style', get_stylesheet_uri(), array(), '20221025' );
The release date for all themes will be November 1, 2022. Could you update all of the date based versions for the main stylesheets to `20221101` so that is properly reflected?

There are exceptions to this, which I'll note individually.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyeleven/functions.php
> +	wp_enqueue_style( 'twentyeleven-block-editor-style', get_template_directory_uri() . '/editor-blocks.css', array(), '20221025' );
This one should be `20220927` (last [changed here](https://core.trac.wordpress.org/changeset/54340/)).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyfifteen/functions.php
> +	wp_enqueue_style( 'twentyfifteen-block-style', get_template_directory_uri() . '/css/blocks.css', array( 'twentyfifteen-style' ), '20221025' );
This one should be `20220914`, last changed [here](https://core.trac.wordpress.org/changeset/54151/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyfifteen/functions.php
> +	wp_enqueue_style( 'twentyfifteen-ie', get_template_directory_uri() . '/css/ie.css', array( 'twentyfifteen-style' ), '20221025' );
This should be `20220908`, last changed [here](https://core.trac.wordpress.org/changeset/54109/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyfifteen/functions.php
> +	wp_enqueue_style( 'twentyfifteen-block-editor-style', get_template_directory_uri() . '/css/editor-blocks.css', array(), '20221025' );
This should be `20220908`, last changed [here](https://core.trac.wordpress.org/changeset/54109/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentytwentyone/package-lock.json
> +	"lockfileVersion": 2,
Please fix using npm < 7.

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentytwelve/functions.php
> +	wp_enqueue_script( 'twentytwelve-customizer', get_template_directory_uri() . '/js/theme-customizer.js', array( 'customize-preview' ), '20221025', true );
This should be `20200516`, last changed [here](https://core.trac.wordpress.org/changeset/47808/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyseventeen/functions.php
> +	wp_enqueue_style( 'twentyseventeen-block-editor-style', get_theme_file_uri( '/assets/css/editor-blocks.css' ), array(), '20221025' );
This should be `20220912`, last changed [here](https://core.trac.wordpress.org/changeset/54139/).

2022-09-30 16:04 UTC, desrosj commented on src/wp-content/themes/twentyseventeen/functions.php
> +	wp_enqueue_style( 'twentyseventeen-block-style', get_theme_file_uri( '/assets/css/blocks.css' ), array( 'twentyseventeen-style' ), '20221025' );
This one should be `20220912`, last changed [here](https://core.trac.wordpress.org/changeset/54139/).

2022-10-02 06:35 UTC, robinwpdeveloper commented
Thanks @desrosj 
I have updated as per your requested changes.

Can you please re review?

2022-10-11 01:33 UTC, desrosj requested changes
Looking good! @robinwpdeveloper could you fix the merge conflicts from [Trac-54404](https://core.trac.wordpress.org/changeset/54404) and [Trac-54405](https://core.trac.wordpress.org/changeset/54405)?

Also, it looks like the `package-lock.json` file for Twenty Twenty is still using version 2 lock file schema from `npm >= 7`.

2022-10-11 05:13 UTC, robinwpdeveloper commented
Hi @desrosj 
I have fixed as per changesheet (manually did this).

Still 3 files has conflict. 
Can you please fix these for me? 

Or, let me know how to fix these conflicts.

Thanks.

2022-10-11 17:01 UTC, desrosj commented
Thanks @robinwpdeveloper! I am going to commit this and I'll fix those oddities during that process. There are a few additional changes that happened over the last week that will require another change to the version. But I'll also handle those.

2022-10-11 18:36 UTC, desrosj commented
Merged into Core in https://core.trac.wordpress.org/changeset/54492.

2022-10-11 18:37 UTC, closed without merging