PHP 8.1 | WP_Scripts::localize(): fix autovivification from false to array bug
WordPress/wordpress-develop pull request #3185
Opened 2022-09-05 11:30 UTC by jrfnl

👉🏻 **This PR is part of a series of PRs to get the builds passing on PHP 8.1 (to prevent having to _also_ allow failures on PHP 8.2, even when the PHP 8.2 issues are fixed (for a certain definition of "fixed")).**

---

This function was previously already problematic as it does not do proper input validation and the function already received tweaks related to PHP 8.0 in [50408] / Trac#52534, which also introduced the `_doing_it_wrong()` and added tests.

The short of it is:
* The function expects to receive an `array` for the `$l10n` parameter;
* ... but silently supported the parameter being passed as a `string`;
* ... and would expect PHP to gracefully handle everything else or throw appropriate warnings/errors.

In the previous fix, a `_doing_it_wrong()` was added for all non-array inputs.
The function would also cause a PHP native "Cannot use a scalar value as an array" warning (PHP < 8.0)/error (PHP 8.0) for all scalar values, except `false`.

PHP 8.1 deprecated autovivification from `false` to `array`, so now `false` starts throwing a "Automatic conversion of false to array is deprecated" deprecation notice.

By rights, the function should just throw an exception when a non-array/string input is received, but BC...

So, while I really hate doing this, the current change will maintain the previous behaviour, but will prevent both the "Cannot use a scalar value as an array" warning/error as well as the "Automatic conversion of false to array" deprecation notice for invalid inputs.

Invalid inputs _will_ still receive a `_doing_it_wrong()`, which is the only reason I find this fix even remotely acceptable.

Includes adding a test passing an empty array.
Includes adding an additional test to the data provider for a `null` input to safeguard the function will not throw a PHP 8.1 "passing null to non-nullable" notice.

Fixes:
```
3) Tests_Dependencies_Scripts::test_wp_localize_script_data_formats with data set #8 (false, '[""]')
Automatic conversion of false to array is deprecated

/var/www/src/wp-includes/class.wp-scripts.php:514
/var/www/src/wp-includes/functions.wp-scripts.php:221
/var/www/tests/phpunit/tests/dependencies/scripts.php:1447
/var/www/vendor/bin/phpunit:123
```

Refs:
* https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.core.autovivification-false

Trac ticket: https://core.trac.wordpress.org/ticket/55656

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2022-09-07 00:23 UTC, costdev requested changes
The docblock for the `data_wp_localize_script_data_formats()` provider also contains a param annotation for `$warning` on line 1454 which can also be removed.

Other than that, the rest looks good to me!

2022-09-07 09:48 UTC, jrfnl commented
> The docblock for the `data_wp_localize_script_data_formats()` provider also contains a param annotation for `$warning` on line 1454 which can also be removed.

Good catch! Fixed ;-)

2022-09-07 18:37 UTC, costdev approved these changes
LGTM :+1:

2022-09-13 16:04 UTC, SergeyBiryukov commented
Thanks for the PR! Merged in [r54142](https://core.trac.wordpress.org/changeset/54142).

2022-09-13 16:04 UTC, closed without merging

2022-09-13 20:21 UTC, jrfnl commented
Thanks @SergeyBiryukov !