56532 add notice
WordPress/wordpress-develop pull request #3213
Opened 2022-09-08 08:02 UTC by robinwpdeveloper

Security notice added for 4.0 or older version.

Trac ticket: [https://core.trac.wordpress.org/ticket/56532](https://core.trac.wordpress.org/ticket/56532)

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2022-09-09 09:23 UTC, rudlinkon commented on src/wp-admin/update-core.php
> +		if ( ! empty( $wp_version ) && $wp_version <= 4.0 ) {
```suggestion
		if ( version_compare( $wp_version, '4.1.0', '<' ) ) {
```

2022-09-09 09:27 UTC, rudlinkon requested changes
it is safe to use `version_compare` function and no need to check if is it empty because this variable is already used in the upper block.

2022-09-09 11:40 UTC, robinwpdeveloper commented
Thanks @rudlinkon . Requested changes are made and pushed.

2022-09-11 09:59 UTC, mukeshpanchal27 reviewed
@robinwpdeveloper Left feedback for translator document.

2022-09-11 09:59 UTC, mukeshpanchal27 commented on src/wp-admin/update-core.php
> +				/* translators: 1: Documentation on WordPress backups, 2: Documentation on updating WordPress. */
It should be WordPress version.

```suggestion
				/* translators: 1: WordPress version, 2: Documentation on updating WordPress. */
```

2022-09-11 10:38 UTC, robinwpdeveloper commented
Thanks @mukeshpanchal27 . Code updated.

2022-09-23 14:46 UTC, qasumitbagthariya commented
I have tested this PR in WordPress 3.9.37 and it is working as expected, Please note I have manually put the PR code in the `src/wp-admin/update-core.php` file. Please check the video.

**Environment**
OS: Windows 10
Web Server: nginx/1.16.5
PHP: 7.4.27 
WordPress: 3.9.37
Theme: Twentytwentytwo

**Browsers:**
Chrome - Version 105.0.5195.127 (Official Build) (64-bit)


https://user-images.githubusercontent.com/67687255/191986979-8664227c-7599-4bfa-a534-a23425aca816.mp4

![image](https://user-images.githubusercontent.com/67687255/191987080-8f6d065c-1bcf-4b8c-a5e8-762f6a8a227c.png)
![image](https://user-images.githubusercontent.com/67687255/191987362-2dca8a14-9217-45f7-a882-b1b8c639874d.png)

2022-09-23 14:54 UTC, rudlinkon commented
> I have tested this PR in WordPress 3.9.37 and it is working as expected, Please note I have manually put the PR code in the `src/wp-admin/update-core.php` file. Please check the video.
> 
> **Environment** OS: Windows 10 Web Server: nginx/1.16.5 PHP: 7.4.27 WordPress: 3.9.37 Theme: Twentytwentytwo
> 
> **Browsers:** Chrome - Version 105.0.5195.127 (Official Build) (64-bit)
> 
>  56532.add.notice.by.robinwpdeveloper.Pull.Request.3213.WordPress_wordpress-develop.-.Google.Chrome.-.23.September.2022.mp4 
> ![image](https://user-images.githubusercontent.com/67687255/191987080-8f6d065c-1bcf-4b8c-a5e8-762f6a8a227c.png) ![image](https://user-images.githubusercontent.com/67687255/191987362-2dca8a14-9217-45f7-a882-b1b8c639874d.png)

Thank you @qasumitbagthariya for testing the PR

2022-09-25 23:50 UTC, peterwilsoncc commented
As mentioned on trac, for versions trunk and versions 4.0 and above the strings can be added to the collection of release related strings after the `return` statement.

This will allow the translation team to begin translating them without the need for additional code wrapped in the conditional.

https://github.com/WordPress/wordpress-develop/blob/8f3254d794ca4e8b8e0ec8254e5886be840a60c6/src/wp-admin/about.php#L342-L378

There are two strings that need to be  added to the about page:

```php
/* translators: 1: WordPress version number, 2: Link to update WordPress */
__( 'Important! Your version of WordPress (%1$s) is no longer supported, you will not receive any security updates for your website. To keep your site secure, please <a href="%2$s">update to the latest version of WordPress</a>.' );

/* translators: 1: WordPress version number, 2: Link to update WordPress */
__( 'Important! Your version of WordPress (%1$s) will stop receiving security updates in the near future. To keep your site secure, please <a href="%2$s">update to the latest version of WordPress</a>.' );
```

On the ticket, I've uploaded some patches for WordPress 3.7 - 4.0 that include the CSS changes required to make the update notice more prominent.

2022-09-27 04:40 UTC, peterwilsoncc reviewed
The strings have been added correctly in the about page, thank you!

Are you able to remove the changes to `update-core.php` as they won't be needed for the current versions of WordPress for some time. I have some separate patches on trac for the versions of WP that will shortly be losing support

2022-09-27 04:40 UTC, peterwilsoncc commented on src/wp-admin/update-core.php
> +		}
```suggestion
```

2022-09-27 04:55 UTC, robinwpdeveloper commented
Thanks @peterwilsoncc 
Code updated as per your suggestion.

2022-09-27 05:14 UTC, peterwilsoncc approved these changes
Thanks so much, I think this is ready.

2022-09-27 06:14 UTC, peterwilsoncc commented
Merged in https://core.trac.wordpress.org/changeset/54322 / 1de72e40208fcf45e44b26ad79a1fd3322ca1a2e

2022-09-27 06:14 UTC, closed without merging