Improves the consistency in capitalization of fetching and outputting of request headers
WordPress/wordpress-develop pull request #3243
Opened 2022-09-14 11:36 UTC by mhkuu

Adapted during **Yoast Contributor Day** on Friday 4 November.

Improves the consistency in capitalization of fetching and outputting of request headers. See the Trac ticket for details.

Trac ticket: https://core.trac.wordpress.org/ticket/54225

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2023-01-20 06:11 UTC, costdev requested changes
Thanks for the PR @mhkuu! I've left a couple of notes about two files that are part of external libraries and should not be patched in this PR.

2023-01-20 06:11 UTC, costdev commented on src/wp-includes/Requests/Transport/fsockopen.php
> +			// Always include Content-Length on POST requests to prevent
This file is part of an external library and should not be patched in the PR.

2023-01-20 06:11 UTC, costdev commented on src/wp-includes/SimplePie/Misc.php
> +		header('Content-Type: text/javascript; charset: UTF-8');
This file is part of an external library and should not be patched in this PR.

2023-01-28 01:42 UTC, costdev approved these changes
Thanks for the updates @mhkuu! LGTM :+1:

2023-02-03 13:34 UTC, audrasjb commented
Committed in https://core.trac.wordpress.org/changeset/55210

2023-02-03 13:34 UTC, closed without merging