check to ensure $field is an array
WordPress/wordpress-develop pull request #3323
Opened 2022-09-24 23:07 UTC by afragen

Add a check to the `else` as `elseif` to ensure `$field` is an array when it is treated as such.

Trac ticket: https://core.trac.wordpress.org/ticket/56650

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2022-09-28 20:57 UTC, costdev requested changes
Just some minor suggestions. Still needs unit tests - I'm happy to take a look at those.

2022-09-28 20:57 UTC, costdev commented on src/wp-includes/class-wp-list-util.php
> +				if ( ! ( is_object( $value ) || is_array( $value ) ) ) {
```suggestion
				if ( ! is_object( $value ) && ! is_array( $value ) ) {
```
IMO, this is a little easier to read. Just a suggestion though. Same suggestion for the later instance.

2022-09-28 20:57 UTC, costdev commented on src/wp-includes/class-wp-list-util.php
> +						__( 'Value for `$this->output` must be either an object or an array for this function.' ),
```suggestion
						__( "Values for the input array must be either objects or arrays.' ),
```
Same suggestion in the later instance.

2022-09-28 21:06 UTC, costdev commented on src/wp-includes/class-wp-list-util.php
> +				if ( ! ( is_object( $value ) || is_array( $value ) ) ) {
Hmm...

Starting to wonder if an `else` is more appropriate for the `_doing_it_wrong()` condition. That saves on some checks.

i.e.
Currently:
- Good object data: `if is object` + `if not object and not array` (2)
- Good array data: `if is object` + `else if is array` + `if not object and not array` (3)
- Bad data: `if is object` + `else if is array` + `if not object and not array` (3)

With `else`:
- Good object data: `if is object` (1)
- Good array data: `if is object` + `else if is array` (2)
- Bad data: `if is object` + `else if is array` + `else` (3ish)

2022-09-28 21:33 UTC, afragen commented
@costdev I think I've resolved the above issues.

2022-10-06 22:28 UTC, costdev approved these changes
LGTM :+1:

2022-10-09 23:25 UTC, audrasjb commented on tests/phpunit/tests/functions/wpListPluck.php
> +		$this->assertSame( array(), wp_list_pluck( $input, 'a_field' ) ); // I think...
Is the "// I think..." comment intended?

2022-10-09 23:25 UTC, audrasjb commented on tests/phpunit/tests/functions/wpListPluck.php
> +		$this->assertSame( array(), wp_list_pluck( $input, 'a_field', 'an_index_key' ) ); // I think...
Is the "// I think..." comment intended?

2022-10-09 23:27 UTC, afragen commented on tests/phpunit/tests/functions/wpListPluck.php
> +		$this->assertSame( array(), wp_list_pluck( $input, 'a_field' ) ); // I think...
@costdev I think these are for you 😉

2022-10-12 20:49 UTC, costdev commented on tests/phpunit/tests/functions/wpListPluck.php
> +		$this->assertSame( array(), wp_list_pluck( $input, 'a_field' ) ); // I think...
...woops! Nope, that was left over from pseudo during a DM chat about the tests. :sweat_smile:

2023-02-25 11:01 UTC, SergeyBiryukov commented
Thanks for the PR! Merged in [r55423](https://core.trac.wordpress.org/changeset/55423).

Note: As `wp_list_pluck()` is just a wrapper and the actual source code change was in `WP_List_Util::pluck()`, I have moved the tests to the class where all the other tests for `WP_List_Util` are located.

2023-02-25 11:01 UTC, closed without merging