Introduce `switch_to_user_locale()`
WordPress/wordpress-develop pull request #3637
Opened 2022-11-16 10:34 UTC by swissspidy

Trac ticket: https://core.trac.wordpress.org/ticket/57123

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2022-11-16 14:07 UTC, costdev commented on src/wp-includes/class-wp-locale-switcher.php
> +		$locale = $entry[0];
```suggestion
		$locale = is_array( $entry ) ? $entry[0] : false;
```
This should resolve the test failures

2022-11-16 14:47 UTC, swissspidy commented on src/wp-includes/class-wp-locale-switcher.php
> +		$locale = $entry[0];
Ah, thanks 👍

2022-11-29 12:33 UTC, costdev requested changes

2022-11-29 12:33 UTC, costdev commented on src/wp-includes/class-wp-locale-switcher.php
> +	 * @return false|string Locale if the locale has been switched, false otherwise.
```suggestion
	 * @return string|false Locale if the locale has been switched, false otherwise.
```

2022-11-29 12:33 UTC, costdev commented on src/wp-includes/ms-functions.php
> +	$switched_locale = switch_to_user_locale( $user->ID );
If `get_user_by()` returns `false`, `$user->ID` will throw a warning `Attempt to read property "ID" on bool`.

Previously, `switch_to_locale()` handled a `false` value by returning `false`.

I suggest a change to:

```suggestion
	$switched_locale = $user instanceof WP_User ? switch_to_user_locale( $user->ID ) : false;
```

2022-11-29 12:33 UTC, costdev commented on src/wp-includes/ms-functions.php
> +	$switched_locale = switch_to_user_locale( $user->ID );
See above regarding `get_user_by()`

2022-11-30 06:11 UTC, costdev commented on src/wp-includes/class-wp-locale-switcher.php
> +		$locale = is_array( $entry ) ? $entry[0] : false;
```suggestion
		$entry  = end( $this->stack );
		$locale = is_array( $entry ) ? $entry[0] : false;
```
Not sure how PHPCS didn't fail on this in CI 🤔. It produces a warning locally at least.

2022-11-30 06:13 UTC, costdev approved these changes
Aside from one last minor comment about aligning equals signs, the rest of the PR looks good to me.

As I've looked at the PR a few times, I'll leave it to other contributors to review in case there's anything I've missed.

Thanks @swissspidy!

2023-01-29 03:32 UTC, costdev requested changes
Hi @swissspidy, I've left a few more thoughts. :slightly_smiling_face:

2023-01-29 03:32 UTC, costdev commented on tests/phpunit/tests/l10n/wpLocaleSwitcher.php
> +	 * @covers ::switch_to_locale
```suggestion
	 * @ticket 57123
	 *
	 * @covers ::switch_to_locale
```

2023-01-29 03:32 UTC, costdev commented on tests/phpunit/tests/l10n/wpLocaleSwitcher.php
> +	 * @covers ::switch_to_locale
```suggestion
	 * @ticket 57123
	 *
	 * @covers ::switch_to_locale
```

2023-01-29 03:32 UTC, costdev commented on tests/phpunit/tests/l10n/wpLocaleSwitcher.php
> +		$this->assertFalse( $locale_1 );
Can you add another parameter to the end of each of the assertions to describe what went wrong should one of them fail?

That way, contributors can see _which_ of the `assertFalse()` or `assertSame()` failed, with some added context.

e.g.

`$this->assertFalse( $locale_1, 'Locale should be false before switching.' );`

`$this->assertSame( 'de_DE', $locale_2, 'The locale was not changed to de_DE.' );`

and so on.

Note: This is required as documented in the [Writing PHPUnit Tests - Using Assertions entry](https://make.wordpress.org/core/handbook/testing/automated-testing/writing-phpunit-tests/#using-assertions) handbook entry:
> All PHPUnit assertions, as well as all WordPress custom assertions, allow for a `$message` parameter to be passed. This message will be displayed when the assertion fails and can help immensely when debugging a test. This parameter should always be used if more than one assertion is used in a test method.

2023-01-29 17:02 UTC, costdev commented on tests/phpunit/tests/l10n/wpLocaleSwitcher.php
> +	 * @covers ::switch_to_locale
Just this one left I think :slightly_smiling_face:

2023-01-29 22:36 UTC, costdev approved these changes
Thanks for the updates @swissspidy! LGTM :+1:

2023-01-30 10:25 UTC, ocean90 reviewed
Can we have a test which demonstrates the behavior when mixing `switch_to_locale()`, `switch_to_user_locale()`, and `restore_previous_locale()`?

2023-01-30 10:25 UTC, ocean90 commented on src/wp-includes/class-wp-locale-switcher.php
> +		 * @param null|int $user_id User ID for context if available.
```suggestion
		 * @param false|int $user_id User ID for context if available.
```

2023-01-30 10:26 UTC, swissspidy commented
Committed in https://core.trac.wordpress.org/changeset/55161

2023-01-30 10:26 UTC, closed without merging