added tests for wp_check_filetype
WordPress/wordpress-develop pull request #3648
Opened 2022-11-18 21:34 UTC by pbearne

Just tests

Trac ticket: [](https://core.trac.wordpress.org/ticket/57151)

2022-11-20 02:42 UTC, costdev requested changes
Thanks for the PR @pbearne!

I've left suggestions to bring the tests up to Core standards and have suggested four additional datasets.

Note that there may be PHPCS array alignment failures if these suggestions are applied directly in GitHub.

2022-11-20 02:42 UTC, costdev commented on tests/phpunit/tests/functions/wpCheckFiletype.php
> + */
```suggestion
/**
 * Tests the wp_check_filetype() function.
 *
 * @group functions.php
 * @group upload
 * 
 * @covers ::wp_check_filetype
 */
```

2022-11-20 02:42 UTC, costdev commented on tests/phpunit/tests/functions/wpCheckFiletype.php
> +class Test_wp_check_filetype extends WP_UnitTestCase {
```suggestion
class Tests_Functions_WpCheckFiletype extends WP_UnitTestCase {
```

2022-11-20 02:42 UTC, costdev commented on tests/phpunit/tests/functions/wpCheckFiletype.php
> +	 * @dataProvider wp_check_filetype_dataset
```suggestion
	 * @ticket 57151
	 *
	 * @dataProvider data_wp_check_filetype
	 *
	 * @param string     $filename The filename to check.
	 * @param array|null $mimes    An array of mimetypes.
	 * @param array      $expected An array containing the extension and mimetype.
```

2022-11-20 02:42 UTC, costdev commented on tests/phpunit/tests/functions/wpCheckFiletype.php
> +	}
```suggestion
	public function test_wp_check_filetype( $filename, $mimes, $expected ) {
		$this->assertSame( $expected, wp_check_filetype( $filename, $mimes ) );
	}
```

2022-11-20 02:42 UTC, costdev commented on tests/phpunit/tests/functions/wpCheckFiletype.php
> +	function wp_check_filetype_dataset() {
```suggestion
	/**
	 * Data provider for test_wp_check_filetype().
	 *
	 * @return array[]
	 */
	public function data_wp_check_filetype() {
```

2022-11-20 02:42 UTC, costdev commented on tests/phpunit/tests/functions/wpCheckFiletype.php
> +			'default'     => array(
```suggestion
			'.jpg and default allowed mimetypes' => array(
```

2022-11-20 02:42 UTC, costdev commented on tests/phpunit/tests/functions/wpCheckFiletype.php
> +				'mines'    => null,
```suggestion
				'mimes'    => null,
```
While this dataset covers the defaults (i.e. `null`), I'd also suggest an additional dataset that sets `$mimes` to `array()` to reflect an `empty()` value of the documented datatype.

2022-11-20 02:42 UTC, costdev commented on tests/phpunit/tests/functions/wpCheckFiletype.php
> +			'short_mines' => array(
```suggestion
			'.jpg and jpg|jpeg|jpe mimetypes'    => array(
```
I'd also suggest these additional datasets:
1. A `.jpeg` file with the same value for `$mimes` as this dataset.
2. A `.jpe` file with the same value for `$mimes` as this dataset.
3. A `.JPG` file (uppercase) to ensure the regex in `wp_check_filetype()` is always case-insensitive.

2022-11-20 02:42 UTC, costdev commented on tests/phpunit/tests/functions/wpCheckFiletype.php
> +				'mines'    => array(
```suggestion
				'mimes'    => array(
```

2022-11-20 02:42 UTC, costdev commented on tests/phpunit/tests/functions/wpCheckFiletype.php
> +			'badfile'     => array(
```suggestion
			'.XXX and no matching mimetype'      => array(
```

2022-11-20 02:42 UTC, costdev commented on tests/phpunit/tests/functions/wpCheckFiletype.php
> +				'mines'    => array(
```suggestion
				'mimes'    => array(
```

2022-11-20 02:42 UTC, costdev commented on tests/phpunit/tests/functions/wpCheckFiletype.php
> +			'bad_mines'   => array(
```suggestion
			'.jpg but only gif allowed'          => array(
```

2022-11-20 02:42 UTC, costdev commented on tests/phpunit/tests/functions/wpCheckFiletype.php
> +				'mines'    => array(
```suggestion
				'mimes'    => array(
```

2022-11-20 02:42 UTC, costdev commented on tests/phpunit/tests/functions/wpCheckFiletype.php
> +
```suggestion
```

2023-03-02 21:04 UTC, hellofromtonya commented
Closing in favor of https://github.com/WordPress/wordpress-develop/pull/4158, which was committed.

2023-03-02 21:04 UTC, closed without merging