test for _mce_set_direction
WordPress/wordpress-develop pull request #3675
Opened 2022-11-24 01:30 UTC by pbearne

Trac ticket: https://core.trac.wordpress.org/ticket/57192

2022-11-24 06:40 UTC, mukeshpanchal27 reviewed
Thanks @pbearne Left some minor formatting feedback.

The message needs to update with more context.

2022-11-24 06:40 UTC, mukeshpanchal27 commented on tests/phpunit/tests/functions/mceSetDirection.php
> + */#
```suggestion
 */
```

2022-11-24 06:40 UTC, mukeshpanchal27 commented on tests/phpunit/tests/functions/mceSetDirection.php
> +		$this->assertEquals( $mce_init, _mce_set_direction( $mce_init ), ' set to ltr' );
```suggestion
		$this->assertEquals( $mce_init, _mce_set_direction( $mce_init ), 'set to ltr' );
```

2022-11-26 23:13 UTC, costdev requested changes
Thanks for the PR @pbearne! I've left some thoughts below for standards, stricter testing and test stability.

2022-11-26 23:13 UTC, costdev commented on tests/phpunit/tests/functions/mceSetDirection.php
> +	public function test__mce_set_direction() {
```suggestion
	public function test_mce_set_direction() {
```
A double `_` is not convention in the test suite, even for `_private` functions.

2022-11-26 23:13 UTC, costdev commented on tests/phpunit/tests/functions/mceSetDirection.php
> +		$this->assertEquals( $mce_init, _mce_set_direction( $mce_init ), ' set to ltr' );
As a string array, `assertSame()` should be used here.

2022-11-26 23:13 UTC, costdev commented on tests/phpunit/tests/functions/mceSetDirection.php
> +		$this->assertEquals( $mce_init_expected, _mce_set_direction( $mce_init ), "checking we don't get to strings added" );
For test stability, the test method should use a data provider that accepts `(string) $text_direction`, `(array) $init_args` and `(array) $expected` parameters, should document these parameters at the bottom of the test method's docblock, and the data provider should contain a dataset for each of these tests.

2022-11-26 23:13 UTC, costdev commented on tests/phpunit/tests/functions/mceSetDirection.php
> +		$wp_locale->text_direction = $direction;
This should be reset before the assertion in case of test failure.

2024-02-27 19:40 UTC, swissspidy commented
https://core.trac.wordpress.org/changeset/57718

2024-02-27 19:40 UTC, closed without merging