WordPress 3.7 final release patches.
WordPress/wordpress-develop pull request #3684
Opened 2022-11-25 03:40 UTC by peterwilsoncc

https://core.trac.wordpress.org/ticket/56786 targeting 3.8 branch.

2022-11-28 00:43 UTC, audrasjb requested changes

2022-11-28 00:43 UTC, audrasjb commented on src/wp-admin/includes/update.php
> +			'https://wordpress.org/download/'
`'https://wordpress.org/download/'` should be a translatable string so it can be localized for each language.

2022-11-28 08:58 UTC, audrasjb approved these changes

2022-11-29 22:36 UTC, peterwilsoncc commented
Merged in https://core.trac.wordpress.org/changeset/54900

2022-11-29 22:36 UTC, closed without merging