Drop the usage of the local CSS rule
WordPress/wordpress-develop pull request #3826
Opened 2023-01-07 10:46 UTC by Luehrsen

As discussed [here](https://core.trac.wordpress.org/ticket/55985#comment:16), loading the local font file can lean to unexpected compatibility issues due to version or locale mismatches of the font.

Vendors like Google have dropped using local in their font delivery.

That is why I would propose dropping the local rule altogether.

Trac ticket: https://core.trac.wordpress.org/ticket/57430#ticket

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2023-01-29 03:05 UTC, costdev approved these changes
Thanks for the PR @Luehrsen! LGTM :+1:

2023-02-02 07:07 UTC, aristath approved these changes

2023-02-13 13:23 UTC, hellofromtonya requested changes

2023-02-13 13:23 UTC, hellofromtonya commented on src/wp-includes/script-loader.php
> +		return implode( ', ', $items );
This change is out-of-scope for the defect bugfix. Let's instead keep parity with the fix made in Gutenberg https://github.com/WordPress/gutenberg/pull/47254.

I'll update this PR.

2023-02-13 14:00 UTC, hellofromtonya commented on src/wp-includes/script-loader.php
> +		return implode( ', ', $items );
@Luehrsen Though I do understand why this change was made, I've reverted it for the commit.

Why? To keep it matching (parity with) the same code in the Fonts API (being developed in Gutenberg).

This is intentional to keep what's in Core synchronized with what's in the API being developed in Gutenberg.

This change could be considered in the Fonts API. Please feel free to open an [issue](https://github.com/WordPress/gutenberg/issues) and [PR](https://github.com/WordPress/gutenberg/pulls) for discussion. Thank you!

2023-02-13 14:01 UTC, hellofromtonya approved these changes
* Confirmed changes match (have parity with) the same fix made in the Font API https://github.com/WordPress/gutenberg/pull/47254 ✅ 
* Has change annotations ✅ 
* Works as expected ✅ 

Ready for commit 👍

2023-02-13 14:32 UTC, hellofromtonya commented
Committed via https://core.trac.wordpress.org/changeset/55314. Thanks for your contributions!

2023-02-13 14:32 UTC, closed without merging