57689
WordPress/wordpress-develop pull request #4052
Opened 2023-02-11 14:58 UTC by robinwpdeveloper

Trac ticket: https://core.trac.wordpress.org/ticket/57689

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2023-02-24 13:09 UTC, robinwpdeveloper commented
Hi @desrosj 
https://github.com/robinwpdeveloper/wordpress-develop/tree/57689 is now up to date with the latest trunk.

I think this is what you meant by refreshing PR.

2023-03-06 21:11 UTC, audrasjb commented
Hi @robinwpdeveloper, more than just refreshing against trunk, the idea was to implement the feedback of comment:8 (see the Trac ticket)

2023-03-07 06:23 UTC, costdev requested changes
Thanks for the PR @robinwpdeveloper! All the dates look good to me, pending confirmation about the three skipped files that need some feedback.

I've left some requested changes per [this comment on the ticket](https://core.trac.wordpress.org/ticket/57689#comment:9)

2023-03-07 06:23 UTC, costdev commented on src/wp-content/themes/twentytwenty/readme.txt
> +https://wordpress.org/support/article/twenty-twenty-changelog/#Version_2.2
```suggestion
https://wordpress.org/documentation/article/twenty-twenty-changelog/#Version_2.2
```
Per [this comment](https://core.trac.wordpress.org/ticket/57689#comment:9).

2023-03-07 06:23 UTC, costdev commented on src/wp-content/themes/twentytwentyone/readme.txt
> +https://wordpress.org/support/article/twenty-twenty-one-changelog#Version_1.8
```suggestion
https://wordpress.org/documentation/article/twenty-twenty-one-changelog/#Version_1.8
```
Per [this comment](https://core.trac.wordpress.org/ticket/57689#comment:9).

2023-03-07 06:23 UTC, costdev commented on src/wp-content/themes/twentytwentythree/readme.txt
> +https://wordpress.org/support/article/twenty-twenty-three-changelog#Version_1.1
```suggestion
https://wordpress.org/documentation/article/twenty-twenty-three-changelog/#Version_1.1
```
Per [this comment](https://core.trac.wordpress.org/ticket/57689#comment:9).

2023-03-07 06:23 UTC, costdev commented on src/wp-content/themes/twentytwentytwo/readme.txt
> +https://wordpress.org/support/article/twenty-twenty-two-changelog#Version_1.4
```suggestion
https://wordpress.org/documentation/article/twenty-twenty-two-changelog/#Version_1.4
```
Per [this comment](https://core.trac.wordpress.org/ticket/57689#comment:9).

2023-03-07 06:58 UTC, robinwpdeveloper commented
Thanks @audrasjb  and @costdev.
Requested changes are made.

2023-03-07 15:49 UTC, desrosj approved these changes
Thanks all! I've pushed a few more date/version changes that I noticed reviewing, and I also fixed the missing changes causing two themes to have unversioned changes after running `build` scripts.

2023-03-07 16:26 UTC, desrosj commented
Merged in https://core.trac.wordpress.org/changeset/55476

2023-03-07 16:26 UTC, closed without merging