Str starts with
WordPress/wordpress-develop pull request #4273
Opened 2023-03-31 23:07 UTC by spacedmonkey

Trac ticket: https://core.trac.wordpress.org/ticket/58012

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2023-04-01 06:48 UTC, sabernhardt commented
Please do not replace `strpos` in bundled themes. The themes should work with older versions of both PHP and WordPress (before the polyfill). The `str_starts_with` function was [already suggested](https://github.com/WordPress/wordpress-develop/pull/3992/files#r1096616940) for all the `$font_version` variables. Maybe these could have a note to explain it, though.

2023-04-05 12:17 UTC, costdev commented on src/wp-includes/PHPMailer/PHPMailer.php
> +                    && !str_starts_with($url, 'cid:')
External libraries shouldn't be touched by this PR right?

2023-04-17 13:08 UTC, spacedmonkey commented on src/wp-includes/PHPMailer/PHPMailer.php
> +                    && !str_starts_with($url, 'cid:')
```suggestion
                    && 0 !== strpos($url, 'cid:')
```

2023-04-17 13:08 UTC, spacedmonkey commented on src/wp-content/themes/twentyfifteen/functions.php
> +	$font_version = ( str_starts_with( (string) twentyfifteen_fonts_url(), get_template_directory_uri() . '/' ) ) ? '20230328' : null;
```suggestion
	$font_version = ( 0 === strpos( (string) twentyfifteen_fonts_url(), get_template_directory_uri() . '/' ) ) ? '20230328' : null;
```

2023-04-17 13:24 UTC, spacedmonkey commented
@sabernhardt  Removed changes to themes.

2023-04-22 14:19 UTC, SergeyBiryukov commented on src/wp-includes/class-simplepie.php
> +	if ( !str_starts_with( $class, 'SimplePie_' ) )
```suggestion
	if ( ! str_starts_with( $class, 'SimplePie_' ) )
```

2023-04-22 14:25 UTC, SergeyBiryukov commented
Looks good based on a visual review, left one suggestion in `wp-includes/class-simplepie.php`.

As a follow-up to this, `false !== strpos( ... )` can also be replaced with `str_contains()`, which is polyfilled in core as well.

2023-04-25 11:26 UTC, mukeshpanchal27 reviewed
Thanks @spacedmonkey, Great start. left a few suggestions for removing extra round brackets.

`if ( strpos( haystack, needle ) === 0 ) {` why this type of check is not consider in this PR? I found many instance in core for same.


**List of files:**
```
/src/wp-admin/load-styles.php
/src/wp-admin/includes/credits.php
/src/wp-admin/includes/template.php
/src/wp-includes/block-template.php
/src/wp-includes/bookmark-template.php
/src/wp-includes/class-wp.php
/src/wp-includes/functions.php
/src/wp-includes/l10n.php
/src/wp-includes/pluggable.php
/src/wp-includes/rest-api.php
/src/wp-includes/rewrite.php
/src/wp-includes/rest-api/class-wp-rest-server.php
/src/wp-includes/widgets/class-wp-widget-block.php
```

2023-04-25 11:26 UTC, mukeshpanchal27 commented on src/wp-admin/includes/class-wp-site-health.php
> +				$result['status'] = ( str_starts_with( ini_get( 'error_log' ), ABSPATH ) ) ? 'critical' : 'recommended';
```suggestion
				$result['status'] = str_starts_with( ini_get( 'error_log' ), ABSPATH ) ? 'critical' : 'recommended';
```

Remove extra round brackets.

2023-04-25 11:26 UTC, mukeshpanchal27 commented on src/wp-admin/includes/network.php
> +	$is_www = ( str_starts_with( $hostname, 'www.' ) );
```suggestion
	$is_www = str_starts_with( $hostname, 'www.' );
```

2023-04-25 13:55 UTC, spacedmonkey commented
> Thanks @spacedmonkey, Great start. left a few suggestions for removing extra round brackets.
> 
> `if ( strpos( haystack, needle ) === 0 ) {` why this type of check is not consider in this PR? I found many instance in core for same.
> 
> **List of files:**
> 
> ```
> /src/wp-admin/load-styles.php
> /src/wp-admin/includes/credits.php
> /src/wp-admin/includes/template.php
> /src/wp-includes/block-template.php
> /src/wp-includes/bookmark-template.php
> /src/wp-includes/class-wp.php
> /src/wp-includes/functions.php
> /src/wp-includes/l10n.php
> /src/wp-includes/pluggable.php
> /src/wp-includes/rest-api.php
> /src/wp-includes/rewrite.php
> /src/wp-includes/rest-api/class-wp-rest-server.php
> /src/wp-includes/widgets/class-wp-widget-block.php
> ```

Good patch. I did a regex search and found more!

2023-04-27 04:31 UTC, mukeshpanchal27 reviewed
Thanks @spacedmonkey, Thanks for the updates. Left final feedback.

I found some instances in files that are missing:
```
https://github.com/spacedmonkey/wordpress-develop/blob/str_starts_with/src/wp-includes/class-simplepie.php#L3227
https://github.com/spacedmonkey/wordpress-develop/blob/str_starts_with/src/wp-includes/functions.php#L7434
https://github.com/spacedmonkey/wordpress-develop/blob/str_starts_with/src/wp-includes/rest-api/class-wp-rest-server.php#L651
```

2023-04-27 04:31 UTC, mukeshpanchal27 commented on src/wp-includes/l10n.php
> +		} elseif ( ( str_starts_with( $src_url['path'], trailingslashit( $site_url['path'] ) ) ) ) {
```suggestion
		} elseif ( str_starts_with( $src_url['path'], trailingslashit( $site_url['path'] ) ) ) {
```

2023-04-27 11:24 UTC, spacedmonkey commented
> Thanks @spacedmonkey, Thanks for the updates. Left final feedback.
> 
> I found some instances in files that are missing:
> 
> ```
> https://github.com/spacedmonkey/wordpress-develop/blob/str_starts_with/src/wp-includes/class-simplepie.php#L3227
> https://github.com/spacedmonkey/wordpress-develop/blob/str_starts_with/src/wp-includes/functions.php#L7434
> https://github.com/spacedmonkey/wordpress-develop/blob/str_starts_with/src/wp-includes/rest-api/class-wp-rest-server.php#L651
> ```

Good catches. Simple pie was left by design, It is an external library. Fixed now.

2023-04-27 11:38 UTC, costdev requested changes
Thanks for the updates @spacedmonkey! Just one that needs to be inverted.

2023-04-27 11:38 UTC, costdev commented on src/wp-admin/includes/credits.php
> +		|| ( isset( $results['data']['version'] ) && str_starts_with( $version, $results['data']['version'] ) )
```suggestion
		|| ( isset( $results['data']['version'] ) && ! str_starts_with( $version, $results['data']['version'] ) )
```

2023-04-27 12:34 UTC, costdev approved these changes
Thanks for the update @spacedmonkey! LGTM :+1:

2023-04-28 04:47 UTC, mukeshpanchal27 approved these changes
Thanks @spacedmonkey, the changes look good to me.

2023-05-02 15:39 UTC, SergeyBiryukov approved these changes

2023-05-02 15:44 UTC, SergeyBiryukov commented
Thanks for the PR! Merged in [r55703](https://core.trac.wordpress.org/changeset/55703).

2023-05-02 15:44 UTC, closed without merging