Grammar improvement after signup.
WordPress/wordpress-develop pull request #4314
Opened 2023-04-11 15:52 UTC by NekoJonez

Like I said in the trac ticket, I think the sentence flows a bit better now. I also adjusted the translator comment for make it even more clear.

Trac ticket: (https://core.trac.wordpress.org/ticket/58115)

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2023-04-11 20:44 UTC, audrasjb requested changes
Thanks for the PR! I added one small change request ;)

2023-04-11 20:44 UTC, audrasjb commented on src/wp-signup.php
> +	/* translators: %s: The user Email address. */
I don't think "Email" should stay capitalized :)

2023-04-11 20:48 UTC, NekoJonez commented
@audrasjb Fixed! Thanks for that feedback :D

2023-04-11 20:51 UTC, NekoJonez commented
@audrasjb I looked further and I found the exact same thing lower in the file... So, I fixed that as well.

2023-04-11 21:32 UTC, audrasjb approved these changes
Nice 👌

2023-04-12 04:43 UTC, krupal-panchal approved these changes

2023-04-20 04:18 UTC, krupal-panchal approved these changes

2023-04-25 11:31 UTC, hz-tyfoon approved these changes

2023-06-09 15:07 UTC, audrasjb commented
Committed in https://core.trac.wordpress.org/changeset/55902

2023-06-09 15:07 UTC, closed without merging