Show user roles id 58103
WordPress/wordpress-develop pull request #4331
Opened 2023-04-14 15:31 UTC by madejtax

Trac ticket: 

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2023-04-20 14:35 UTC, lphoumpakka requested changes

2023-04-20 14:35 UTC, lphoumpakka commented on src/wp-admin/users.php
> +						$role_a = $a->roles[0];
Check empty role
Prefer use reset

2023-04-20 14:35 UTC, lphoumpakka commented on src/wp-admin/users.php
> +						echo '<option value="' . esc_attr( $user->ID ) . '"> User: ' . esc_html( $user->display_name ) . ' - rol: ' . esc_html( $user->roles[0] ) . '</option>';
Missing "e" to "role".
Needs translation for "User" and "role".
Add more check to empty role 
Prefers use reset for $user->roles

2023-04-25 11:43 UTC, hz-tyfoon commented
Looks like there are some `coding standards issues` in the file changes. Can u fix them?

2023-06-07 21:57 UTC, audrasjb commented
Closed in favor of #4441

2023-06-07 21:57 UTC, closed without merging