58094 8.1 CSV files
WordPress/wordpress-develop pull request #4370
Opened 2023-04-23 10:57 UTC by elenachavdarova

Include text/csv to the list of supported types in wp_check_filetype_and_ext().

Track ticket: https://core.trac.wordpress.org/ticket/58094

2023-05-07 12:11 UTC, costdev commented on src/wp-includes/functions.php
> +		} elseif ( ( 'application/csv' === $real_mime ) || ( 'text/csv' === $real_mime ) ) {
```suggestion
		} elseif ( 'application/csv' === $real_mime || 'text/csv' === $real_mime ) {
```
IMO, it looks a little cleaner to remove the additional parentheses here.

2023-05-07 12:13 UTC, costdev approved these changes
Thanks for the PR @elenachavdarova! I've just left one thought below regarding parentheses, but this is not a blocker for this PR. 🙂

2023-07-13 17:16 UTC, spacedmonkey approved these changes

2023-07-13 17:17 UTC, spacedmonkey requested changes
Unit test updated needed.

2023-07-17 18:28 UTC, SergeyBiryukov commented
Thanks for the PR! Closing this for now, as the related issue cannot be reproduced, see [comment 9 on #58094](https://core.trac.wordpress.org/ticket/58094#comment:9).

2023-07-17 18:28 UTC, closed without merging