Load compat in load-style.php
WordPress/wordpress-develop pull request #4418
Opened 2023-05-03 15:50 UTC by spacedmonkey

Trac ticket:  https://core.trac.wordpress.org/ticket/58012

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2023-05-03 15:59 UTC, SergeyBiryukov commented
Thanks! Yeah, that's what I was leaning towards in [58012.diff](https://core.trac.wordpress.org/attachment/ticket/58012/58012.diff)[​](https://core.trac.wordpress.org/raw-attachment/ticket/58012/58012.diff) as well 🙂 

The `str_starts_with()` call was replaced in [[55710]](https://core.trac.wordpress.org/changeset/55710), let's reinstate it in this PR too.

2023-05-03 17:25 UTC, SergeyBiryukov approved these changes

2023-05-03 17:27 UTC, azaozz commented
Sorry but including that file is "Doing it wrong". `load_scripts.php` and `load-styles.php` are (were?) designed to run outside of WordPress. They use `script-loader.php` as a **whitelist of URLs to scripts and styles**. None of the functions there are supposed to run.

2023-05-03 17:32 UTC, azaozz requested changes

2023-05-03 17:32 UTC, azaozz commented on src/wp-admin/load-styles.php
> +require ABSPATH . WPINC . '/compat.php';
Doesn't make sense to include a whole file just for this. `load-styles.php` is designed to run outside of WordPress.

2023-05-03 17:57 UTC, johnbillion requested changes
I agree with Andrew that this is an unnecessary change just to introduce what amounts to a coding standards change and has no functional benefit.

Loading the extra `compat.php` also presumably slows down the response time of these endpoints even further, albeit to a slight degree.

2023-05-04 10:12 UTC, spacedmonkey commented
Closing as it is fixed.

2023-05-04 10:12 UTC, closed without merging