I18N: Change wording of `roll back`
WordPress/wordpress-develop pull request #4436
Opened 2023-05-10 06:38 UTC by kebbet

Draft. See ticket.

2023-05-10 06:45 UTC, costdev requested changes
Thanks for the PR Kebbet. I've left some suggestions of language I think might work well im each context.

2023-05-10 06:45 UTC, costdev commented on src/wp-admin/includes/class-core-upgrader.php
> +		$this->strings['start_rollback']        = __( 'Attempting to restore back to previous version.' );
```suggestion
		$this->strings['start_rollback']        = __( 'Attempting to restore the previous version.' );
```

2023-05-10 06:45 UTC, costdev commented on src/wp-admin/includes/class-core-upgrader.php
> +		$this->strings['start_rollback']        = __( 'Attempting to restore back to previous version.' );
```suggestion
		$this->strings['start_rollback']        = __( 'Attempting to restore the previous version.' );
```

2023-05-10 06:45 UTC, costdev commented on src/wp-admin/includes/file.php
> +						__( 'Your PHP code changes were restored due to an error on line %1$s of file %2$s. Please fix and try saving again.' ),
```suggestion
						__( 'Your PHP code changes were not applied due to an error on line %1$s of file %2$s. Please fix and try saving again.' ),
```

2023-05-10 06:54 UTC, kebbet commented
Thanks for the review @costdev, much better with your suggestions! They are now applied.

2023-05-10 21:01 UTC, audrasjb approved these changes

2023-05-10 21:08 UTC, SergeyBiryukov commented
The suggested strings indeed look better to me. Thanks!

2023-05-10 21:08 UTC, SergeyBiryukov approved these changes

2023-05-11 14:49 UTC, audrasjb commented
committed in https://core.trac.wordpress.org/changeset/55750

2023-05-11 14:49 UTC, closed without merging