Check to see if class exists.
WordPress/wordpress-develop pull request #4454
Opened 2023-05-15 08:43 UTC by spacedmonkey

Trac ticket:  https://core.trac.wordpress.org/ticket/58185

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2023-05-16 02:04 UTC, peterwilsoncc requested changes

2023-05-16 02:04 UTC, peterwilsoncc commented on src/wp-includes/meta.php
> +			require ABSPATH . WPINC . '/class-wp-metadata-lazyloader.php';
```suggestion
			require_once ABSPATH . WPINC . '/class-wp-metadata-lazyloader.php';
```

2023-05-17 01:39 UTC, dd32 approved these changes

2023-05-17 09:44 UTC, spacedmonkey commented
Committed in https://core.trac.wordpress.org/changeset/55818 .

2023-05-17 09:44 UTC, closed without merging