Fixed grammatical mistake
WordPress/wordpress-develop pull request #4464
Opened 2023-05-17 04:12 UTC by mamun94

Fixed grammatical mistakes.

Trac ticket: https://core.trac.wordpress.org/ticket/58334

2023-05-17 04:14 UTC, costdev requested changes
Thanks for the PR @mamun94! I've left a couple of additional corrections in this review.

2023-05-17 04:14 UTC, costdev commented on src/wp-admin/includes/class-bulk-upgrader-skin.php
> +		// Nothing, This will be displayed within an iframe.
```suggestion
		// Nothing. This will be displayed within an iframe.
```

2023-05-17 04:14 UTC, costdev commented on src/wp-admin/includes/class-bulk-upgrader-skin.php
> +		// Nothing, This will be displayed within an iframe.
```suggestion
		// Nothing. This will be displayed within an iframe.
```

2023-05-17 04:21 UTC, mukeshpanchal27 approved these changes
@mamun94 Approved from my end, pending the changes from @costdev.

2023-05-17 06:55 UTC, afragen approved these changes

2023-05-17 06:57 UTC, afragen commented
Also, approve with @costdev's changes.

2023-05-17 18:51 UTC, costdev commented
Hi @mamun94! Are you available to update this pull request with the suggested changes above? 🙂

2023-05-18 03:41 UTC, mamun94 commented
Hi,
@costdev Changed the suggested issue updated. 🙂🙂

2023-05-18 06:23 UTC, mukeshpanchal27 approved these changes
The changes look good to me.

2023-05-18 10:18 UTC, costdev approved these changes
Thanks for the updates @mamun94! LGTM! :+1:

2023-05-18 11:39 UTC, SergeyBiryukov commented
Thanks for the PR! Merged in [r55823](https://core.trac.wordpress.org/changeset/55823).

2023-05-18 11:39 UTC, closed without merging