Add unit tests for ticket #58392
WordPress/wordpress-develop pull request #4580
Opened 2023-06-08 13:23 UTC by Hug0-Drelon

Trac ticket: https://core.trac.wordpress.org/ticket/58392

This PR adds unit tests to the previously proposed diff.

2023-06-08 16:26 UTC, audrasjb requested changes
Everything looks good to me, except that we need a few docblocks in the provided unit tests. 
You can take [wpPublishPost](https://github.com/WordPress/wordpress-develop/blob/trunk/tests/phpunit/tests/post/wpPublishPost.php) as an example.

2023-06-08 16:26 UTC, audrasjb commented on tests/phpunit/tests/post/wpTrashPost.php
> +
I think we need a docblock here:
```
/**
 * @group post
 * @covers ::wp_trash_post
 */
```
See https://github.com/WordPress/wordpress-develop/blob/trunk/tests/phpunit/tests/post/wpPublishPost.php

2023-06-08 16:26 UTC, audrasjb commented on tests/phpunit/tests/post/wpTrashPost.php
> +
And a mention of the related ticket for each test case. For example:
```
	/**
	 * @ticket 58392
	 * @covers ::wp_trash_post
	 */
```

See https://github.com/WordPress/wordpress-develop/blob/trunk/tests/phpunit/tests/post/wpPublishPost.php

2023-06-08 19:23 UTC, costdev commented on tests/phpunit/tests/post/wpTrashPost.php
> +	public function test_trash_post() {
Thanks for these tests @Hug0-Drelon!

These should ideally be separate test methods to test each filter/action independently. That way, if there's a failure with one of them, the others will still be tested. Same for the `wp_untrash_post()` tests.

2023-06-08 22:09 UTC, Hug0-Drelon commented
Hi @audrasjb and @costdev 👋 
Thanks for the feedback!
I've split the test and added some docblocks as you suggested.

2023-06-09 06:59 UTC, costdev requested changes
Thanks for the updates @Hug0-Drelon! I've left some more thoughts in this review 🙂

2023-06-09 06:59 UTC, costdev commented on tests/phpunit/tests/post/wpTrashPost.php
> +	 * @covers ::wp_trash_post
```suggestion
	 * Tests that wp_trash_post() returns a WP_Post object
	 * and sets the correct post meta to trash a post.
	 *
	 * @ticket 58392
	 *
	 * @covers ::wp_trash_post
```
- Let's add descriptions to each of the tests, starting with "Tests that" per convention.
- I also spaced out the `@ticket` and `@covers` annotations based on [the structure/grouping of annotations in this ticket](https://core.trac.wordpress.org/ticket/56070).

2023-06-09 06:59 UTC, costdev commented on tests/phpunit/tests/post/wpTrashPost.php
> +	 * @covers ::wp_trash_post
```suggestion
	 * Tests that wp_trash_post() applies 'pre_trash_post' filters
	 * and passes the expected values to callbacks.
	 *
	 * @ticket 58392
	 *
	 * @covers ::wp_trash_post
```

2023-06-09 06:59 UTC, costdev commented on tests/phpunit/tests/post/wpTrashPost.php
> +	 * @covers ::wp_trash_post
```suggestion
	 * Tests that wp_trash_post() triggers the 'wp_trash_post' action
	 * and passes the expected values to callbacks.
	 *
	 * @ticket 58392
	 *
	 * @covers ::wp_trash_post
```

2023-06-09 06:59 UTC, costdev commented on tests/phpunit/tests/post/wpTrashPost.php
> +	 * @covers ::wp_trash_post
```suggestion
	 * Tests that wp_trash_post() triggers the 'trashed_post' action
	 * and passes the expected values to callbacks.
	 *
	 * @ticket 58392
	 *
	 * @covers ::wp_trash_post
```

2023-06-09 06:59 UTC, costdev commented on tests/phpunit/tests/post/wpUntrashPost.php
> +	 * @covers ::wp_untrash_post
```suggestion
	 * Tests that wp_untrash_post() returns a WP_Post object,
	 * removes post meta for an untrashed post and sets it to a 'Draft'.
	 *
	 * @ticket 58392
	 *
	 * @covers ::wp_untrash_post
```

2023-06-09 06:59 UTC, costdev commented on tests/phpunit/tests/post/wpUntrashPost.php
> +	 * @covers ::wp_untrash_post
```suggestion
	 * Tests that wp_untrash_post() applies 'pre_untrash_post' filters
	 * and passes the expected values to callbacks.
	 *
	 * @ticket 58392
	 *
	 * @covers ::wp_untrash_post
```

2023-06-09 06:59 UTC, costdev commented on tests/phpunit/tests/post/wpUntrashPost.php
> +	 * @covers ::wp_untrash_post
```suggestion
	 * Tests that wp_untrash_post() triggers the 'untrash_post' action
	 * and passes the expected values to callbacks.
	 *
	 * @ticket 58392
	 *
	 * @covers ::wp_untrash_post
```

2023-06-09 06:59 UTC, costdev commented on tests/phpunit/tests/post/wpUntrashPost.php
> +	 * @covers ::wp_untrash_post
```suggestion
	 * Tests that wp_untrash_post() triggers the 'untrashed_post' action
	 * and passes the expected values to callbacks.
	 *
	 * @ticket 58392
	 *
	 * @covers ::wp_untrash_post
```

2023-06-09 06:59 UTC, costdev commented on tests/phpunit/tests/post/wpTrashPost.php
> + * @covers ::wp_trash_post
```suggestion
 * @group post
 *
 * @covers ::wp_trash_post
```

2023-06-09 06:59 UTC, costdev commented on tests/phpunit/tests/post/wpTrashPost.php
> +class Tests_Post_wpTrashPost extends WP_UnitTestCase {
```suggestion
class Tests_Post_WpTrashPost extends WP_UnitTestCase {
```
`wp` should be `Wp` here. [See the handbook entry on Test Classes](https://make.wordpress.org/core/handbook/testing/automated-testing/writing-phpunit-tests/#test-classes) and [this ticket about 'wp' vs 'Wp' for test class names](https://core.trac.wordpress.org/ticket/56846).

2023-06-09 06:59 UTC, costdev commented on tests/phpunit/tests/post/wpUntrashPost.php
> + * @covers ::wp_untrash_post
```suggestion
 * @group post
 *
 * @covers ::wp_untrash_post
```

2023-06-09 06:59 UTC, costdev commented on tests/phpunit/tests/post/wpUntrashPost.php
> +class Tests_Post_wpUntrashPost extends WP_UnitTestCase {
```suggestion
class Tests_Post_WpUntrashPost extends WP_UnitTestCase {
```

2023-06-11 13:37 UTC, Hug0-Drelon commented
Thanks for the insight @costdev! Nice to see how standardization is going 🙂

2023-06-11 13:53 UTC, costdev approved these changes
Thanks for the updates @Hug0-Drelon! I think that's all from me on this one!

2023-06-23 20:38 UTC, audrasjb approved these changes
Thanks for the update!

2023-06-26 20:56 UTC, audrasjb commented
committed in https://core.trac.wordpress.org/changeset/56043

2023-06-26 20:56 UTC, closed without merging