Deprecated notice fired by wp_set_object_terms() with PHP 8.1
WordPress/wordpress-develop pull request #4603
Opened 2023-06-13 03:48 UTC by peterwilsoncc

Prevents the throwing of a notice in `wp_set_object_terms()`.

`src` changes props @SergeyBiryukov 

Trac ticket: https://core.trac.wordpress.org/ticket/57923

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2023-06-13 05:15 UTC, costdev requested changes
Thanks for the PR @peterwilsoncc!

I've added some feedback in this review.

2023-06-13 05:15 UTC, costdev commented on tests/phpunit/tests/term/wpSetObjectTerms.php
> +	 * Empty values should clear an object of all terms.
```suggestion
	 * Tests that empty values clear an object of all terms.
```

2023-06-13 05:15 UTC, costdev commented on tests/phpunit/tests/term/wpSetObjectTerms.php
> +	 * @param mixed $empty_value An empty.
```suggestion
	 * @param mixed $empty_value An empty value.
```

2023-06-13 05:15 UTC, costdev commented on tests/phpunit/tests/term/wpSetObjectTerms.php
> +		$this->assertNotEmpty( $terms );
These assertions should have a `$message` parameter.

2023-06-13 05:15 UTC, costdev commented on tests/phpunit/tests/term/wpSetObjectTerms.php
> +	 * Data provider for test_empty_value_should_clear_terms().
```suggestion
	 * Data provider.
```

We're currently using this for data provider docblocks until consensus is reached on a consistent format.

```php
/**
 * Data provider.
 *
 * @return array[]
 */
```

2023-06-14 00:13 UTC, peterwilsoncc commented on tests/phpunit/tests/term/wpSetObjectTerms.php
> +		$this->assertNotEmpty( $terms );
```suggestion
		$this->assertNotEmpty( $terms, 'Terms should initially be applied to post object.' );
```

2023-06-14 00:14 UTC, peterwilsoncc commented on tests/phpunit/tests/term/wpSetObjectTerms.php
> +		$this->assertEmpty( $terms );
```suggestion
		$this->assertEmpty( $terms, 'An empty() value should clear terms from the post object.' );
```

2023-06-14 00:15 UTC, peterwilsoncc commented
Thanks @costdev , I've applied each of your suggestions.

2023-06-14 22:38 UTC, costdev approved these changes
Thanks for the updates @peterwilsoncc!

2023-06-14 23:51 UTC, closed without merging

2023-06-14 23:52 UTC, peterwilsoncc commented
Merged in [r55921](https://core.trac.wordpress.org/changeset/55921) / https://github.com/WordPress/wordpress-develop/commit/6178829ab0594d3a541c406502ba31e05ddd82f3