Move logic to improve performance.
WordPress/wordpress-develop pull request #4766
Opened 2023-06-30 10:06 UTC by spacedmonkey

Trac ticket: https://core.trac.wordpress.org/ticket/58235

Follow on from https://core.trac.wordpress.org/changeset/56037. 

Move the check to see if properties exist before doing anymore processing. 

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2023-06-30 11:58 UTC, swissspidy commented on src/wp-includes/media.php
> +	// Images should have source and dimension attributes for the loading optimization attributes to be added.
The regexes below do check for single quotes and double quotes. Why don't these checks do that? Seems like an oversight.

(And yes I know this is just moved from elsewhere, but now is a great opportunity to discuss this and fix/document it)

2023-06-30 16:32 UTC, felixarntz requested changes
@spacedmonkey Thanks for opening this PR for consideration. Looking at the change, the main change you made here is not something we can do, please review the code comment that explains why.

The only other change here is moving the `preg_match_all()` call in `wp_filter_content_tags()`, which makes sense to me. However, that change is unrelated to #58235, so I think that should be a separate ticket.

2023-06-30 16:32 UTC, felixarntz commented on src/wp-includes/media.php
> +	}
This change must not be made. Please see the comment starting in line 1939/1944.

2023-06-30 16:32 UTC, felixarntz commented on src/wp-includes/media.php
> +	}
Same here, this must not be moved here.

2023-06-30 23:43 UTC, closed without merging

2023-07-03 14:07 UTC, spacedmonkey commented
@felixarntz Good catch. Sorry I missed that comment how. Closing this PR.