Toolbar: Make the 'Edit site' link aware of the current template
WordPress/wordpress-develop pull request #4810
Opened 2023-07-07 07:21 UTC by Mamaduka

PR makes the 'Edit site' link in the toolbar contextually aware of the current template.

## How

Introduces a new global `$_wp_current_template_id` that stores the current template ID during the template resolution.

We can't use the existing `$_wp_current_template_content` global as it only stores template contents.

## Refs

Gutenberg issue: https://github.com/WordPress/gutenberg/issues/37850
Trac ticket: https://core.trac.wordpress.org/ticket/58746

2023-07-07 10:11 UTC, audrasjb requested changes
Looks good to me. However, we also need two docblock updates :)

2023-07-07 10:11 UTC, audrasjb commented on src/wp-includes/admin-bar.php
> +	global $_wp_current_template_id;
We need to document this global with a `@global` mention in the docblock above ;)

2023-07-07 10:11 UTC, audrasjb commented on src/wp-includes/block-template.php
> +	global $_wp_current_template_content, $_wp_current_template_id;
needs a docblock, too :)

2023-07-07 10:55 UTC, Mamaduka commented
Thank you, @audrasjb! I added DocBlocks in [447fba8](https://github.com/WordPress/wordpress-develop/pull/4810/commits/447fba8b04ea6809758fb0be3c0c673b9eb6d653).

2023-07-07 12:18 UTC, mukeshpanchal27 reviewed
Thanks @Mamaduka for the PR, `$` missing in global.

2023-07-07 12:18 UTC, mukeshpanchal27 commented on src/wp-includes/admin-bar.php
> + * @global string _wp_current_template_id
```suggestion
 * @global string $_wp_current_template_id
```

2023-07-07 12:18 UTC, mukeshpanchal27 commented on src/wp-includes/block-template.php
> + * @global string _wp_current_template_id
```suggestion
 * @global string $_wp_current_template_id
```

2023-07-11 06:04 UTC, audrasjb approved these changes
👍

2023-07-11 18:51 UTC, closed without merging