Update bundled theme changelog and asset version
WordPress/wordpress-develop pull request #4863
Opened 2023-07-18 07:26 UTC by kafleg

Update version, tested upto, changelog and CSS version

Trac ticket: https://core.trac.wordpress.org/ticket/57857

2023-07-18 10:35 UTC, sabernhardt requested changes
Twenty Nineteen, Twenty Twenty and Twenty Twenty-One also need updates to their `package.json` and `package-lock.json` files. I already had started working on a pull request, and it might be easier to finish that than editing this one.

2023-07-18 10:35 UTC, sabernhardt commented on src/wp-content/themes/twentyeleven/functions.php
> +	wp_enqueue_style( 'twentyeleven-block-style', get_template_directory_uri() . '/blocks.css', array(), '20230808' );
Most assets do not need a newer version number. Twenty Eleven only needs to update `style.css` in the header template.

2023-07-18 10:35 UTC, sabernhardt commented on src/wp-content/themes/twentyeleven/readme.txt
> +* Released: August 08, 2023
To follow the pattern with March 9 and November 1, dates do not need the zero.

2023-07-21 05:23 UTC, kafleg commented on src/wp-content/themes/twentyeleven/readme.txt
> +* Released: August 08, 2023
@sabernhardt do you want me to fix that and commit again?

2023-07-21 13:12 UTC, sabernhardt commented on src/wp-content/themes/twentyeleven/readme.txt
> +* Released: August 08, 2023
I opened a separate pull request, [4865](https://github.com/WordPress/wordpress-develop/pull/4865), trying to prepare it for RC1. That PR still had some further changes, too.

2023-07-27 06:43 UTC, carolinan commented
I believe this PR should be closed.

2023-07-27 09:24 UTC, audrasjb commented
Closing in favor of #4865

2023-07-27 09:24 UTC, closed without merging