Code Modernization: Replace some ternaries with null coalescing operator.
WordPress/wordpress-develop pull request #4886
Opened 2023-07-22 05:03 UTC by costdev

This PR contains commits separated by component for easier reviewing/possible commit.

Changes can be reviewed altogether or per PR commit.
If moved forward for merging to WordPress Core, this PR's commits can be merged individually, grouped into smaller chunks, or squashed into a single commit.

Trac ticket:

2023-09-21 06:02 UTC, mukeshpanchal27 requested changes
Thanks @costdev for the PR. Could you please rebased?

2023-09-21 08:07 UTC, costdev commented
@mukeshpanchal27 This PR is on hold until a Make post has been made to establish what PHP 7 syntaxes will be supported/allowed in Core.

2025-12-23 05:56 UTC, westonruter commented
Refresh: https://github.com/WordPress/wordpress-develop/pull/10654

2026-01-05 06:04 UTC, westonruter commented
Via the refresh in https://github.com/WordPress/wordpress-develop/pull/10654 I've committed the updates for:

0. Tests: https://github.com/WordPress/wordpress-develop/commit/745a5370d41c2366fc15a77292add90dcd3d5028
1. REST API: https://github.com/WordPress/wordpress-develop/commit/ddb3799f8981de193a59ff4142aa36c87f242e78
2. Editor: https://github.com/WordPress/wordpress-develop/commit/60c63c226f84b042d88f4e942c32a10fbb30b15c and https://github.com/WordPress/wordpress-develop/commit/5ed1e083f0d3e5207bf467e20845129a20fb3c31
3. Widgets: https://github.com/WordPress/wordpress-develop/commit/133fdbbdd2bf77bb58bdf61dc322777bc3b35aa4
4. Customize: https://github.com/WordPress/wordpress-develop/commit/a00cc83d9bf02eacbe366c9a1be781829b97c325
5. Comments: https://github.com/WordPress/wordpress-develop/commit/e142030357cafcbb251e507cf6b1043a94dbd71b
6. HTTP: https://github.com/WordPress/wordpress-develop/commit/25caa5d6a1e34c2054e7bb30b543ace05c61fef1
7. Formatting: https://github.com/WordPress/wordpress-develop/commit/6d60f73c834691312ee958664e26bc474e06b71f

2026-01-06 06:10 UTC, westonruter commented
To continue, bia the refresh in https://github.com/WordPress/wordpress-develop/pull/10654 I've committed the updates for:

8. Script Loader: 667cffae725abce2c6c5bf9a85fa40a91a7e40c1
9. Bootstrap/Load: f7bd33addcc31c568b51dbb4c04a37875f917d91
10. Code Modernization: Site Health, Permalinks, I18N, Users, Multisite: 14b647c6b1a2e0782ddab4fda41d8ef774ed640f
11. Taxonomy, Posts/Post Types, Options/Meta APIs, Query, General: fb52a4063cfddd8268851a92648b6fed0c7c1ad4 

There are now 47 files left.

2026-01-09 04:27 UTC, closed without merging