Add title attribute to oEmbed/REST alternate <link> tags / 'Link:' header
WordPress/wordpress-develop pull request #5080
Opened 2023-08-24 20:09 UTC by addisonhardy

This PR makes three changes:
- Adds the `title` attribute to `<link rel="alternate">` tags for oEmbed and REST API endpoints
- Updates the oEmbed phpunit tests to reflect the above change
- Adds the `title` link-param to REST API `Link:` headers (verified as supported in RFC 8288 here: https://httpwg.org/specs/rfc8288.html#serialisation-defined-attributes)

Note: The Trac ticket referenced below does not include a consensus discussion around this change.  Opening the PR as a proof of concept as part of familiarizing w/ the WP development process as a new contributor at WordCamp US 2023.

Trac ticket: https://core.trac.wordpress.org/ticket/59006

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2023-08-31 20:09 UTC, kadamwhite requested changes
I cannot find a clear example of a site with headers like this in an RTL or character-based language, and I understand your argument that "oEmbed" and "JSON" are standards with ASCII-based names, so it may be a non-issue — but I'd prefer to get an opinion from somebody with more experience in other languages before we decide not to make these strings translatable.

cc @rmccue @TimothyBJacobs for second opinion.

2023-08-31 22:19 UTC, TimothyBJacobs commented
Maybe @SergeyBiryukov has some thoughts on localization. My inclination would be that we should still translate it.

2023-09-29 15:58 UTC, joedolson commented
I'm inclined to think these should be translated, although it does feel a little strange. At least in the case of oEmbed (XML), I think that the structure and order of the text could be variable by language, which is enough to justify it, to me.

2024-01-14 17:17 UTC, audrasjb requested changes
Yes these strings should be translatable: even if it's a edge case, as soon as the title is rendered in the user agent, any language change without information about the language of the string would be a compliance issue.

2024-10-08 01:30 UTC, addisonhardy commented
Closing as no longer needed due to #6703

2024-10-08 01:30 UTC, closed without merging