Try/lazy load
WordPress/wordpress-develop pull request #5098
Opened 2023-08-26 15:12 UTC by spacedmonkey

Trac ticket: 

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2025-01-15 18:26 UTC, felixarntz requested changes
@spacedmonkey I think there is at least one bug with the code that needs to be addressed (related to switching to another site in Multisite).

Other than that, I think it would be great if you could separate the overall metadata lazyloader integration and handle that in another PR. The role and capability logic itself is expensive enough to be lazy-loaded, which is what most of this PR is about. That in itself is already complex and may have some quirks to consider, so I think separating the two concerns makes the PRs easier to review.

As an aside, I'm not very familiar with metadata lazy-loading, but I am familiar with how `WP_User` works, so I only feel comfortable with reviewing the latter.

2025-01-15 18:26 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
> +	protected $caps = array();
Why is this changed to `protected`? Wouldn't it be better to make it `private` instead?

2025-01-15 18:26 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
> +	protected $roles = array();
Same here.

2025-01-15 18:26 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
> +	protected $allcaps = array();
Same here.

2025-01-15 18:26 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
> +		$this->load_capablity_data();
This feedback is not directly related to this line, but it looks like you're not loading the capability data in the `remove_all_caps()` method below. This could lead to unexpected consequences I think. It would be safer to add it there too.

2025-01-15 18:26 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
> -		$this->get_role_caps();
I think removing this without replacing it with some other mechanism to "reset" the flag that capability and role data are loaded will lead to problems. For example, if capabilities and roles were already loaded and then someone calls `WP_User::for_site()` with another site ID, the `WP_User` object would still have the old capabilities and roles, not the ones for the site requested.

2025-01-15 18:26 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
> +		wp_lazyload_user_meta( array( $this->ID ) );
I'm not very familiar with how metadata lazy-loading works, so I feel like I'm not the right person to review this part. For example, one potential caveat here is that user metadata is generally global, but some meta keys only apply to specific sites.

I wonder for instance why this method is called here. Since user metadata is global, why would it need to be loaded (again) when the site is switched? Shouldn't this call be somewhere else, or only be called if it hadn't been called before?

2025-01-16 04:26 UTC, peterwilsoncc commented on src/wp-includes/class-wp-user.php
> -		$this->get_role_caps();
Indeed, this appears to be the cause of the test failures for MS.

2025-01-30 22:52 UTC, spacedmonkey commented on src/wp-includes/class-wp-user.php
> +	protected $caps = array();
I don't think we can make this private. If someone is extending the WP_User class, then this property will then become unaccessible. There is no need for it to be private, protected will work here.

2025-01-30 23:38 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
> +	protected $caps = array();
Fair point. 👍

2025-01-31 13:47 UTC, spacedmonkey commented on src/wp-includes/class-wp-user.php
> +		$this->load_capablity_data();
Fixed.

2025-01-31 13:47 UTC, spacedmonkey commented on src/wp-includes/class-wp-user.php
> -		$this->get_role_caps();
Fixed.

2025-01-31 19:06 UTC, spacedmonkey commented on src/wp-includes/user.php
> + * @since 6.4.0
```suggestion
 * @since 6.8.0
```

2025-02-04 17:00 UTC, felixarntz reviewed
@spacedmonkey The `WP_User` changes look almost good to commit, just a few points of minor feedback.

As mentioned, I would like for someone else that is more experienced with `WP_Metadata_Lazyloader` to review that portion of the PR.

2025-02-04 17:00 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
> +	 * Load capability data.
```suggestion
	 * Loads capability data if it has not been loaded yet.
```

2025-02-04 17:00 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
>  		$this->get_role_caps();
This implementation looks a bit inconsistent with that from the other methods, and it is doing manually what `load_capability_data()` does. So I think it makes sense to use it:

```suggestion
		delete_user_meta( $this->ID, $this->cap_key );
		delete_user_meta( $this->ID, $wpdb->get_blog_prefix() . 'user_level' );
		$this->loaded_caps = false;
		$this->load_capability_data();
```

By calling `load_capability_data()` here, `$this->caps` will be automatically set to the empty array (if deleting the user metadata succeeded), and then `$this->get_role_caps()` will be called.

2025-02-04 17:00 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
> +
This is unnecessary I think. The `WP_User` class has always populated `$this->caps` before, and not doing so anymore would be a breaking change. So we don't need this here, since `$this->caps` will always be correct prior to calling this method.
```suggestion
```

2025-02-26 01:53 UTC, peterwilsoncc reviewed
I've added a couple of notes and a question inline.

The change to cache_users, does make the change so user meta data is always lazy loaded and there doesn't appear to be a way for developers to trigger the active loading of user meta. 

Based on manual testing it appears pretty good.

2025-02-26 01:53 UTC, peterwilsoncc commented on src/wp-includes/class-wp-user.php
For IDEs, the now protected properties will need to be added to the list of properties available in the class level docblock. https://github.com/WordPress/wordpress-develop/blob/64cefd6a3d6f5f3e1ea859915b1f1d07f0519ef9/src/wp-includes/class-wp-user.php#L10-L38

2025-02-26 01:53 UTC, peterwilsoncc commented on src/wp-includes/class-wp-user.php
> +	private function load_capablity_data() {
```suggestion
	private function load_capability_data() {
```

2025-02-26 01:53 UTC, peterwilsoncc commented on tests/phpunit/tests/user/query.php
> +		$this->reset_lazyload_queue();
Do you know why this is needed, shouldn't the queue be clear?

2025-02-27 15:47 UTC, spacedmonkey commented on src/wp-includes/class-wp-user.php
Fixed

2025-02-27 15:49 UTC, spacedmonkey commented on src/wp-includes/class-wp-user.php
> +
The lines below checks if caps is an array. 

```
if ( is_array( $this->caps ) ) 
```

I wanted to ensure `$this->caps` was set correctly before doing this check.

2025-02-27 15:50 UTC, spacedmonkey commented on src/wp-includes/class-wp-user.php
> +		wp_lazyload_user_meta( array( $this->ID ) );
This is the key to not loading user meta on every request and is required.

2025-02-27 18:18 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
> +		wp_lazyload_user_meta( array( $this->ID ) );
I understand that this is useful, but I don't think it's required for this PR. This line fits perfectly into the scope of https://core.trac.wordpress.org/ticket/63021, but less into lazy-loading the role/cap properties of `WP_User`.

On another note, if we keep it, could you review my previous question please?
> Since user metadata is global, why would it need to be loaded (again) when the site is switched? Shouldn't this call be somewhere else, or only be called if it hadn't been called before?

2025-02-27 18:22 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
> +
My point is that that's unnecessary to check, because it'll always be set correctly based on `$this->caps = $this->get_caps_data()`, which is called before this `get_role_caps()` method everywhere.

2025-02-27 18:27 UTC, felixarntz reviewed
@spacedmonkey @peterwilsoncc I am realizing just now that the change of making the `$caps`, `$roles`, and `$allcaps` properties protected may be considered a breaking change, albeit only relevant for edge cases.

They're still readable via magic getter and isset-er, but in theory a plugin doing some very niche capability modification stuff may be _writing_ these properties too. With the current state of this PR, that wouldn't work anymore.

I'm not overly concerned about this, since doing so would be a bad practice, but I still wanted to flag it. I think we have two options here:
* Either accept this as a edge-case BC break we're willing to make, punt this to 6.9 to land `early` in the milestone, and cover it in a dev note.
* Or add conditions for these to the `__set()` method to maintain backward compatibility (which is definitely more forgiving, but may continue encouraging this problematic pattern).

WDYT?

2025-02-28 03:59 UTC, spacedmonkey reviewed
@peterwilsoncc @felixarntz @joemcgill As requested, I have removed all the lazy loading user meta stuff. This makes this patch much much smaller and easily to review. 

I have added some tests to valid that `get_role_caps` continues to work. Other existing tests cover add_cap, remove_cap, remove_all_caps, has_cap and set_role still work.

2025-02-28 03:59 UTC, spacedmonkey commented on src/wp-includes/class-wp-user.php
> +
The method `get_role_caps` is public. What you create a WP_User instance and the call `get_role_caps`?  It feels safer to just make sure that caps are loaded here. What does it hurt to have this here?

2025-02-28 04:02 UTC, spacedmonkey commented
> I am realizing just now that the change of making the `$caps`, `$roles`, and `$allcaps` properties protected may be considered a breaking change, albeit only relevant for edge cases.
> 
> They're still readable via magic getter and isset-er, but in theory a plugin doing some very niche capability modification stuff may be _writing_ these properties too. With the current state of this PR, that wouldn't work anymore.
> 
> I'm not overly concerned about this, since doing so would be a bad practice, but I still wanted to flag it. I think we have two options here:
> 
> * Either accept this as a edge-case BC break we're willing to make, punt this to 6.9 to land `early` in the milestone, and cover it in a dev note.
> * Or add conditions for these to the `__set()` method to maintain backward compatibility (which is definitely more forgiving, but may continue encouraging this problematic pattern).
> 
> WDYT?

If you are change the properties manaully, I feel like that are a pretty dangerous way of changing a user role. There are other filters and ways of doing this that are less problematic. I do believe this needs a detail dev note, but I feel like we should not enable this edge.

2025-02-28 17:08 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
> +
Hmm, that's a fair point. Could you add an inline comment to clarify this? For example:
```suggestion
		// Edge-case: In case someone calls this method before lazy initialization, we need to initialize on demand.
		if ( ! $this->loaded_caps ) {
			$this->caps = $this->get_caps_data();
		}

```

2025-02-28 17:10 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
> +
In addition, ideally this method would also set `$this->loaded_caps = true` in that situation: If someone calls `get_role_caps()` before initialization, the data is all set up the same way as `load_capability_data()` does it. So there would be no point of lazy-loading that data again afterwards.

2025-02-28 17:11 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
> +		wp_lazyload_user_meta( array( $this->ID ) );
@spacedmonkey Can you please get back to me on this open question?

2025-04-28 19:51 UTC, felixarntz reviewed
@spacedmonkey This looks almost good to go.

Just a few minor points here, and could you please get back to my feedback in https://github.com/WordPress/wordpress-develop/pull/5098#discussion_r1941557785? Still waiting for a reply to that.

2025-04-28 19:51 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
> + * @property array $allcaps
Let's go with the more specific type notation, as it's already used in other places in this class. Also noting that the `bool[]` annotation below is actually incorrect, so we should fix that.
```suggestion
 * @property array<string, bool> $caps
 * @property string[] $roles
 * @property array<string, bool> $allcaps
```

2025-04-28 19:51 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
>  	 *             and boolean values represent whether the user has that capability.
See above. Not a problem in this PR, but since we're touching it, it would be good to fix this incorrect type annotation.
```suggestion
	 * @var array<string, bool> Array of key/value pairs where keys represent a capability name
	 *                          and boolean values represent whether the user has that capability.
```

2025-04-28 19:51 UTC, felixarntz commented on src/wp-includes/class-wp-user.php
>  	 *             and boolean values represent whether the user has that capability.
See above:
```suggestion
	 * @var array<string, bool> Array of key/value pairs where keys represent a capability name
	 *                          and boolean values represent whether the user has that capability.
```

2025-05-20 15:39 UTC, swissspidy commented
@spacedmonkey FYI there are some merge conflicts plus some open feedback above from Felix (whom I accidentally requested another review from, sorry!)

2025-09-24 20:50 UTC, spacedmonkey commented on src/wp-includes/class-wp-user.php
> +	 * @since 6.8.0
```suggestion
	 * @since 6.9.0
```

2025-09-24 20:51 UTC, spacedmonkey commented on src/wp-includes/class-wp-user.php
> +	 * @since 6.8.0
```suggestion
	 * @since 6.9.0
```

2025-09-25 06:58 UTC, mukeshpanchal27 reviewed
Quick minor feedbacks

2025-09-25 06:58 UTC, mukeshpanchal27 commented on tests/phpunit/tests/user/multisite.php
> +        $this->assertContains( 'subscriber', $user->roles, 'User should have subscriber role' );
```suggestion
		$user = get_user_by( 'id', $user_id );
		$this->assertContains( 'subscriber', $user->roles, 'User should have subscriber role' );
```

2025-09-25 06:58 UTC, mukeshpanchal27 commented on tests/phpunit/tests/user/multisite.php
> +        $this->assertContains( 'subscriber', $user->roles, 'User should still have subscriber role' );
```suggestion
		$this->assertContains( 'subscriber', $user->roles, 'User should still have subscriber role' );
```

2025-09-25 06:58 UTC, mukeshpanchal27 commented on src/wp-includes/class-wp-user.php
> +	/**
```suggestion
	/**
```

2025-09-25 16:36 UTC, felixarntz approved these changes
@spacedmonkey LGTM, other than the coding standards issues to resolve :)

2025-09-26 01:07 UTC, westonruter commented on tests/phpunit/tests/user/query.php
> +			$user->roles;
I understand this is just to initiate loading the role data, but it looks like an error:

<img width="474" height="154" alt="Image" src="https://github.com/user-attachments/assets/884ac531-e15e-4542-88af-cff2eadf3b24" />

So I suggest adding an assertion to at least look at the value:

```suggestion
			$this->assertIsArray( $user->roles );
			foreach ( $user->roles as $role ) {
				$this->assertIsString( $role );
			}
```

2025-09-26 01:19 UTC, westonruter commented on src/wp-includes/class-wp-user.php
> +		// Edge-case: In case someone calls this method before lazy initialization, we need to initialize on demand.
Nit, this is two words:

```suggestion
		// Edge case: In case someone calls this method before lazy initialization, we need to initialize on demand.
```

2025-09-26 01:21 UTC, westonruter commented
> Trac ticket: https://core.trac.wordpress.org/ticket/58001

Shouldn't this rather reference https://core.trac.wordpress.org/ticket/63021 ?

**Update:** No! 😅

2025-09-29 20:57 UTC, spacedmonkey commented
@westonruter @mukeshpanchal27 Feedback actioned, can you take a look.

2025-09-29 22:48 UTC, westonruter commented on src/wp-includes/class-wp-user.php
> +			return isset( $this->$key );
Shouldn't it always return `true` here since they will always be populated magically?

```suggestion
			return true;
```

2025-09-29 22:48 UTC, westonruter commented on src/wp-includes/class-wp-user.php
> +		}
Per above:

```suggestion
		if ( ! isset( $this->caps ) ) {
			$this->caps = $this->get_caps_data();
		}
```

2025-09-29 22:48 UTC, westonruter commented on src/wp-includes/class-wp-user.php
> +		$this->loaded_caps = false;
Per above.

```suggestion
		$this->caps        = null;
```

2025-09-29 22:48 UTC, westonruter commented on src/wp-includes/class-wp-user.php
> +		$this->loaded_caps = true;
Per above.

```suggestion
		$this->caps = $this->get_caps_data();
		$this->get_role_caps();
```

2025-09-29 22:48 UTC, westonruter commented on src/wp-includes/class-wp-user.php
> +		if ( $this->loaded_caps ) {
Per above.

```suggestion
		if ( isset( $this->caps ) ) {
```

2025-09-29 22:48 UTC, westonruter commented on src/wp-includes/class-wp-user.php
> +
Minor point: Instead of introducing a new `$loaded_caps` member variable, the `$caps` member could be typed as `array<string, bool>|null` instead of `array<string, bool>`. It could be default `null` whenever wanting to check if whether the caps have been loaded, you can just check if `isset( $this->caps )`. This would eliminate having to look at two different member variables.

```suggestion
```

2025-09-29 22:48 UTC, westonruter commented on src/wp-includes/class-wp-user.php
> +	protected $caps = array();
```suggestion
	 * @var array<string, bool>|null Array of key/value pairs where keys represent a capability name
	 *                               and boolean values represent whether the user has that capability.
	 * 
	 *                               Null if the caps have not been loaded yet.
	 */
	protected $caps = null;
```

2025-09-29 22:48 UTC, westonruter commented on src/wp-includes/class-wp-user.php
> +		$this->loaded_caps = false;
Per above.

```suggestion
		$this->caps = null;
```

2025-10-02 22:18 UTC, westonruter commented on src/wp-includes/class-wp-user.php
> +	 *                          and boolean values represent whether the user has that capability.
```suggestion
	 *                               and boolean values represent whether the user has that capability.
```

2025-10-02 22:24 UTC, westonruter commented on src/wp-includes/class-wp-user.php
> +		}
Why wouldn't this also just do?

```suggestion
	$this->load_capability_data();
```

2025-10-02 22:39 UTC, spacedmonkey reviewed
@felixarntz @westonruter I feedback. I also fixed some edge case unsetting properties and setting properties. The current PR has new tests and is pretty clear, IMO.

2025-10-02 22:39 UTC, spacedmonkey commented on src/wp-includes/class-wp-user.php
> +		}
This was originally considers. But `load_capability_data` calls `get_role_caps`, which calls `load_capability_data`. This will loop forever.

2025-10-02 22:40 UTC, spacedmonkey commented on src/wp-includes/class-wp-user.php
> + * @property array<string, bool> $caps
```suggestion
 * @property array<string, bool>|null $caps
```

2025-10-02 22:41 UTC, spacedmonkey commented on src/wp-includes/class-wp-user.php
> + * @property array<string, bool>|null $caps
```suggestion
 * @property array<string, bool> $caps
```

2025-10-03 00:06 UTC, westonruter commented on src/wp-includes/class-wp-user.php
> +		}
Ah, OK 😄 ♾️

2025-10-03 00:09 UTC, westonruter approved these changes

2025-10-03 03:48 UTC, mukeshpanchal27 commented on tests/phpunit/tests/user/capabilities.php
> +	 * @dataProvider data_add_user_properties_manually
```suggestion
	 * @ticket 58001
	 *
	 * @dataProvider data_add_user_properties_manually
	 *
	 * @param string $property_name  The property name to set.
	 * @param array  $property_value The property value to set.
	 * @param bool   $check_null     Whether to check that the property is null after unsetting it.
```

2025-10-03 03:49 UTC, mukeshpanchal27 approved these changes

2025-10-08 20:00 UTC, closed without merging