Login: adjust markup for errors and messages
WordPress/wordpress-develop pull request #5178
Opened 2023-09-08 21:10 UTC by sabernhardt

- Uses an unordered list for multiple errors, or a paragraph for only one.
- Removes the bullet styling from the error list and adds a small margin between multiple error messages.
- Uses `.notice` and `.notice-error` classes on `div` containers, and updates styles.
- Wraps message paragraphs with a `div` in `login_header()` functions and retains the `message`, `reset-pass` and `register` classes on the `div` **instead of the paragraph**.
- Removes `.clear` elements, and adds a `16px` bottom margin for the password strength indicator and the registration form mail message to replace the `br` elements.
- Edits margin and padding for Reset Password fields:
1. The zero bottom margin that applies to the `rp` action did not apply to `resetpass`.
2. The `2.5rem` right padding for password inputs applies to both the text and password types with the selector `.js.login input.password-input`, so the others would be unnecessary.

[Trac 30685](https://core.trac.wordpress.org/ticket/30685)

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2023-09-20 17:36 UTC, joedolson requested changes
Mostly just needs to be adapted to use `wp_admin_notice()`.

2023-09-20 17:36 UTC, joedolson commented on src/wp-login.php
> +			echo '<div id="login_error" class="notice notice-error">' . apply_filters( 'login_errors', $errors ) . "</div>\n";
This should be updated to use the new `wp_admin_notice()` function.

2023-09-20 17:36 UTC, joedolson commented on src/wp-login.php
> +			echo '<div id="login-message" class="notice notice-info message">' . apply_filters( 'login_messages', $messages ) . "</div>\n";
Should also be updated to use the `wp_admin_notice()` function

2023-09-20 17:36 UTC, joedolson commented on src/wp-login.php
> +		login_header( __( 'Lost Password' ), '<div class="notice notice-info message"><p>' . __( 'Please enter your username or email address. You will receive an email message with instructions on how to
Same issue.

2023-09-20 17:36 UTC, joedolson commented on src/wp-login.php
> +			login_header( __( 'Password Reset' ), '<div class="notice notice-info message reset-pass"><p>' . __( 'Your password has been reset.' ) . ' <a href="' . esc_url( wp_login_url() ) . '">' . __( 'Log
You can probably guess.

2023-09-20 17:36 UTC, joedolson commented on src/wp-login.php
> +		login_header( __( 'Reset Password' ), '<div class="notice notice-info message reset-pass"><p>' . __( 'Enter your new password below or generate one.' ) . '</p></div>', $errors );
This is starting to feel unnecessary. ;)

2023-09-20 17:36 UTC, joedolson commented on src/wp-login.php
> +		login_header( __( 'Registration Form' ), '<div class="notice notice-info message register"><p>' . __( 'Register For This Site' ) . '</p></div>', $errors );
`wp_admin_notice()`

2023-09-20 17:36 UTC, joedolson commented on src/wp-admin/css/login.css
> +.login .notice-error {
This probably makes more sense than including `common.css` on the login page, but it might benefit from a comment to document that these styles are duplicates.

2023-09-20 21:17 UTC, joedolson commented
@costdev Looks like we need to load `wp_admin_notices()` earlier so we can use the function at login. Any thoughts on that?

2023-09-20 22:57 UTC, costdev commented
@joedolson We _could_ move the definitions of `wp_get_admin_notice()` and `wp_admin_notice()` to `wp-includes/functions.php`.

This file is loaded on the frontend and backend.

This is an example of how we can implement `wp_admin_notice()` and work with the login page's stylesheet, as it currently doesn't have access to the admin notice styles. This styling difference can be rectified later, so I don't think that's a blocker for this PR.

```php
if ( ! empty( $messages ) ) {
	/**
	 * Filters instructional messages displayed above the login form.
	 *
	 * @since 2.5.0
	 *
	 * @param string $messages Login messages.
	 */
	$messages = apply_filters( 'login_messages', $messages );
	wp_admin_notice(
		$messages,
		array(
			'id'                 => 'login-message',
			'additional_classes' => array( 'message' ),
			'paragraph_wrap'     => false,
		)
	);
}
```
![image](https://github.com/WordPress/wordpress-develop/assets/79332690/02e2785c-b8e9-4337-a2d6-0f7d52796322)

2023-09-20 23:48 UTC, joedolson commented
I'd like to look at abstracting styles in a later iteration; I could easily see having a dedicated `notices.css` that could hold all of those - and I think the time to work on that is when we go through and migrate non-conforming markup. 

I think there would be benefits to having `wp_admin_notice()` and `wp_get_admin_notice()` available on the front-end for extenders; not with the styles, because any independent front-end usage should provide its own styling, but for this usage I think it makes sense.

2023-09-21 00:31 UTC, costdev commented on src/wp-includes/functions.php
> +
@sabernhardt Thanks for handling this move in this PR!

Can we also move the test files for consistency?
- `tests/phpunit/tests/admin/wpAdminNotice.php` -> `tests/phpunit/tests/functions/wpAdminNotice.php`
- `tests/phpunit/tests/admin/wpGetAdminNotice.php` -> `tests/phpunit/tests/functions/wpGetAdminNotice.php`

2023-09-21 00:41 UTC, costdev commented on tests/phpunit/tests/functions/wpAdminNotice.php
> +class Tests_Admin_WpAdminNotice extends WP_UnitTestCase {
```suggestion
 * @group functions.php
 *
 * @covers ::wp_admin_notice
 */
class Tests_Functions_WpAdminNotice extends WP_UnitTestCase {
```
Couple of minor changes to match the new location. 🙂

2023-09-21 00:41 UTC, costdev commented on tests/phpunit/tests/functions/wpGetAdminNotice.php
> +class Tests_Admin_WpGetAdminNotice extends WP_UnitTestCase {
```suggestion
 * @group functions.php
 *
 * @covers ::wp_get_admin_notice
 */
class Tests_Functions_WpGetAdminNotice extends WP_UnitTestCase {
```
Couple of minor changes to match the new location. 🙂

2023-09-21 00:41 UTC, costdev commented on src/wp-includes/functions.php
> +
[73126ee](https://github.com/WordPress/wordpress-develop/pull/5178/commits/73126ee58e846be2017a694a1e577a4f352db6bc) Thanks!

2023-09-21 02:08 UTC, costdev commented
Thanks for the updates @sabernhardt!

Did a little testing with the following to check that the logic was preserved and just for a general comparison with `trunk`.

The extra spacing between each `error` message is a nice result! 🙂 

```php
add_filter(
    'wp_login_errors',
    function( $errors ) {
        $errors->add( 'message_1', '<strong>Test 1:</strong> One message with a severity.',           'message' );
        $errors->add( 'message_2', '<strong>Test 2:</strong> 1/2 messages with a severity.',          'message' );
        $errors->add( 'message_2', '<strong>Test 2:</strong> 2/2 messages with a severity.',          'message' );
        $errors->add( 'message_3', '<strong>Test 3:</strong> 1/2 messages, first with a severity.',   'message' );
        $errors->add( 'message_3', '<strong>Test 3:</strong> 2/2 messages, first with a severity.',             );
        $errors->add( 'message_4', '<strong>Test 4:</strong> 1/2 messages, second with a severity.'             );
        $errors->add( 'message_4', '<strong>Test 4:</strong> 2/2 messages, second with a severity.',  'message' );
        $errors->add( 'error_1',   '<strong>Test 5:</strong> One error with a severity.',             'error'   );
        $errors->add( 'error_2',   '<strong>Test 6:</strong> One error with no severity.'                       );
        $errors->add( 'error_3',   '<strong>Test 7:</strong> 1/2 errors with a severity.',            'error'   );
        $errors->add( 'error_3',   '<strong>Test 7:</strong> 2/2 errors with a severity.',            'error'   );
        $errors->add( 'error_4',   '<strong>Test 8:</strong> 1/2 errors, first with a severity.',     'error'   );
        $errors->add( 'error_4',   '<strong>Test 8:</strong> 2/2 errors, first with a severity.'                );
        $errors->add( 'error_5',   '<strong>Test 9:</strong> 1/2 errors, last with a severity.'                 );
        $errors->add( 'error_5',   '<strong>Test 9:</strong> 2/2 errors, last with a severity.',      'error'   );
        $errors->add( 'mixed_1',   '<strong>Test 10:</strong> 1/2 errors with different severities.', 'message' );
        $errors->add( 'mixed_1',   '<strong>Test 10:</strong> 2/2 errors with different severities.', 'error'   );
        return $errors;
    }
);
```

![image](https://github.com/WordPress/wordpress-develop/assets/79332690/c949178c-1e30-499d-8b1b-68c45288fbc7)

2023-09-21 18:23 UTC, joedolson commented
In r56654

2023-09-21 18:23 UTC, closed without merging