test for wp_schedule_delete_old_privacy_export_files
WordPress/wordpress-develop pull request #5550
Opened 2023-10-23 17:54 UTC by pbearne

Trac ticket: https://core.trac.wordpress.org/ticket/59707

2026-06-23 14:10 UTC, mindctrl requested changes

2026-06-23 14:10 UTC, mindctrl commented on tests/phpunit/tests/functions/wpScheduleDeleteOldPrivacyExportFiles.php
> + * @covers ::test_wp_schedule_delete_old_privacy_export_files
```suggestion
 * @covers ::wp_schedule_delete_old_privacy_export_files
```

2026-06-23 14:10 UTC, mindctrl commented on tests/phpunit/tests/functions/wpScheduleDeleteOldPrivacyExportFiles.php
> +		wp_installing( false );
If the above assertions fail for some reason, the `wp_installing( false )` won't run. Thoughts on putting it in `tear_down()`?

2026-06-23 14:16 UTC, pbearne commented on tests/phpunit/tests/functions/wpScheduleDeleteOldPrivacyExportFiles.php
> +		wp_installing( false );
I will move it

2026-06-24 17:23 UTC, mindctrl commented on tests/phpunit/tests/functions/wpScheduleDeleteOldPrivacyExportFiles.php
> +		wp_unschedule_event( wp_next_scheduled( 'wp_privacy_delete_old_export_files' ), 'wp_privacy_delete_old_export_files' );
Do we need to call the parent methods?

```suggestion
		parent::set_up();
		wp_unschedule_event( wp_next_scheduled( 'wp_privacy_delete_old_export_files' ), 'wp_privacy_delete_old_export_files' );
```

2026-06-24 17:23 UTC, mindctrl commented on tests/phpunit/tests/functions/wpScheduleDeleteOldPrivacyExportFiles.php
> +		$this->assertFalse( wp_next_scheduled( 'wp_privacy_delete_old_export_files' ) );
```suggestion
		$this->assertFalse( wp_next_scheduled( 'wp_privacy_delete_old_export_files' ) );
		parent::tear_down();
```

2026-06-24 17:23 UTC, mindctrl commented on tests/phpunit/tests/functions/wpScheduleDeleteOldPrivacyExportFiles.php
> +}
This would test the other branch of `wp_schedule_delete_old_privacy_export_files()` where it skips adding a new job if one already exists.

```suggestion

  /**
   * Check that calling the function when already scheduled does not create a duplicate.
   *
   * @ticket 59707
   */
  public function test_wp_schedule_delete_old_privacy_export_files_already_scheduled() {
      wp_schedule_delete_old_privacy_export_files();
      $first = wp_next_scheduled( 'wp_privacy_delete_old_export_files' );

      wp_schedule_delete_old_privacy_export_files();
      $this->assertSame( $first, wp_next_scheduled( 'wp_privacy_delete_old_export_files' ) );
  }
}
```

2026-07-07 09:36 UTC, masteradhoc commented
@pbearne could you check the last feedback from @mindctrl? i'd like to milestone this for 7.1 so we can get this added soon.

2026-07-16 17:44 UTC, roshniahuja commented
Thanks @pbearne for the patch. I've prepared a refreshed version of the test that resolves the outstanding review feedback from @mindctrl on this PR:

- Calls `parent::set_up()` / `parent::tear_down()`.
- Moves the `wp_installing( false )` reset into `tear_down()` so it always runs even if an assertion fails.
- Adds a third test, `test_wp_schedule_delete_old_privacy_export_files_already_scheduled()`, covering the branch where the event is already scheduled (no duplicate is created).
- Adds a standard file docblock, `@group privacy` (the ticket's reassigned component), and assertion failure messages.

Verified locally against `trunk`: `OK (3 tests, 5 assertions)`, and PHPCS is clean.

Branch: https://github.com/roshniahuja/wordpress-develop/tree/59707-test-wp-schedule-delete-old-privacy-export-files

2026-07-16 17:50 UTC, roshniahuja commented
For visibility: I've also opened #[12563](https://github.com/WordPress/wordpress-develop/pull/12563) as an alternative PR carrying these same tests, in case that's an easier path to land than updating this branch. Happy to close it and fold the changes in here instead — whichever maintainers prefer. See #59707.

2026-07-21 13:00 UTC, mindctrl approved these changes

2026-07-28 12:04 UTC, t-hamano commented
@pbearne, Can you address the feedback from Copilot? Both seem like reasonable suggestions.

2026-08-04 18:29 UTC, masteradhoc commented
Thank you @pbearne! The PR would be ready for another review and merge. @t-hamano Can you help out here?

2026-08-05 12:46 UTC, t-hamano commented on tests/phpunit/tests/functions/wpScheduleDeleteOldPrivacyExportFiles.php
> +		parent::tear_down();
Why do we need to execute this within the test method?

2026-08-05 12:46 UTC, t-hamano commented on tests/phpunit/tests/functions/wpScheduleDeleteOldPrivacyExportFiles.php
> +		wp_installing( false );
I believe that restoring within each test is safer than running `wp_installing` within the test.

See:

https://github.com/WordPress/wordpress-develop/blob/7d6fa3a8728c3d25ea173d3893a69c1f13d1b65a/tests/phpunit/tests/privacy/wpPersonalDataCleanupRequests.php#L164-L169

2026-08-05 12:46 UTC, t-hamano commented on tests/phpunit/tests/functions/wpScheduleDeleteOldPrivacyExportFiles.php
> +
```suggestion
	public function test_wp_schedule_delete_old_privacy_export_files() {
```

2026-08-05 12:46 UTC, t-hamano commented on tests/phpunit/tests/functions/wpScheduleDeleteOldPrivacyExportFiles.php
> +		$this->assertIsInt( wp_next_scheduled( 'wp_privacy_delete_old_export_files' ) );
When executing multiple assertions within a single test, it is recommended to include a message.

https://make.wordpress.org/core/handbook/testing/automated-testing/writing-phpunit-tests/#:~:text=This%20parameter%20should%20always%20be%20used%20if%20more%20than%20one%20assertion%20is%20used%20in%20a%20test%20method.

2026-08-05 12:46 UTC, t-hamano commented on tests/phpunit/tests/functions/wpScheduleDeleteOldPrivacyExportFiles.php
> +		$this->assertFalse( wp_next_scheduled( 'wp_privacy_delete_old_export_files' ) );
When executing multiple assertions within a single test, it is recommended to include a message.

https://make.wordpress.org/core/handbook/testing/automated-testing/writing-phpunit-tests/#:~:text=This%20parameter%20should%20always%20be%20used%20if%20more%20than%20one%20assertion%20is%20used%20in%20a%20test%20method.

2026-08-05 16:38 UTC, pbearne commented on tests/phpunit/tests/functions/wpScheduleDeleteOldPrivacyExportFiles.php
> +		parent::tear_down();
we don't

2026-08-07 08:32 UTC, t-hamano commented on tests/phpunit/tests/functions/wpScheduleDeleteOldPrivacyExportFiles.php
> +		$this->assertSame( $first, wp_next_scheduled( 'wp_privacy_delete_old_export_files' ) );
```suggestion
		// Schedule ahead of time() so that a duplicate would land on a different timestamp.
		wp_schedule_event( strtotime( '+1 hour' ), 'hourly', 'wp_privacy_delete_old_export_files' );

		// Take a snapshot of the cron option while the event is scheduled.
		$expected = _get_cron_array();

		// The event is already scheduled, so this call should be a no-op.
		wp_schedule_delete_old_privacy_export_files();

		// Check cron option is unchanged.
		$this->assertSame( $expected, _get_cron_array(), 'the event should not be scheduled again' );
```

This assertion doesn't currently catch a regression — removing [the `! wp_next_scheduled()` guard](https://github.com/WordPress/wordpress-develop/blob/f358f5ec386f2dfdc24a7de992295fe1327234f5/src/wp-includes/functions.php#L8556) leaves this test green. Two reasons:

1. `wp_schedule_event()` stores events as `$crons[ $timestamp ][ $hook ][ md5( serialize( $args ) ) ]`. This function always schedules with no args, so both calls collide on all three keys when they happen within the same second — the second one silently overwrites the first, and no duplicate is ever observable.
2. Even if the two calls land on different seconds, `wp_next_scheduled()` only returns the soonest timestamp, so it still returns `$first` and the assertion passes.

Seeding the event at a timestamp other than `time()` and comparing the whole cron option would cover both cases:

This follows the same pattern as [test_pre_schedule_event_filter()](https://github.com/WordPress/wordpress-develop/blob/f358f5ec386f2dfdc24a7de992295fe1327234f5/tests/phpunit/tests/cron.php#L424).

2026-08-07 08:32 UTC, t-hamano commented on tests/phpunit/tests/functions/wpScheduleDeleteOldPrivacyExportFiles.php
> +		wp_installing( $prior );
```suggestion
		$this->assertFalse( wp_next_scheduled( 'wp_privacy_delete_old_export_files' ), 'no export should be scheduled' );

		// set to installing mode
		$prior = wp_installing();
		wp_installing( true );

		wp_schedule_delete_old_privacy_export_files();

		wp_installing( $prior );

		$this->assertFalse( wp_next_scheduled( 'wp_privacy_delete_old_export_files' ), 'no export should be scheduled while installing' );
```

Since the installing mode restoration occurs after the assertion, if the assertion fails, the installing mode is not restored, which affects subsequent tests. I believe we need to be careful about the order to ensure that the installing mode is always restored regardless of whether the assertion succeeds or fails.

Also, please note that the message has been changed from `export should be scheduled` to `no export should be scheduled while installing`. The previous message indicated the opposite of the assertion.

2026-08-11 02:13 UTC, t-hamano approved these changes

2026-08-11 02:38 UTC, closed without merging