test for wp_privacy_exports_url
WordPress/wordpress-develop pull request #5551
Opened 2023-10-23 18:27 UTC by pbearne

Trac ticket: https://core.trac.wordpress.org/ticket/59709

2024-01-11 10:03 UTC, jdstphen00 commented
https://sloto-mania.co.uk
https://cryptocasino4u.com
https://365bet4u.com

2026-06-25 14:19 UTC, mindctrl requested changes

2026-06-25 14:19 UTC, mindctrl commented on tests/phpunit/tests/functions/wpPrivacyExportsUrl.php
> +class Tests_functions_test_wp_privacy_exports_url extends WP_UnitTestCase {
With the current filename and classname, phpunit complains about not being able to find the class. We can do the class or the file.

```suggestion
class Tests_functions_test_wpPrivacyExportsUrl extends WP_UnitTestCase {
```

2026-06-25 14:19 UTC, mindctrl commented on tests/phpunit/tests/functions/wpPrivacyExportsUrl.php
> + */#
```suggestion
 */
```

2026-06-25 14:19 UTC, mindctrl commented on tests/phpunit/tests/functions/wpPrivacyExportsUrl.php
> +		$this->assertEquals( 'http://example.org/wp-content/uploads/wp-personal-data-exports/', wp_privacy_exports_url() );
Just a nit, to match other patterns in the tests folder.

```suggestion
		$this->assertSame( 'http://example.org/wp-content/uploads/wp-personal-data-exports/', wp_privacy_exports_url() );
```

2026-06-25 14:19 UTC, mindctrl commented on tests/phpunit/tests/functions/wpPrivacyExportsUrl.php
> +		$this->assertEquals( $expected_url, $actual_url );
```suggestion
		$this->assertSame( $expected_url, $actual_url );
```

2026-06-25 14:19 UTC, mindctrl commented on tests/phpunit/tests/functions/wpPrivacyExportsUrl.php
> +		remove_filter( 'wp_privacy_exports_url', array( $this, 'filter_wp_privacy_exports_url' ) );
Maybe an edge case, but I think we need to move `remove_filter` to `tear_down()`, in case the assertion ever fails it won't leak into other tests.

2026-07-01 14:09 UTC, mindctrl approved these changes

2026-07-07 09:36 UTC, masteradhoc commented
Thanks for the work @pbearne and the reviews @mindctrl. i'll milestone this for 7.1 now.

2026-07-30 14:14 UTC, mindctrl reviewed
Looks good overall. The remaining Copilot suggestions make sense.

2026-08-02 09:21 UTC, t-hamano commented
Hi @pbearne, do you have the bandwidth to address the Copilot reviews?

2026-08-04 17:45 UTC, pbearne commented
done

2026-08-04 18:32 UTC, masteradhoc commented
~~@pbearne can you recheck? the last commit removed the } on line 22.~~

LGTM! @t-hamano can you recheck this one as well?

2026-08-05 08:44 UTC, t-hamano commented on tests/phpunit/tests/functions/wpPrivacyExportsUrl.php
> + * @group functions.php
```suggestion
 * @group functions
 ```

2026-08-05 08:44 UTC, t-hamano commented on tests/phpunit/tests/functions/wpPrivacyExportsUrl.php
> +	public function tear_down() {
This `tear_down` method itself should be removable because anything added via `add_filter` should be cleaned up by the base class's tear_down.

2026-08-05 08:44 UTC, t-hamano commented on tests/phpunit/tests/functions/wpPrivacyExportsUrl.php
> +		return 'https://filtered.com/wp-personal-data-exports/';
```suggestion
		return str_replace( 'wp-personal-data-exports/', 'filtered-exports/', $exports_url );
```

This is a similar change to the one in https://github.com/WordPress/wordpress-develop/pull/5553#discussion_r3698613696. I believe we need to test the filter parameters.

2026-08-05 12:28 UTC, t-hamano commented on tests/phpunit/tests/functions/wpPrivacyExportsUrl.php
> + * @group functions.php
Fixed in 8a127b00fa

2026-08-05 12:28 UTC, t-hamano commented on tests/phpunit/tests/functions/wpPrivacyExportsUrl.php
> +	public function tear_down() {
Fixed in d501f656b6

2026-08-05 12:28 UTC, t-hamano commented on tests/phpunit/tests/functions/wpPrivacyExportsUrl.php
> +		return 'https://filtered.com/wp-personal-data-exports/';
Fixed in 4428823cfe

2026-08-05 12:49 UTC, t-hamano approved these changes

2026-08-05 13:04 UTC, closed without merging