59710 wp privacy exports dir
WordPress/wordpress-develop pull request #5553
Opened 2023-10-23 19:36 UTC by pbearne

Trac ticket: https://core.trac.wordpress.org/ticket/59710

2024-01-13 07:34 UTC, trfga12 commented
also same issue in following sites 
https://saptahikpatrika.com
https://www.newweborder.co

2026-06-24 19:06 UTC, mindctrl requested changes

2026-06-24 19:06 UTC, mindctrl commented on tests/phpunit/tests/functions/wpPrivacyExportsDir.php
> +class Tests_functions_wp_privacy_exports_dir extends WP_UnitTestCase {
Fixes issue where phpunit throws saying: `Class wpPrivacyExportsDir could not be found in /var/www/tests/phpunit/tests/functions/wpPrivacyExportsDir.php` 

Matches the pattern in #5550.

```suggestion
class Tests_Functions_wpPrivacyExportsDir extends WP_UnitTestCase {
```

2026-06-24 19:06 UTC, mindctrl commented on tests/phpunit/tests/functions/wpPrivacyExportsDir.php
> + */#
```suggestion
 */
```

2026-06-24 19:06 UTC, mindctrl commented on tests/phpunit/tests/functions/wpPrivacyExportsDir.php
> +		$this->assertEquals( $expected_url, $actual_url );
```suggestion
		$expected_dir = '/wp-personal-data-exports-dir/';
		$actual_dir   = wp_privacy_exports_dir();
		$this->assertEquals( $expected_dir, $actual_dir );
```

2026-06-24 19:06 UTC, mindctrl commented on tests/phpunit/tests/functions/wpPrivacyExportsDir.php
> +		return '/wp-personal-data-exports-url/';
```suggestion
		return '/wp-personal-data-exports-dir/';
```

2026-07-01 14:15 UTC, mindctrl requested changes

2026-07-01 14:15 UTC, mindctrl commented on tests/phpunit/tests/functions/wpPrivacyExportsDir.php
> +		$this->assertEquals( '/var/www/src/wp-content/uploads/wp-personal-data-exports/', wp_privacy_exports_dir() );
Deriving the directory at runtime should allow the tests to run in other setups.

```suggestion
		$upload_dir = wp_upload_dir();
		$expected   = trailingslashit( $upload_dir['basedir'] ) . 'wp-personal-data-exports/';
		$this->assertSame( $expected, wp_privacy_exports_dir() );
```

2026-07-01 14:15 UTC, mindctrl commented on tests/phpunit/tests/functions/wpPrivacyExportsDir.php
> +		$this->assertEquals( $expected_dir, $actual_dir );
```suggestion
		$this->assertSame( $expected_dir, $actual_dir );
```

2026-07-07 09:35 UTC, masteradhoc commented
@pbearne could you check the last feedback from @mindctrl? i'd like to milestone this for 7.1 so we can get this added soon.

2026-07-30 14:08 UTC, mindctrl approved these changes

2026-08-02 09:53 UTC, t-hamano commented on tests/phpunit/tests/functions/wpPrivacyExportsDir.php
> + * @group functions.php
```suggestion
 * @group functions
```

2026-08-02 09:53 UTC, t-hamano commented on tests/phpunit/tests/functions/wpPrivacyExportsDir.php
> +		add_filter( 'wp_privacy_exports_dir', array( $this, 'filter_wp_privacy_exports_dir' ) );
```suggestion
	public function test_wp_privacy_exports_dir_filtered() {
		add_filter( 'wp_privacy_exports_dir', array( $this, 'filter_wp_privacy_exports_dir' ) );
```

2026-08-02 09:53 UTC, t-hamano commented on tests/phpunit/tests/functions/wpPrivacyExportsDir.php
> +	}
The test confirms that the hook is applied and that its return value is used, but the callback ignores its argument entirely. As a result, the value passed to the filter is never verified — changing the implementation to `apply_filters( 'wp_privacy_exports_dir', 'garbage' )` would still pass.

I think deriving the returned value from `$exports_dir` closes that gap.

```php
public function filter_wp_privacy_exports_dir( $exports_dir ) {
	return str_replace( 'wp-personal-data-exports/', 'filtered-exports/', $exports_dir );
}
```

2026-08-04 18:26 UTC, masteradhoc commented
@pbearne Thank you! Could you check the PHP Unit Test Error?

```
There was 1 failure:

1) Tests_Functions_wpPrivacyExportsDir::test_wp_privacy_exports_dir_filtered
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'/wp-personal-data-exports-dir/'
+'/var/www/src/wp-content/uploads/filtered-exports/'

/var/www/tests/phpunit/tests/functions/wpPrivacyExportsDir.php:28
phpvfscomposer:///var/www/vendor/phpunit/phpunit/phpunit:106
/var/www/vendor/bin/phpunit:118
```

2026-08-05 08:07 UTC, t-hamano commented
> Could you check the PHP Unit Test Error?

I have fixed this.

2026-08-05 08:16 UTC, t-hamano approved these changes

2026-08-05 08:55 UTC, masteradhoc commented
Thank you @t-hamano appreciate we can get this out :)

2026-08-05 09:02 UTC, closed without merging