Adding the initial Tooltip
WordPress/wordpress-develop pull request #5676
Opened 2023-11-16 00:42 UTC by Rajinsharwar

PR for adding the initial draft for the Tooltip functionality.

Trac ticket: https://core.trac.wordpress.org/ticket/51006

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-01-18 10:50 UTC, ayazwpseo commented
I find myself grappling with precisely the same challenge at the moment. Your guidance is greatly appreciated.
{{{
#!html
<a href="https://casinonewsupdate.com/"></a>
<a href="https://casino-worlds.com/"></a>
<a href="https://casinonewsspot.com/"></a>
<a href="https://casino-hotspot.com/"></a>
<a href="https://casinoworldnews4u.com/"></a>
<a href="https://allaroundcasino.com/"></a>
<a href="https://casinodada.com/"></a>
<a href="https://casinoguide4u.com/"></a>
<a href="http://casinomedia.co.uk/"></a>
<a href="http://casinopost.co.uk/"></a>
<a href="http://casino-days.co.uk/"></a>
<a href="http://casino-guru.co.uk/"></a>
<a href="http://betting-post.com/"></a>
<a href="http://jammymonkey.uk/"></a>
<a href="https://vefeed.com/"></a>
<a href="https://puffmi.com.au"></a>
}}}

2024-01-23 13:47 UTC, sarinajor commented
<a href='https://capmistoi-6221.weebly.com'>.</a>
<a href='https://capmistoi-6222.weebly.com'>.</a>
<a href='https://capmistoi-6223.weebly.com'>.</a>
<a href='https://capmistoi-6224.weebly.com'>.</a>
<a href='https://capmistoi-6225.weebly.com'>.</a>
<a href='https://capmistoi-6226.weebly.com'>.</a>
<a href='https://capmistoi-6227.weebly.com'>.</a>
<a href='https://capmistoi-6228.weebly.com'>.</a>
<a href='https://capmistoi-6229.weebly.com'>.</a>
<a href='https://capmistoi-6230.weebly.com'>.</a>
<a href='https://capmistoi-6231.weebly.com'>.</a>
<a href='https://capmistoi-6232.weebly.com'>.</a>
<a href='https://capmistoi-6233.weebly.com'>.</a>
<a href='https://capmistoi-6234.weebly.com'>.</a>
<a href='https://capmistoi-6235.weebly.com'>.</a>
<a href='https://capmistoi-6236.weebly.com'>.</a>
<a href='https://capmistoi-6237.weebly.com'>.</a>
<a href='https://capmistoi-6238.weebly.com'>.</a>
<a href='https://capmistoi-6239.weebly.com'>.</a>
<a href='https://capmistoi-6240.weebly.com'>.</a>

2024-07-15 22:25 UTC, Rajinsharwar commented
1. Added validations and _doing_it_wrong fro the arguments passed.
2. Added a new filter that can be used to change the Tooltip icon image. This is similar to the one we have in add_menu() function. We can now pass the URL, or the SVG, or the dashicon class, or even the "none" to style using CSS.

Example usage:
```
add_filter( 'wp_tooltip_icon', 'my_filter', 10, 2 );

function my_filter( $icon_url, $field_id ) {
    $icon_url = "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMjAiIHZpZXdib3g9IjAgMCAyMCAyMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsPSIjYTdhYWFkIiBkPSJNMTcuNiA4LjVoLTcuNXYzaDQuNGMtLjQgMi4xLTIuMyAzLjUtNC40IDMuNC0yLjYtLjEtNC42LTIuMS00LjctNC43LS4xLTIuNyAyLTUgNC43LTUuMSAxLjEgMCAyLjIuNCAzLjEgMS4ybDIuMy0yLjJDMTQuMSAyLjcgMTIuMSAyIDEwLjIgMmMtNC40IDAtOCAzLjYtOCA4czMuNiA4IDggOGM0LjYgMCA3LjctMy4yIDcuNy03LjgtLjEtLjYtLjEtMS4xLS4zLTEuN3oiIGZpbGxydWxlPSJldmVub2RkIiBjbGlwcnVsZT0iZXZlbm9kZCI+PC9wYXRoPjwvc3ZnPg==";

    return $icon_url;
}
```
This will show an SVG now in the tooltip.

Example:

![image](https://github.com/user-attachments/assets/2a6783ed-ab70-4c4a-bfe4-9c7aaa7f8f12)

3. Added a new action hook that's fired just before the tooltip is rendered in HTML.
4. Loading the styles and scripts for the tooltip before it's rendered to not show a slightly broken tooltip.

Screenshots:

![image](https://github.com/user-attachments/assets/3a476567-85c0-4647-abd0-c8b10a62d124)

Using Tab navigation: 

![image](https://github.com/user-attachments/assets/0733888d-59ac-4f96-abe7-c04500a4df4b)

2025-01-28 00:47 UTC, joedolson requested changes
This is a first round of feedback; I've still got some more things to look at.

2025-01-28 00:47 UTC, joedolson commented on src/js/_enqueues/wp/wp-tooltip.js
> +		tooltipButton.style.cursor = 'help';
Let's not customize the cursor. Let it use the standard cursor for buttons in WordPress.

2025-01-28 00:47 UTC, joedolson commented on src/wp-includes/css/wp-tooltip.css
> +.wp-tooltip-button:focus {
This should inherit existing styles for buttons, so that :focus states are standardized. Probably add the class 'button' to the trigger and only add additional styles if there is something that needs to be overwritten.

2025-01-28 00:47 UTC, joedolson commented on src/wp-includes/functions.php
> +		$icon_html = '<span ' . $icon . '></span>';
Add `aria-hidden` to the image container class, to prevent it from being read by screen readers.

2025-01-28 00:47 UTC, joedolson commented on src/wp-includes/functions.php
> +		$icon_html = '<svg height = "20" width = "20"' . $icon . '</svg>';
Add `aria-hidden` to the SVG, as well as `focusable="false"` to prevent older browser from focusing the SVG independently from the button.

2025-01-28 00:47 UTC, joedolson commented on src/wp-includes/functions.php
> +		$icon_html = '<span class="dashicons dashicons-editor-help"></span>';
Add `aria-hidden` here, as well.

2025-02-02 21:35 UTC, joedolson requested changes
Some additional comments.

2025-02-02 21:35 UTC, joedolson commented on src/wp-includes/functions.php
> + * @param string $tooltip_button_label Optional. The label for the tooltip button. Default is 'Help'.
Change the default value to an empty string, and set the default as `__( 'Help' )` inside the function, so that the default value is translatable.

2025-02-02 21:35 UTC, joedolson commented on src/wp-includes/functions.php
> +function add_tooltip( $field_id, $tooltip_text, $tooltip_button_label = 'Help', $position = 'right' ) {
Let's make the arguments into an array, so that the order isn't important. Somebody should be able to set the position without needing to define the button label.

2025-02-02 21:35 UTC, joedolson commented on src/wp-includes/functions.php
> +		<div id="<?php echo esc_attr( $field_id ); ?>-tooltip" class="wp-tooltip-content">
Add `role="tooltip"`

2025-02-02 21:35 UTC, joedolson commented on src/js/_enqueues/wp/wp-tooltip.js
> +		tooltipContainer.addEventListener( 'mouseleave', hideTooltip );
For accessibility, the tooltip should not be hidden on `mouseleave`; only when either the trigger loses focus or when `esc` is hit.

2025-02-11 22:49 UTC, joedolson approved these changes

2025-02-14 15:29 UTC, swissspidy commented on src/wp-includes/functions.php
> +use function PHPSTORM_META\map;
This needs to be reverted

2025-02-14 15:31 UTC, swissspidy commented on src/wp-includes/functions.php
> +				__( 'The "%s" argument must be a non-empty string.' ),
Technically only `$tooltip_text` is checked to be non-empty, so the error message is incorrect for the other variables.

I also find the switch here very confusing. If you fix `$field_id` then you get the next warning for the next variable. That doesn't make sense to me.

I'd just add three checks in a row or so:

```
if ( ! is_string( $field_id ) || '' === $field_id ) {
	_doing_it_wrong(...);
}

if ( ! is_string( $tooltip_text ) || '' === $tooltip_text ) {
	_doing_it_wrong(...);
}

if ( ! is_string( $button_label ) ) {
	_doing_it_wrong(...);
}
```

2025-02-14 15:31 UTC, swissspidy commented on src/wp-includes/functions.php
> +	if ( ! is_string( $position ) || ! in_array( $position, $valid_positions, true ) ) {
The `is_string` check is superfluous

2025-02-14 15:32 UTC, swissspidy commented on src/wp-includes/functions.php
> +			'6.8.0'
What does this have to do with the hook below?

Also it's not a filter, it's an action.

2025-02-14 15:33 UTC, swissspidy commented on src/wp-includes/functions.php
> +	add_action( 'pre_wp_tooltip_rendered', $field_id, $tooltip_text, $button_label, $position, $icon_url );
What is this good for? `pre_` actions are not so common, and `pre_` filters would be used to short-circuit rendering.

2025-02-14 15:33 UTC, swissspidy commented on src/wp-includes/script-loader.php
> +	$scripts->add( 'wp-tooltip', "/wp-includes/js/wp-tooltip$suffix.js", array( 'jquery' ), false, 1 );
Why does this use jQuery?

2026-07-14 18:51 UTC, closed without merging