Added tests for wp_timezone_choice
WordPress/wordpress-develop pull request #5694
Opened 2023-11-21 23:08 UTC by pbearne

Trac ticket: https://core.trac.wordpress.org/ticket/59941

2025-01-22 22:42 UTC, audrasjb requested changes
Thanks for the PR, looks good to me. I added a few nitpick comments :)

2025-01-22 22:42 UTC, audrasjb commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +	 * Default values
missing period :)

2025-01-22 22:42 UTC, audrasjb commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +	 * zones are selected from the list.
Would be nice to capitalize "Zones" :)

2025-01-22 22:42 UTC, audrasjb commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +	 * Test passing the locale in
missing period :)

2025-01-22 22:42 UTC, audrasjb commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +	 * Sett the locale globally
Set, not Sett + missing period ;)

2025-11-03 19:03 UTC, SirLouen requested changes
A last check before 6.9

2025-11-03 19:03 UTC, SirLouen commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +		$selected_timezone_option = '<option value="America/Los_Angeles">Los Angeles</option>';
@pbearne wouldn't be better to set a dataProvider for all these tests?

2025-11-03 21:12 UTC, westonruter requested changes

2025-11-03 21:12 UTC, westonruter commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +		restore_current_locale();
This should be moved to `tear_down` if it isn't automatically handled by the test cleanup logic already.

```suggestion
```

2025-11-03 21:12 UTC, westonruter commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +
```suggestion
```

2025-11-03 21:12 UTC, westonruter commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +
```suggestion
```

2025-11-03 21:12 UTC, westonruter commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +		// Test an tranalated city.
```suggestion
		// Test a translated city.
```

2025-11-05 19:16 UTC, pbearne commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +		$selected_timezone_option = '<option value="America/Los_Angeles">Los Angeles</option>';
done

2025-11-05 23:07 UTC, SirLouen requested changes
Overall, it's looking good to me. 
I've sent you a PR with some final little CS tweaks.

2025-11-06 00:37 UTC, westonruter requested changes

2025-11-06 00:37 UTC, westonruter commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +	 */
```suggestion
```

2025-11-06 00:37 UTC, westonruter commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +	 * @return array
```suggestion
	 * @return array<string, string[]>
```

2025-11-06 00:37 UTC, westonruter commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +	 * @return array
```suggestion
	 * @return array<string, string[]>
```

2025-11-06 00:37 UTC, westonruter commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +	 * @return array
```suggestion
	 * @return array<string, string[]>
```

2025-11-06 00:37 UTC, westonruter commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +	 * @return array
```suggestion
	 * @return array<string, string[]>
```

2025-11-06 00:37 UTC, westonruter commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +	}
```suggestion
	public function tear_down() {
		restore_current_locale();
		parent::tear_down();
	}

```

2025-11-06 16:25 UTC, SirLouen commented
@pbearne did you see my PR?

2025-11-06 17:33 UTC, westonruter commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +	 */
Still needs to be applied.

2025-11-07 04:45 UTC, westonruter approved these changes
This looks good to me, at least the code in `tests/functions`. For the changes in `data/languages`, I have no experience. So I defer to someone who has.

2025-11-07 04:46 UTC, westonruter commented
> did you see my PR?

@SirLouen Can you apply your suggestions directly to this PR? Or can you provide a link to the PR you're referring to?

2025-11-24 12:15 UTC, SirLouen commented
@westonruter it was only some little tweaks I sent back in the day to @pbearne 's branch 
https://github.com/pbearne/wordpress-develop/pull/183

2025-11-24 17:13 UTC, westonruter commented
@SirLouen I fixed the merge conflicts and merged the branch into this one.

2025-11-24 17:18 UTC, SirLouen approved these changes
> @SirLouen I fixed the merge conflicts and merged the branch into this one.

Great, do you think it's ready for commit?
There have been some minor tweaks lately that I hope I have not skipped, but it's looking good to me.

2025-11-24 17:24 UTC, westonruter commented
As far as I can see, yes, it looks ready for commit. But I don't have any experience with adding files to `‎tests/phpunit/data` so I defer to someone with i18n expertise, especially @swissspidy.

2026-03-25 16:33 UTC, juanmaguitar commented
@swissspidy This PR seems ready to be merged. As per [this comment](https://github.com/WordPress/wordpress-develop/pull/5694#issuecomment-3571920844) do you think you'll be able to have a final look at it before WP 7.0 final release date ([in a few weeks](https://make.wordpress.org/core/7-0/))

2026-03-25 17:06 UTC, swissspidy commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +	public function data_wp_timezone_choice_es_set(): array {
```suggestion
	public static function data_wp_timezone_choice_es_set(): array {
```

2026-03-25 18:03 UTC, swissspidy commented
🚢  it

2026-03-25 19:25 UTC, swissspidy commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +			'city in Americas'             => array( '<option value="America/Los_Angeles">Los Angeles</option>' ),
```suggestion
			'city in Americas'             => array( '<option value="America/Los_Angeles" dir="auto">Los Angeles</option>' ),
```

2026-03-25 19:26 UTC, swissspidy commented on tests/phpunit/tests/functions/wpTimezoneChoice.php
> +			'translated city name appears' => array( '<option value="Pacific/Port_Moresby">Port Moresby</option>' ),
```suggestion
			'city in Americas'             => array( '<option value="America/Los_Angeles" dir="auto">Los Angeles</option>' ),
			'deprecated timezone'          => array( '<option value="Pacific/Honolulu" dir="auto">Honolulu</option>' ),
			'manual offset example'        => array( '<option value="UTC-8" dir="auto">UTC-8</option>' ),
			'UTC option'                   => array( '<option value="UTC" dir="auto">UTC</option>' ),
			'continent example'            => array( '<option value="Africa/Johannesburg" dir="auto">Johannesburg</option>' ),
			'city example'                 => array( '<option value="Asia/Kuala_Lumpur" dir="auto">Kuala Lumpur</option>' ),
			'city with sub-city'           => array( '<option value="America/Argentina/Buenos_Aires" dir="auto">Argentina - Buenos Aires</option>' ),
			'translated city name appears' => array( '<option value="Pacific/Port_Moresby" dir="auto">Port Moresby</option>' ),
```

2026-03-25 23:08 UTC, westonruter commented
@swissspidy The tests weren't passing after 9165507. It seems some `dir=auto` attributes were missing from the tests. I added them in bb85bc6. Please review.

2026-03-26 06:20 UTC, swissspidy commented
Ah thanks. Still good to go :)

2026-03-26 22:29 UTC, closed without merging