Update blocks.php
WordPress/wordpress-develop pull request #5799
Opened 2023-12-19 19:58 UTC by josephfusco

Trac ticket: 

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-01-03 09:25 UTC, gziolo commented
Resharing my https://github.com/WordPress/gutenberg/issues/57234#issuecomment-1875059772 from the issue in the Gutenberg repository. I propose that we remove the handling for the missing asset file and provide the default values instead. To land this patch, the required changes would be removing the proposed filter, and the `_doing_it_wrong` handling. It would be great to add a unit test that covers the case when there is no asset file provided.

2024-01-05 15:53 UTC, colorful-tones commented
It looks like unit tests are failing. I do not have the knowledge to fix or write 'em. Would it be necessary for merging, and could we have a separate follow-up PR to address the tests @gziolo ?

2024-01-05 15:54 UTC, colorful-tones commented
Also, would it be easier to move this patch to be against the Gutenberg repo?

2024-01-05 19:07 UTC, josephfusco commented
A lot of the failing tests were fixed with https://github.com/WordPress/wordpress-develop/pull/5799/commits/5c67d336cc762757a2123e0e6c0f982efd52d12c, however there are still a few tests failing but seem unrelated.

> Also, would it be easier to move this patch to be against the Gutenberg repo?

If the code for `register_block_script_handle` is sourced from outside of wordpress-develop, I'm happy to move this patch there.

2024-01-05 19:32 UTC, gziolo reviewed
Thank you for iterations. All changes need to get applied in WordPress core.

2024-01-05 19:32 UTC, gziolo commented on src/wp-includes/blocks.php
> +		$script_asset = array(
Would it be possible to simplify it to:

```suggestion
		$script_asset = array();
```

given that access to the array is guarded later and the same default values seem to be provided?

2024-01-05 19:32 UTC, gziolo commented on tests/phpunit/tests/blocks/register.php
> -	 * @expectedIncorrectUsage register_block_script_handle
It looks like we had a case with a missing asset file covered, so it no longer has to assert for doing it wrong call 👍

2024-01-05 19:32 UTC, gziolo commented on tests/phpunit/tests/blocks/register.php
> +		$this->assertFalse( $result );
What’s the reason that it returns `false`? Shouldn't it return the generated handle name instead?

2024-01-05 19:33 UTC, gziolo commented on src/wp-includes/blocks.php
>  		return false;
Ok, we should remove this early exit so the asset gets correctly registered.

2024-01-06 02:12 UTC, spacedmonkey requested changes

2024-01-06 02:12 UTC, spacedmonkey commented on src/wp-includes/blocks.php
> +	if ( file_exists( $script_asset_path ) ) {
Can we avoid this file exists? This check is bad for performance.

2024-01-06 02:12 UTC, spacedmonkey commented on src/wp-includes/blocks.php
> +	if ( file_exists( $script_asset_path ) ) {
Could we try an include instead?

2024-01-10 17:49 UTC, colorful-tones commented
Nice progress here @josephfusco ! 🕺

2024-02-07 13:09 UTC, gziolo commented on tests/phpunit/tests/blocks/register.php
> +		$this->assertSame( 'unit-tests-test-block-script' );
```suggestion
		$this->assertSame( 'unit-tests-test-block-script', $result );
```

2024-02-07 13:12 UTC, gziolo commented on src/wp-includes/blocks.php
> +	$script_asset        = @include $script_asset_path;
```suggestion
	// Asset file for blocks is optional. See https://core.trac.wordpress.org/ticket/60460.
	$script_asset        = @include $script_asset_path;
```

2024-02-08 08:10 UTC, gziolo approved these changes
Updating code directly on GitHub isn't the best idea after all 😅 

The good news is that it's ready to go!

2024-02-08 08:20 UTC, gziolo commented
Committed with https://core.trac.wordpress.org/changeset/57559.

2024-02-08 08:20 UTC, closed without merging

2024-02-08 10:04 UTC, colorful-tones commented
Thanks for getting this over the line @gziolo and thanks @josephfusco for kicking it off 🙌