Drop php4 support for do action first arg array object type in favor of better support of PHP7+ native types
WordPress/wordpress-develop pull request #5839
Opened 2024-01-04 01:37 UTC by kkmuffme

Drop PHP 4 support for `do_action` with 1 array<object> argument where the array contains only 1 element, in favor of better support for PHP 7+ native types

Trac ticket: https://core.trac.wordpress.org/ticket/60190

2024-02-07 19:29 UTC, johnbillion requested changes
Can you provide some new unit tests that demonstrate the benefit of this change? What can be done after this change that can't be done currently?

2024-03-27 20:40 UTC, kkmuffme commented
Yes, I added a test now (which would result in a fatal error without this PR on standard WP 6.5)

2025-05-23 16:43 UTC, azaozz commented on src/wp-includes/plugin.php
> +	if ( array() === $arg ) {
Probably missing something but this change doesn't seem to be part of the [trac ticket](https://core.trac.wordpress.org/ticket/60190)? 

This changes the behavior for `false`, `null`, `0`, etc. (all things considered "empty" in PHP). After this patch `$arg` will not be an empty string in these cases, right? Thinking this is a potentially big back-compat break, and also not part of the proposed fix as in the trac ticket.

If this is intentional please open a new ticket with reasoning why this is needed and tests to confirm the back-compat issues it may introduce.

2025-05-23 16:49 UTC, azaozz requested changes
https://github.com/WordPress/wordpress-develop/pull/5839/files#r2105010248

2025-05-24 11:25 UTC, johnbillion commented on src/wp-includes/plugin.php
> +	if ( array() === $arg ) {
`$arg` is a variadic parameter which means it'll only ever be an array. This change could have been made as part of r46322.

2025-09-08 21:00 UTC, closed without merging