60740
WordPress/wordpress-develop pull request #6249
Opened 2024-03-11 16:14 UTC by joedolson

Return the array of all icons found in icon directory if the preferred extension is not found.

Trac ticket: https://core.trac.wordpress.org/attachment/ticket/60740

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-03-12 13:42 UTC, audrasjb requested changes
Looks good at a glance. I left a small recommendation to facilitate a commit in 6.5.

2024-03-12 13:42 UTC, audrasjb commented on src/wp-includes/admin-bar.php
> -				/* translators: %s: Current user's display name. */
If we want to commit this in milestone 6.5, it would be nice to keep the translator comment as it is, so the string doesn't get fuzzied (we're in string freeze workflow right now)

2024-03-12 16:12 UTC, sabernhardt commented on src/wp-includes/admin-bar.php
> -				/* translators: %s: Current user's display name. */
Could you remove all the admin toolbar changes (rebase/update the branch to include changes from r57765)?

2024-03-13 15:11 UTC, joedolson commented on src/wp-includes/admin-bar.php
> -				/* translators: %s: Current user's display name. */
Huh. I thought I'd reverted those changes already; didn't expect them in here.

2024-03-13 15:16 UTC, joedolson commented on src/wp-includes/admin-bar.php
> -				/* translators: %s: Current user's display name. */
For reference, only the changes in /post.php are relevant to the PR.

2024-03-13 15:28 UTC, closed without merging