added font directory path and size to site health
WordPress/wordpress-develop pull request #6260
Opened 2024-03-12 16:54 UTC by andr3ribeiro

Added the font directory in the array for site health table iteration

Trac ticket: https://core.trac.wordpress.org/ticket/60719

2024-04-12 21:35 UTC, ironprogrammer commented
Thanks for the PR, @andr3ribeiro! Perhaps a good addition to this would be to include the fonts dir "is writable" check found on the Filesystem Permissions tab. This work is something we could probably get merged early this cycle.

2024-05-27 22:38 UTC, peterwilsoncc requested changes
Similar to the uploads directory tests, this should use the `basedir` value rather than `path`.

While they are the same on a default WordPress install, plugins may filter the path for individual uploads by adding a sub-directory, for example:

```php
array (
  'path' => '/path/to/wp-content/uploads/fonts/font-family',
  'url' => 'http://example.com/wp-content/uploads/fonts/font-family',
  'subdir' => '/font-family',
  'basedir' => '/path/to/wp-content/uploads/fonts',
  'baseurl' => 'http://example.com/wp-content/uploads/fonts',
  'error' => false,
)
```

2024-05-27 22:38 UTC, peterwilsoncc commented on src/wp-admin/includes/class-wp-debug-data.php
> +					'value' => wp_get_font_dir()['path'],
```suggestion
					'value' => wp_get_font_dir()['basedir'],
```

2024-05-27 22:38 UTC, peterwilsoncc commented on src/wp-admin/includes/class-wp-debug-data.php
> +			'fonts_size'     => wp_get_font_dir()['path'],
```suggestion
			'fonts_size'     => wp_get_font_dir()['basedir'],
```

2024-06-03 09:50 UTC, audrasjb commented
I committed the changes suggested by @peterwilsoncc directly to the PR.

2024-06-03 16:44 UTC, audrasjb approved these changes

2024-06-03 16:56 UTC, audrasjb commented
Committed in https://core.trac.wordpress.org/changeset/58299

2024-06-03 16:56 UTC, closed without merging