Indicate submenu item level in admin nav menu editor and customizer nav menu editor
WordPress/wordpress-develop pull request #6318
Opened 2024-03-25 19:57 UTC by Rcreators

Trac ticket: https://core.trac.wordpress.org/ticket/60673

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-06-02 23:56 UTC, joedolson requested changes
This is in pretty good shape, and the remaining items are fairly small. The functionality works pretty well. It may still be possible to get it in, but it's getting pretty late. However, it seems like something that can definitely be ready for 6.7, if it doesn't make this release.

2024-06-02 23:56 UTC, joedolson commented on src/wp-admin/includes/class-walker-nav-menu-edit.php
> +							__( 'Edit menu item' ),
This looks like an unintentional change; remove it.

2024-06-02 23:56 UTC, joedolson commented on src/wp-admin/nav-menus.php
> +	'subMenuFocus'            => __( 'Edit %1$s (%2$s, sub-item %3$d of %4$d of %5$s)' ),
Change to `under %5$s`. Better English grammar, makes the string easier to parse while placeholders are present.

2024-06-02 23:56 UTC, joedolson commented on src/wp-admin/nav-menus.php
> +	'subMenuMoreDepthFocus'   => __( 'Edit %1$s (%2$s, sub-item %3$d of %4$d of %5$s, level %6$d)' ),
Change to `under %5$s`. Better English grammar, makes the string easier to parse while placeholders are present.

2024-06-02 23:56 UTC, joedolson commented on src/wp-includes/class-wp-customize-nav-menus.php
> +			'subMenuFocus'            => __( 'Edit %1$s (%2$s, sub-item %3$d of %4$d of %5$s)' ),
Change to `under %5$s`. Better English grammar, makes the string easier to parse while placeholders are present.

2024-06-02 23:56 UTC, joedolson commented on src/wp-includes/class-wp-customize-nav-menus.php
> +			'subMenuMoreDepthFocus'   => __( 'Edit %1$s (%2$s, sub-item %3$d of %4$d of %5$s, level %6$d)' ),
Change to `under %5$s`. Better English grammar, makes the string easier to parse while placeholders are present.

2024-06-02 23:56 UTC, joedolson commented on src/wp-includes/customize/class-wp-customize-nav-menu-item-control.php
> +							printf( __( 'Edit %1$s (%2$s, sub-item %3$d of %4$d of %5$s)' ), '{{ data.title || data.original_title || wp.customize.Menus.data.l10n.untitled }}', '{{ data.item_type_label }}', '', '', '' );
Change to `under %5$s`. Better English grammar, makes the string easier to parse while placeholders are present.

Also update the translator comment.

2024-06-02 23:56 UTC, joedolson commented on src/wp-includes/customize/class-wp-customize-nav-menu-item-control.php
> +						printf( __( 'Edit %1$s (%2$s, %3$d of %4$d)' ), '{{ data.title || data.original_title || wp.customize.Menus.data.l10n.untitled }}', '{{ data.item_type_label }}', '', '' );
Update the translator comment.

2024-06-02 23:56 UTC, joedolson commented on src/wp-includes/customize/class-wp-customize-nav-menu-item-control.php
> +							printf( __( 'Edit %1$s (%2$s, sub-item %3$d of %4$d of %5$s, level %6$s)' ), '{{ data.title || data.original_title || wp.customize.Menus.data.l10n.untitled }}', '{{ data.item_type_label }}', '
Change to `under %5$s`. Better English grammar, makes the string easier to parse while placeholders are present.

Also update the translator comment.

2024-06-02 23:56 UTC, joedolson commented on src/js/_enqueues/wp/customize/nav-menus.js
> +		 * Set up initial state of accessibility for menu items.
Make this more explicit: it's setting up the initial state of the screen reader accessibility information for menu items. Setting up the state of accessibility implies it's doing things outside the parameters that it's actually handling.

2024-06-03 12:50 UTC, afercia commented on src/js/_enqueues/lib/nav-menu.js
> +				totalMenuItems = primaryItems.length;
Why this change? I think we should keep the comma? unless I'm missing something

2024-06-03 12:56 UTC, afercia commented on src/js/_enqueues/lib/nav-menu.js
> +				totalSubItems = subItems.length;
Why this line ends with a semicolon? I think we should use a comma? unless I'm missing something

2024-06-03 13:03 UTC, afercia commented on src/js/_enqueues/lib/nav-menu.js
> +				if( depth < 2 ) {
There should be a space after the `if`

2024-06-03 13:05 UTC, afercia commented on src/js/_enqueues/lib/nav-menu.js
> +					api.refreshAdvancedAccessibilityOfItem( ui.item.find('a.item-edit') );
There should be spaces inside the parenthesis: `( 'a.item-edit' )`

2024-06-03 13:06 UTC, afercia commented on src/js/_enqueues/wp/customize/nav-menus.js
> +		 *
This line is unnecessary.

2024-06-03 13:07 UTC, afercia commented on src/js/_enqueues/wp/customize/nav-menus.js
> +		 * It's setting up the initial state of the screen reader accessibility information for menu items.
It is preferred to start function descriptions with a third person verb e.g. 'Sets up ...'.

2024-06-03 13:08 UTC, afercia commented on src/js/_enqueues/wp/customize/nav-menus.js
> +			menu.on( 'mouseenter.refreshAccessibility focus.refreshAccessibility touchstart.refreshAccessibility' , '.menu-item' , function(){
Spaces before the commas should be removed. (I understand this code was copied from the existing implementation but yes the spaces should be removed)

2024-06-03 13:15 UTC, afercia commented on src/js/_enqueues/wp/customize/nav-menus.js
> +				totalMenuItems = primaryItems.length;
Same as above: why a semicolon?

2024-06-03 13:15 UTC, afercia commented on src/js/_enqueues/wp/customize/nav-menus.js
> +				totalSubItems = subItems.length;
Same as above: why a semicolon?

2024-06-03 13:16 UTC, afercia commented on src/js/_enqueues/wp/customize/nav-menus.js
> +				if( depth < 2 ) {
There should be a space after the `if`

2024-06-03 13:17 UTC, afercia commented on src/js/_enqueues/wp/customize/nav-menus.js
> +			$this.find('.screen-reader-text').text( title );
There should be spaces inside the parenthesis.

2024-06-03 13:19 UTC, afercia commented on src/wp-admin/nav-menus.php
> +	'menuFocus'               => __( 'Edit %1$s (%2$s, %3$d of %4$d)' ),
In `4: Total Item` the word Item should start with lowercase and end with a period.

2024-06-03 13:20 UTC, afercia commented on src/wp-admin/nav-menus.php
> +	/* translators: 1: Item name, 2: Item type, 3: Item index, 4: Total Items */
In `4: Total Items` the word Items should start with lowercase and end with a period.

2024-06-03 13:21 UTC, afercia commented on src/wp-admin/nav-menus.php
> +	/* translators: 1: Item name, 2: Item type, 3: Item index, 4: Total Items, 5: Item Parent. */
In `4: Total Items, 5: Item Parent`, Itmes and Parent should be lowercase.

2024-06-03 13:22 UTC, afercia commented on src/wp-admin/nav-menus.php
> +	/* translators: 1: Item name, 2: Item type, 3: Item index, 4: Total Items, 5: Item Parent, 6: Item Depth */
In `4: Total Items, 5: Item Parent, 6: Item Depth`, Items, Parend and Depth should be lowercase and hte comment should end with a period.

2024-06-03 13:23 UTC, afercia commented on src/wp-includes/class-wp-customize-nav-menus.php
> +			/* translators: 1: Item name, 2: Item type, 3: Item index, 4: Total Items, 5: Item Parent. */
Same as above

2024-06-03 13:23 UTC, afercia commented on src/wp-includes/class-wp-customize-nav-menus.php
> +			/* translators: 1: Item name, 2: Item type, 3: Item index, 4: Total Items, 5: Item Parent, 6: Item Depth */
Same as above

2024-06-03 13:24 UTC, afercia commented on src/wp-includes/customize/class-wp-customize-nav-menu-item-control.php
> +						/* translators: 1: Title of a menu item, 2: Type of a menu item */
Missing period at the end of translator comment

2024-06-03 13:24 UTC, afercia commented on src/wp-includes/customize/class-wp-customize-nav-menu-item-control.php
> +							/* translators: 1: Title of a menu item, 2: Type of a menu item, 3: Depth of a menu item */
Missing period at the end of translator comment

2024-06-03 13:30 UTC, Rcreators commented
@afercia All changes have been amended.

2024-06-03 13:42 UTC, afercia requested changes
Please see inline comments

2024-06-03 13:44 UTC, Rcreators commented
> Please see inline comments

All the requested changes are pushed.

2024-06-03 14:58 UTC, afercia commented
Thanks for addressing the coding standards points I raised @Rcreators 
I understand part of this PR is code copied from already existing code there's some more occurrences of missing spaces between parehthesis and single quote `('` or `')` that would be nice to fix if possible. Thanks!
Other than that, I would leave functional and final review to @joedolson

2024-06-03 20:33 UTC, joedolson commented
In r58306

2024-06-03 20:33 UTC, closed without merging