Adding a new function named user_can_for_blog(), and unit tests for it.
WordPress/wordpress-develop pull request #6418
Opened 2024-04-19 22:49 UTC by Rajinsharwar

Adding a new function named user_can_for_blog(), and unit tests for it.

Trac ticket: https://core.trac.wordpress.org/ticket/45197

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-05-13 16:10 UTC, johnbillion requested changes
I've added some more tests for this change and the tests are failing. The function is incorrectly returning true when checking the `edit_posts` capability for a user who does not have access to the site that's being checked.

I'm not yet sure if this is a problem with the tests or the function.

2024-05-13 16:49 UTC, johnbillion commented
@Rajinsharwar @JJJ Any thoughts on what's up here? The `test_user_can_for_blog()` test is failing when it checks the `edit_posts` capability of a user on a site that the user doesn't belong to. The result is incorrectly `true` instead of `false`.

2024-05-13 18:37 UTC, Rajinsharwar commented on tests/phpunit/tests/user/capabilities.php
> +		$author = self::$users['author'];
```suggestion
		$author = self::factory()->user->create( array( 'role' => 'author' ) );
```

2024-05-13 20:11 UTC, Rajinsharwar commented
Fixed @johnbillion, used the user_can() instead in the function, the previous method didn't check for the current_blog I bielive.

2024-09-30 10:17 UTC, johnbillion approved these changes

2024-09-30 11:04 UTC, johnbillion commented
https://core.trac.wordpress.org/changeset/59123

2024-09-30 11:04 UTC, closed without merging