Html5lib tests: Fix rexet of context element
WordPress/wordpress-develop pull request #6464
Opened 2024-04-30 16:15 UTC by sirreal

Trac ticket: 

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-04-30 16:43 UTC, costdev requested changes

2024-04-30 16:43 UTC, costdev commented on tests/phpunit/tests/html-api/wpHtmlProcessorHtml5lib.php
>  	 * @param string $html             Given test HTML.
```suggestion
	 * @param string|null $fragment_context Context element in which to parse HTML, such as BODY or SVG.
	 * @param string      $html             Given test HTML.
```

2024-04-30 20:20 UTC, costdev approved these changes
Thanks @sirreal, that's all from me on this. I'll leave the rest to @dmsnell as someone with more familiarity of the context (pun intended) :slightly_smiling_face:

2024-04-30 21:04 UTC, dmsnell approved these changes
I'm guessing this was skipping tests because it didn't try the ones that were in `<body>` context? but the others are not in `<body>`?

Looks fine. Thanks for your help, both of you.

2024-04-30 21:05 UTC, dmsnell commented
ah. there's more of a description in the Trac ticket. feel free to duplicate descriptions 😉

2024-05-01 23:45 UTC, closed without merging

2024-05-01 23:45 UTC, dmsnell commented
Merged in [[58072]](https://core.trac.wordpress.org/changeset/58072)
https://github.com/wordpress/wordpress-develop/commit/a8d5879867e03d62e3a91569aa18c84142e47c62