Improve theme file caching in class-wp-theme-json.php
WordPress/wordpress-develop pull request #6707
Opened 2024-06-02 21:20 UTC by spacedmonkey

Minor changes have been made to class-wp-theme-json.php to better cache the theme files. This includes adding an 'update_cache' functionality that sets 'str_start_with' and 'str_start_with_cache', and removing redundant checks for empty or non-numerical values. These improvements aim to optimize performance by updating cache when necessary.

Trac ticket:  https://core.trac.wordpress.org/ticket/59595

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-06-04 00:41 UTC, joemcgill commented
Thanks @spacedmonkey. I did some profiling of this change against trunk and it does reduce the number of `str_starts_with` calls quite drastically.

**Trunk**
<img width="1512" alt="image" src="https://github.com/WordPress/wordpress-develop/assets/801097/aa82a8b0-7b42-45bf-a602-8c704331704d">

**This PR**
<img width="1510" alt="image" src="https://github.com/WordPress/wordpress-develop/assets/801097/eeac66c2-5fca-4cad-86a8-b9124b373d66">

That said, [the PR we've been working on ](https://github.com/WordPress/wordpress-develop/pull/6392#issuecomment-2146264128) has a bigger impact by reducing the number of calls to this method altogether. It may be worth combining both approaches to maximize the benefit, but I'd like to prioritize getting #6392 into trunk first as it has the biggest potential impact.

2024-06-13 17:13 UTC, joemcgill commented
@spacedmonkey are ok to close this in favor of https://github.com/WordPress/gutenberg/pull/62522?

2024-06-20 10:14 UTC, ellatrix commented
@joemcgill This is the backport PR? We'll need both?

2024-06-20 13:44 UTC, joemcgill commented
@ellatrix and @spacedmonkey, it's fine to use this PR as the backport from https://github.com/WordPress/gutenberg/pull/62522. At present, it's not the same code though, so this will need to be updated once the GB PR is finalized.

2024-06-20 15:22 UTC, adamsilverstein commented on src/wp-includes/class-wp-theme-json.php
> +				for ( $i = 0; $i < count( $value_path ); $i++ ) {
is this bit faster than the call to `implode`?

2024-06-20 15:22 UTC, adamsilverstein approved these changes
nice!

2024-06-20 16:59 UTC, joemcgill requested changes
Marking as not ready until after this has been updated with the approach from https://github.com/WordPress/gutenberg/pull/62522 (see [related comment](https://github.com/WordPress/gutenberg/pull/62522#issuecomment-2180309004)).

2024-06-24 16:51 UTC, joemcgill commented
@spacedmonkey, I've approved the related GB PR. Once this PR is updated to reflect the latest changes, I'm happy to give another review.

2024-06-25 08:28 UTC, spacedmonkey commented
Closing in favour of https://github.com/WordPress/wordpress-develop/pull/6895

2024-06-25 08:28 UTC, closed without merging