31354/change structure for inputs
WordPress/wordpress-develop pull request #6730
Opened 2024-06-04 17:34 UTC by jwgoedert

Nested child elements in list items to create visual hierarchy, moved input fields to end of labels for screen reader usability 
Trac ticket: 
https://core.trac.wordpress.org/attachment/ticket/31354/

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-06-07 15:35 UTC, joedolson requested changes
Some JS-related code left in.

2024-06-07 15:35 UTC, joedolson commented on src/wp-admin/options-discussion.php
> +<div id="aria-live-region" aria-live="polite" class="screen-reader-text"></div>
Remove this; it's a stray leftover from your previous patch.

2024-06-10 07:08 UTC, jwgoedert reviewed
Removed leftover js code.

2024-10-01 19:43 UTC, joedolson approved these changes

2024-10-03 21:29 UTC, joedolson commented
in r59160

2026-02-08 19:32 UTC, joedolson commented
Issue was closed in https://core.trac.wordpress.org/changeset/59160

2026-02-08 19:32 UTC, closed without merging