feat: optimize wp_count_posts() query for performance improvement.
WordPress/wordpress-develop pull request #6774
Opened 2024-06-11 10:32 UTC by snehapatil2001

## Ticket
https://core.trac.wordpress.org/ticket/61097

## Description

- This **PR** proposes optimization to the `wp_count_posts()` function to improve query performance, especially for users without the `read_private_posts` capability.
- The current implementation of the function's query includes inefficient conditions, leading to slow queries, particularly in databases with millions of records.
- The proposed solution involves replacing the existing query logic with an optimized `UNION ALL` query, which separates the selection of non-private posts and private posts authored by the current user.
- Additionally, the PR ensures backward compatibility by maintaining the original logic when the conditions for optimization are not met.

## Changes Made
- Replaced the existing query logic in the `wp_count_posts()` function with an optimized `UNION ALL` query.
- Incorporated conditional logic to use the optimized query only when necessary, falling back to the original logic otherwise.

## Context
The `wp_count_posts()` function is critical for counting posts of a specific type in WordPress. However, the current implementation suffers from performance issues due to inefficient query conditions. By optimizing the query with a `UNION ALL` approach, this PR aims to significantly improve performance, especially for large datasets.

2024-06-25 17:16 UTC, rbcorrales commented
Referencing this PR on a new ticket focused on the performance of this query:
https://core.trac.wordpress.org/ticket/61502

2024-06-25 20:56 UTC, pbearne requested changes

2024-06-25 20:56 UTC, pbearne commented on src/wp-includes/post.php
> +	$query = $wpdb->prepare("SELECT post_status, COUNT(*) AS num_posts FROM {$wpdb->posts} WHERE post_type = %s", $type);
```suggestion
	$query = $wpdb->prepare( "SELECT post_status, COUNT(*) AS num_posts FROM {$wpdb->posts} WHERE post_type = %s", $type );
```

2024-06-25 20:56 UTC, pbearne commented on src/wp-includes/post.php
> +			$query = $wpdb->prepare("
```suggestion
			$query = $wpdb->prepare(
			"
```

2024-06-25 20:56 UTC, pbearne commented on src/wp-includes/post.php
> +			", $type, $type, get_current_user_id());
```suggestion
			", 
			$type, 
			$type, 
			get_current_user_id()
			);
```

2024-06-26 04:56 UTC, snehapatil2001 commented
@pbearne Fixed the phpcs errors.

2024-07-02 11:26 UTC, snehapatil2001 commented
@pbearne Do I need to make any more changes??

2025-09-21 05:26 UTC, closed without merging