Fix aria-haspopup usage in the admin menu.
WordPress/wordpress-develop pull request #6818
Opened 2024-06-13 14:29 UTC by afercia

Trac ticket: https://core.trac.wordpress.org/ticket/43095 

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-06-17 07:40 UTC, joedolson requested changes

2024-06-17 07:40 UTC, joedolson commented on src/js/_enqueues/admin/common.js
> +				$( this ).removeAttr( 'aria-haspopup' ):
Switch from colon to semicolon

2024-06-17 09:40 UTC, afercia commented on src/js/_enqueues/admin/common.js
> +				$( this ).removeAttr( 'aria-haspopup' ):
Fixed. My bad vision 😞

2024-06-17 17:03 UTC, joedolson approved these changes
Looks good!

2024-06-20 20:19 UTC, joedolson commented
In [r58449]

2024-06-20 20:19 UTC, closed without merging