Updated doc for `admin_bar_menu`
WordPress/wordpress-develop pull request #7222
Opened 2024-08-21 10:38 UTC by narenin

Trac ticket: https://core.trac.wordpress.org/ticket/61738

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-08-28 16:06 UTC, sabernhardt requested changes
Thanks for the PR!

1. I suggested an edit for the `admin_bar_menu` hook description.
2. For `wp_admin_bar_render()`, I would suggest simply removing the incorrect sentence instead of replacing it. I also added a comma before "which" and adjusted the line length after removing the sentence:
```
 * It includes the {@see 'admin_bar_menu'} action, which should be used to hook in and
 * add new menus to the admin bar. This also gives you access to the `$post` global,
 * among others.
```
3. The `wp_before_admin_bar_render` hook probably should explain more in the docblock, but the [More Information](https://developer.wordpress.org/reference/hooks/wp_before_admin_bar_render/#more-information) section might explain it better than I can.

2024-08-28 16:06 UTC, sabernhardt commented on src/wp-includes/admin-bar.php
> +	 * This is the hook used to add, remove, or manipulate admin bar items. The recommended hook instead of this is wp_before_admin_bar_render.
```suggestion
	 * This hook can add, remove, or manipulate admin bar items. The priority
	 * determines the placement for new items, and changes to existing items
	 * would require a high priority. To remove or manipulate existing nodes
	 * without a specific priority, use `wp_before_admin_bar_render`.
```

This should be the preferred hook for adding items, and it still can modify or remove items if done with a proper priority level.

2024-08-29 05:23 UTC, narenin commented on src/wp-includes/admin-bar.php
> +	 * This is the hook used to add, remove, or manipulate admin bar items. The recommended hook instead of this is wp_before_admin_bar_render.
@sabernhardt Thanks for the detailed feedback. I have implemented the suggestions, please review the same.

2024-09-03 15:18 UTC, hellofromtonya commented on src/wp-includes/admin-bar.php
> +	 * This is the hook used to add, remove, or manipulate admin bar items. The recommended hook instead of this is wp_before_admin_bar_render.
Checked and the requested changes are now implemented in the PR ✅

2024-09-03 15:35 UTC, sabernhardt commented on src/wp-includes/admin-bar.php
> +	 * This is the hook used to add, remove, or manipulate admin bar items. The recommended hook instead of this is wp_before_admin_bar_render.
Thanks for updating the `admin_bar_menu` docblock.

Could you also remove the sentence about the "most optimal point" in `wp_admin_bar_render()` and limit the line length to 80 characters?
https://github.com/WordPress/wordpress-develop/blob/b50a842d4889f2e635b161f4c2d14d078651bf28/src/wp-includes/admin-bar.php#L64-L67

```
 * It includes the {@see 'admin_bar_menu'} action, which should be used to hook in and
 * add new menus to the admin bar. This also gives you access to the `$post` global,
 * among others.
```

2024-09-03 16:45 UTC, hellofromtonya commented on src/wp-includes/admin-bar.php
> +	 * This is the hook used to add, remove, or manipulate admin bar items. The recommended hook instead of this is wp_before_admin_bar_render.
Done in commit https://github.com/WordPress/wordpress-develop/pull/7222/commits/cb0c76490cb7b3b7af11af7d9d06459d83488b90 ✅

2024-09-03 16:46 UTC, hellofromtonya commented
@sabernhardt @joedolson can you do another review please? Is it ready for commit?

2024-09-03 16:50 UTC, sabernhardt approved these changes
Looks good

2024-09-03 18:02 UTC, joedolson approved these changes

2024-09-03 19:59 UTC, hellofromtonya commented
Thank you everyone for your contributions 🌟 This PR was committed via https://core.trac.wordpress.org/changeset/58978.

2024-09-03 19:59 UTC, closed without merging