HttpOnly flags added to setcookie() for `TEST_COOKIE` and `wp-postpas…
WordPress/wordpress-develop pull request #7240
Opened 2024-08-26 15:50 UTC by Kevinlearynet

When running WordPress at a regulated organization security audits routinely flag security issues when PHP creates cookies without the `HttpOnly` argument set to true. While this can't be done for cookies that are used client-side, it can be safely enabled for these server-side only cookies.

* `TEST_COOKIE`
* `wp-postpass_{HASH}`

I've tested this on the latest WordPress trunk with a server stack that mirrors Kinsta and WPEngine. This stack passes 100% of Site Health checks, and is running on the following:

```
Darwin 23.6.0 x86_64
nginx/1.25.5
PHP 8.3.7 (support 64bit values)
Zend OPcache v8.3.7
mysql 8.3.0 / mysqlnd 8.3.7
8.7.1 (SecureTransport) OpenSSL/3.3.0
```

Originally reported by [earthman100](https://core.trac.wordpress.org/query?status=!closed&reporter=earthman100)

Trac ticket: https://core.trac.wordpress.org/ticket/61322

2024-08-29 18:00 UTC, Kevinlearynet commented
Are these test actions reliable? 

I re-triggered tests with a `--no-commit` that changed nothing, and I see completely different results?

1. [First test run](https://github.com/WordPress/wordpress-develop/actions/runs/10562951240) shows 10 errors with specific PHP versions and MySQL/MariaDB combinations
1. [First test run](https://github.com/WordPress/wordpress-develop/actions/runs/10617733758) shows 7 entirely different errors related to `SCRIPT_DEBUG` and applications-passwords.test.js

2025-01-20 15:20 UTC, johnbillion commented
Not sure what was up with those performance tests but I merged the `trunk` branch into this and they seem pretty stable again.

2025-01-21 01:13 UTC, johnbillion requested changes

2025-01-21 01:13 UTC, johnbillion commented on src/wp-login.php
> +		setcookie( 'wp-postpass_' . COOKIEHASH, $hasher->HashPassword( wp_unslash( $_POST['post_password'] ) ), $expire, COOKIEPATH, COOKIE_DOMAIN, $secure, true );
I support setting the test cookie and `wp_lang` cookie to HttpOnly, but I don't think it's safe to do it for the post password cookie. There's too high an opportunity for it to break either JavaScript that reads the value of the cookie, or Ajax handlers in PHP that read the value of the cookie, both of which would no longer be able to do so.

Let's revert this change but keep the other changes.

2025-01-21 13:18 UTC, closed without merging

2025-01-21 13:44 UTC, Kevinlearynet commented
@johnbillion 

Thanks! Glad the unit tests work on trunk w/o issues