Twenty Eleven: Remove IE specific checks
WordPress/wordpress-develop pull request #7411
Opened 2024-09-23 05:58 UTC by sabernhardt

Twenty Eleven changes:
- Removes IE conditional code and HTML5 Shiv from `header.php`
- Removes IE7 and IE8 sections from `style.css` and `rtl.css`
- Removes `width` from `editor-style.css`
- Removes extra `clip` syntax from `functions.php` and `style.css`
- Removes `filter` from `style.css` and `dark.css`
- Removes IE8 `width: auto` rule for full-size and large-size images in `style.css`

[Trac 58836](https://core.trac.wordpress.org/ticket/58836)

Props: neychok

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-12-12 07:26 UTC, aristath approved these changes

2025-10-16 20:44 UTC, joedolson requested changes
Should also remove `-ms-linear-gradient`, which was dropped in IE 10, adding support for `linear-gradient`. https://caniuse.com/?search=linear-gradient

2025-10-16 20:44 UTC, joedolson commented on src/wp-content/themes/twentyeleven/colors/dark.css
>  	background: -ms-linear-gradient(top, rgba(0,0,0,0) 0%,rgba(0,0,0,1) 100%); /* IE10+ */
`-ms-linear-gradient` was also removed in IE10

2025-10-16 20:44 UTC, joedolson commented on src/wp-content/themes/twentyeleven/style.css
>  	background: -ms-linear-gradient(top, rgba(255,255,255,0) 0%,rgba(255,255,255,1) 100%); /* IE10+ */
`-ms-linear-gradient` removed in IE10

2025-10-17 17:46 UTC, joedolson approved these changes

2025-10-17 21:17 UTC, sabernhardt commented
Committed in r60960

2025-10-17 21:17 UTC, closed without merging