Twenty Twelve: Remove IE specific checks
WordPress/wordpress-develop pull request #7412
Opened 2024-09-23 05:58 UTC by sabernhardt

Twenty Twelve changes:
- Registers `ie.css` without enqueuing it
- Removes IE conditional code and HTML5 Shiv from `header.php`
- Removes `width` hack from `editor-style.css`
- Removes extra `clip` syntax from `custom-header.php`

[Trac 58836](https://core.trac.wordpress.org/ticket/58836)

Props: metodiew

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2025-10-16 20:46 UTC, joedolson requested changes
Remove the conditional data flag.

2025-10-16 20:46 UTC, joedolson commented on src/wp-content/themes/twentytwelve/functions.php
>  	$wp_styles->add_data( 'twentytwelve-ie', 'conditional', 'lt IE 9' );
Following r60948, we should remove the conditional flag.

2025-10-16 20:56 UTC, sabernhardt commented on src/wp-content/themes/twentytwelve/functions.php
>  	$wp_styles->add_data( 'twentytwelve-ie', 'conditional', 'lt IE 9' );
I might take another step and remove the sources:
```suggestion
	wp_register_style( 'twentytwelve-ie', false, array( 'twentytwelve-style' ) );
```

T13, T15 and T17 would need the same, and I could replace the files' contents with a short comment (for all the themes).

2025-10-17 17:47 UTC, joedolson commented on src/wp-content/themes/twentytwelve/functions.php
>  	$wp_styles->add_data( 'twentytwelve-ie', 'conditional', 'lt IE 9' );
That makes sense to me.

2025-10-17 17:50 UTC, joedolson approved these changes

2025-10-17 21:18 UTC, sabernhardt commented
Committed in r60961

2025-10-17 21:18 UTC, closed without merging