Twenty Fourteen: Remove IE specific checks
WordPress/wordpress-develop pull request #7414
Opened 2024-09-23 06:00 UTC by sabernhardt

Twenty Fourteen changes:
- Registers `ie.css` without enqueuing it
- Removes IE conditional code and HTML5 Shiv from `header.php`
- Removes extra `clip` syntax from `custom-header.php`

[Trac 58836](https://core.trac.wordpress.org/ticket/58836)

Props: metodiew

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2025-10-16 20:47 UTC, joedolson requested changes
Remove conditional flag.

2025-10-16 20:47 UTC, joedolson commented on src/wp-content/themes/twentyfourteen/functions.php
>  	wp_style_add_data( 'twentyfourteen-ie', 'conditional', 'lt IE 9' );
Remove conditional flag following r60948

2025-10-17 17:52 UTC, joedolson approved these changes

2025-10-17 21:21 UTC, sabernhardt commented
Committed in r60963

2025-10-17 21:21 UTC, closed without merging