Twenty Sixteen: Remove IE specific checks
WordPress/wordpress-develop pull request #7416
Opened 2024-09-23 06:05 UTC by sabernhardt

Twenty Sixteen changes:
- Registers `ie.css` without enqueuing it
- Removes IE conditional code and HTML5 Shiv from `header.php`
- Removes extra `clip` syntax from `custom-header.php`

[Trac 58836](https://core.trac.wordpress.org/ticket/58836)

Props: metodiew

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2025-10-16 20:48 UTC, joedolson requested changes
Remove conditional flags.

2025-10-16 20:48 UTC, joedolson commented on src/wp-content/themes/twentysixteen/functions.php
>  	wp_style_add_data( 'twentysixteen-ie', 'conditional', 'lt IE 10' );
Remove all conditional flags following r60948

2025-10-17 16:49 UTC, sabernhardt commented on src/wp-content/themes/twentysixteen/functions.php
>  	wp_style_add_data( 'twentysixteen-ie', 'conditional', 'lt IE 10' );
That gives a better opportunity to register the handles as a group, under the same comment.

2025-10-17 17:54 UTC, joedolson approved these changes

2025-10-17 18:50 UTC, sabernhardt commented on src/wp-content/themes/twentysixteen/functions.php
> +	wp_register_script( 'twentysixteen-html5', false, array() );
The empty array is default for dependencies.

```suggestion
	wp_register_script( 'twentysixteen-html5', false );
```

2025-10-17 21:27 UTC, sabernhardt commented
Committed in r60965

2025-10-17 21:27 UTC, closed without merging