Aria-label Updated for Pagination
WordPress/wordpress-develop pull request #7448
Opened 2024-09-27 11:56 UTC by tirth-doshi-techno

I have updated get_the_posts_pagination() function to get the post type name and use it in the aria_label for better accessibility text as described in ticket.

**Before**

![Screenshot from 2024-09-27 16-56-48](https://github.com/user-attachments/assets/ebe97048-571d-425a-bf2f-3505c789af43)

**After**

1. Post

![Screenshot from 2024-09-27 17-17-26](https://github.com/user-attachments/assets/d96f2943-3bca-4e16-85be-38c56ab95ef0)

2. Custom Post Type

![Screenshot from 2024-09-27 17-26-02](https://github.com/user-attachments/assets/f3cbb4ba-9dc9-4d22-a1e9-334aa6341fe0)

Trac ticket: https://core.trac.wordpress.org/ticket/54260

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-09-27 13:26 UTC, sabernhardt requested changes
Thanks for working on this!

I found a few changes to make:
1. To update the documentation of both functions, include "pagination" in the [default value for the `aria_label` parameter](https://github.com/sabernhardt/wordpress-develop/pull/37/files#diff-b4070c4f94ed08fdcc78182a9941e3ff552a458744bcfb9eb33713c47d93fb02R2935).
2. Make "Posts" translatable.
3. Add translator comments above each line with a placeholder.

2024-09-27 13:26 UTC, sabernhardt commented on src/wp-includes/link-template.php
> +				'aria_label'         => sprintf( __( '%s pagination' ), $post_type_name ),
```suggestion
				/* translators: %s: Post type name. */
				'screen_reader_text' => sprintf( __( '%s navigation' ), $post_type_name ),
				/* translators: %s: Post type name. */
				'aria_label'         => sprintf( __( '%s pagination' ), $post_type_name ),
```

Add [translator comments](https://github.com/WordPress/wordpress-develop/blob/d23f60f5b77de0d116b2abed3094989ae15874c3/src/wp-includes/post.php#L2101-L2102) to explain the `%s` placeholder.

2024-09-27 13:26 UTC, sabernhardt commented on src/wp-includes/link-template.php
> +			$post_type_name = 'Posts';
```suggestion
			$post_type_name = __( 'Posts' );
```

The "Posts" text should be translatable.

2024-09-28 19:58 UTC, joedolson commented
In addition, I changed the default `screen_reader_text` parameter to '%s pagination'. This makes the two strings match, which would otherwise be confusing. 

This doesn't result in any string churn, since the Posts Navigation text will still be the default passed in non-paginated patterns.

2024-09-28 22:41 UTC, joedolson commented
Removed the Posts string, translator comments, and reference to get_queried_object. That's my fault; I lead people down an invalid path, because we can't actually do that, as nice as it would be.

2024-09-28 23:35 UTC, joedolson commented
In r59113

2024-09-28 23:35 UTC, closed without merging