made changes for comment rest api to support with block commenting
WordPress/wordpress-develop pull request #7488
Opened 2024-10-03 12:55 UTC by rishishah-multidots

### Pull Request Description
Title: Modify Comment REST API to Support Block Comments

Overview: This pull request enhances the WordPress Comment REST API by adding support for [block comments](https://github.com/WordPress/gutenberg/pull/60622). This functionality aims to improve rest API add comment functionality to support the block commenting feature.

### Changes Made:

- Updated the Comment REST API to accept and process block comment type.
- Process comment status if a logged-in user adds block comment then it will not approved automatically.

### Why This Matters:

- As of now custom comment type is now allowed in the comment rest API but we can add it through `wp_insert_comment`
- If any logged-in user ports a comment then it will automatically approve and add the comment in the database with `comment_approved` as `1`.

### Related Tickets:

[Ticket #60622](https://github.com/WordPress/gutenberg/pull/60622): Discussion on block comments feature.

2024-10-15 07:38 UTC, ellatrix commented
@TimothyBJacobs do these changes look good to you? Thanks. :)

2025-01-16 22:52 UTC, peterwilsoncc requested changes
I've added a comment inline re: allowing the submission of unsupported comment types. 

If block comments are to be a thing, then they should build upon the existing `comment` rather than be a new type.

2025-01-16 22:52 UTC, peterwilsoncc commented on src/wp-includes/rest-api/endpoints/class-wp-rest-comments-controller.php
> -
I don't think this should be removed.

As the change to the unit tests show, it allows the addition of comment types to the database that WordPress is unable to support. This is problematic for a number of reasons, primarily because it fills the databse with junk, secondly because plugins may not expect the data and throw a fatal error as a result.

2025-01-16 23:10 UTC, peterwilsoncc commented
> If block comments are to be a thing, then they should build upon the existing `comment` rather than be a new type.

Ignore this part of my comment, I made an assumption about what was meant by block comments that was incorrect.

For the block comments being introduced, then the new comment type should be registered.

2025-08-07 13:55 UTC, t-hamano commented
The Block-level comments functionality is still an experimental feature in the Gutenberg plugin, so there's no need to backport it to core. In fact, the backport changelog has been removed.

https://github.com/WordPress/gutenberg/pull/68846

I'm sorry, but let me close this PR. We need to continue to iterate on the Gutenberg plugin and create a backport PR once we have decided to "stabilize" the feature.

2025-08-07 13:55 UTC, closed without merging