WP_Query: sort more arrays to improve cache hits.
WordPress/wordpress-develop pull request #7497
Opened 2024-10-04 00:14 UTC by peterwilsoncc

Lighter touch alternative to https://github.com/WordPress/wordpress-develop/pull/5347

Trac ticket: https://core.trac.wordpress.org/ticket/59516

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-12-10 19:10 UTC, kt-12 commented
@peterwilsoncc I was concerned that sorting might effect the order of the output too, looks like it doesn't. Can we also ensure, https://core.trac.wordpress.org/ticket/59492#comment:3  is handled (if not), please. If there is only one element in the array it should be converted into string. I remember getting that scenario from a live site, but I can't recall the details.

2024-12-10 22:26 UTC, peterwilsoncc commented
> I was concerned that sorting might effect the order of the output too, looks like it doesn't. 

The order should only have an effect for items that can be used for the orderby clause, for example `post__in`. It's fine to sort for the where clause so the key differs only in the instances where the item is used for ordering.

> Can we also ensure, https://core.trac.wordpress.org/ticket/59492#comment:3 is handled (if not), please. If there is only one element in the array it should be converted into string. I remember getting that scenario from a live site, but I can't recall the details.

My recollection is that in some instances the use of a string vs an array can result in a different where clause beyond just the use of `=` vs `IN`. At the very least, I know it is complicated so I'm trying to get something lighter touch in initially so it's possible to spend additional time comparing the effect of passing a string or an array.

2025-01-19 22:25 UTC, peterwilsoncc commented on tests/phpunit/tests/query/cacheResults.php
> +			),
These two are failing. `cat` is normalised in the generated SQL query but not in the arguments passed to `::generate_cache_key()`.

I can't figure out why as the query vars are passed to `::parse_term_query()` by reference so sorting it there should work. @joemcgill Can you see what I am missing?

2025-01-22 01:26 UTC, peterwilsoncc commented on tests/phpunit/tests/query/cacheResults.php
> +			),
> These two are failing. `cat` is normalised in the generated SQL query but not in the arguments passed to `::generate_cache_key()`.
> 
> I can't figure out why as the query vars are passed to `::parse_term_query()` by reference so sorting it there should work. @joemcgill Can you see what I am missing?

nvm, the tests were testing the wrong thing so I've started testing the cache key generated by WP_Query in bc246274c3ceb7a3204ea113216919177368d9e4

2025-01-28 04:14 UTC, spacedmonkey approved these changes, later dismissed
LGTM. Reviewed all parameters and this PR look solid to me.

2025-01-28 23:07 UTC, peterwilsoncc commented
@spacedmonkey I've pushed a few additional tests and bugs they highlighted since your last review so I'll dismiss it as stale. Because WP_Query is such a fundamental and low level feature, I don't want to yolo even the smallest of changes.

2025-01-29 21:55 UTC, joemcgill approved these changes
Thanks for the additional test coverage here. I left one question but am pre-approving as everything looks good to me.

2025-01-29 21:55 UTC, joemcgill commented on src/wp-includes/class-wp-query.php
> +				// @todo Handle normalizing `tag` query string.
@peterwilsoncc do you intend to keep this comment, or is this something that still needs to be implemented before this is ready?

2025-01-29 21:59 UTC, peterwilsoncc commented on src/wp-includes/class-wp-query.php
> +				// @todo Handle normalizing `tag` query string.
I intend to keep it and have it as a task for later. This block of code does some strange things so I decided to leave it for a follow up.

2025-02-03 13:49 UTC, spacedmonkey requested changes
We can't sort `post__in`, `post_name__in` or `post_parent__in`. These can be orderby these values. This would mean the sort of the orderby would be wrong.

2025-02-03 21:13 UTC, peterwilsoncc commented
> We can't sort `post__in`, `post_name__in` or `post_parent__in`. These can be orderby these values. This would mean the sort of the orderby would be wrong.

These are only sorted for the WHERE clause and cache key generation, they are untouched for the orderby clause. If used for ordering the SQL query will differ, generating a different hash for the cache key.

See 

https://github.com/WordPress/wordpress-develop/blob/62db25a7bc2f27a1d8804f83543cf591d1512a07/src/wp-includes/class-wp-query.php#L2232-L2237

https://github.com/WordPress/wordpress-develop/blob/62db25a7bc2f27a1d8804f83543cf591d1512a07/src/wp-includes/class-wp-query.php#L2215-L2220

https://github.com/WordPress/wordpress-develop/blob/62db25a7bc2f27a1d8804f83543cf591d1512a07/src/wp-includes/class-wp-query.php#L2247-L2252

The test `Test_Query_CacheResults::test_orderby_clauses_are_not_normalized()` has been introduced in this pull request to ensure the cache keys differ.

2025-02-04 23:08 UTC, peterwilsoncc commented
@spacedmonkey I've pushed a change to the orderby tests to include tests that the order of posts returned is as expected. As the post IDs change for each test run, I needed to split the tests in to three rather than use the data provider.

2025-02-06 04:00 UTC, spacedmonkey approved these changes
Thanks for the clarification @peterwilsoncc 

This pr looks great

2025-02-06 05:03 UTC, closed without merging