Bundled Themes Version Bumps for WordPress 6.6
WordPress/wordpress-develop pull request #7564
Opened 2024-10-14 09:31 UTC by SH4LIN

## Overview
- This PR will bumps up the version of the WordPress in themes from twentyten to twentytwentyfour.

## Latest theme versions
- Twenty Ten - 4.3
- Twenty Eleven: 4.8
- Twenty Twelve: 4.4
- Twenty Thirteen: 4.3
- Twenty Fourteen: 4.1
- Twenty Fifteen: 3.9
- Twenty Sixteen: 3.4
- Twenty Seventeen: 3.8
- Twenty Nineteen: 3.0
- Twenty Twenty: 2.8
- Twenty Twenty-One: 2.4
- Twenty Twenty-Two: 1.9
- Twenty Twenty-Three: 1.6
- Twenty Twenty-Four: 1.3

Trac ticket: https://core.trac.wordpress.org/ticket/62034

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-10-14 09:35 UTC, SH4LIN commented
I haven't updated the changelogs in the `readme.txt`. as I am not sure what will be the release date of theme

2024-10-17 05:31 UTC, sabernhardt requested changes
Thanks for starting on this.

1. For the changelogs, the [release date](https://make.wordpress.org/core/6-7/) is scheduled for November 12, 2024.
2. Please update version numbers in the `package.json` and `package-lock.json` files for Twenty Nineteen, Twenty Twenty and Twenty Twenty-One. See [PR 6705](https://github.com/WordPress/wordpress-develop/pull/6705/files#diff-ab5f915063120bb1805e077dea9b47d5341cf4960fb6249d2b65eac58d87ed1c).
3. In themes from Twenty Ten to Twenty Seventeen, update the CSS and JS version strings in `functions.php` (and/or `header.php`) **only if** the file has changed since the last release. Main `style.css` stylesheets reflect the scheduled release date (`20241112`), and others use the modified date. Almost all `blocks.css` and `editor-blocks.css` files have been updated, but only one `ie.css` stylesheet and none of the JS files should change their version at this time.

| Theme/File | Version |
:- | :-
| `twentyten/blocks.css` | `20240703` |
| `twentyten/editor-blocks.css` | `20240703` |
| `twentyeleven/blocks.css` | `20240703` |
| `twentyeleven/editor-blocks.css` | `20240716` |
| `twentytwelve/blocks.css` | `20240812` |
| `twentytwelve/editor-blocks.css` | `20240811` |
| `twentytwelve/ie.css` | `20240722` |
| `twentythirteen/editor-blocks.css` | `20240716` |
| `twentyfourteen/blocks.css` | `20240708` |
| `twentyfourteen/editor-blocks.css` | `20240716` |
| `twentyfifteen/blocks.css` | `20240715` |
| `twentyfifteen/editor-blocks.css` | `20240720` |
| `twentysixteen/blocks.css` | `20240817` |
| `twentysixteen/editor-blocks.css` | `20240817` |
| `twentyseventeen/blocks.css` | `20240729` |
| `twentyseventeen/editor-blocks.css` | `20240824` |

2024-10-17 06:14 UTC, SH4LIN commented
@sabernhardt Got it, I’ll make the changes as requested.

2024-10-20 12:35 UTC, SH4LIN commented
@sabernhardt I have made all the changes.

2024-10-22 16:51 UTC, sabernhardt requested changes
One more edit, please :)

2024-10-22 16:51 UTC, sabernhardt commented on src/wp-content/themes/twentythirteen/functions.php
> +	wp_enqueue_style( 'twentythirteen-block-style', get_template_directory_uri() . '/css/blocks.css', array( 'twentythirteen-style' ), '20231016' );
```suggestion
	wp_enqueue_style( 'twentythirteen-block-style', get_template_directory_uri() . '/css/blocks.css', array( 'twentythirteen-style' ), '20240520' );
```

The most recent change to `blocks.css` was r58178 on May 20, 2024.

2024-10-25 07:35 UTC, SH4LIN commented
@sabernhardt Done

2024-10-25 08:56 UTC, sabernhardt approved these changes
Thanks for the update!

2024-11-04 23:59 UTC, peterwilsoncc commented
Merged [r59344](https://core.trac.wordpress.org/changeset/59344) / https://github.com/WordPress/wordpress-develop/commit/d897aad420ae38619b236b3f5271f12ed97a7431

Thank you!

2024-11-04 23:59 UTC, closed without merging