Feat: Update the screen-reader-text CSS class and its local implementations
WordPress/wordpress-develop pull request #7579
Opened 2024-10-17 05:25 UTC by hbhalodia

Trac ticket: https://core.trac.wordpress.org/ticket/62238

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-10-17 11:29 UTC, afercia requested changes, later dismissed
Thanks @hbhalodia 
A couple first point for feedback:
- Some stylesheet meant to support old browsers like Internet Explorer 7 must keep the old `clip`.
- In other cases where `clip` is removed and there's no `clip-path`, then `clip-path` should be added.

2024-10-18 06:39 UTC, hbhalodia commented
> Thanks @hbhalodia A couple first point for feedback:
> 
> * Some stylesheet meant to support old browsers like Internet Explorer 7 must keep the old `clip`.
> * In other cases where `clip` is removed and there's no `clip-path`, then `clip-path` should be added.

Hi @afercia, thanks for the feedback. I would resolve this.

2024-10-18 07:31 UTC, hbhalodia commented
Hello @afercia, I have updated the PR with the requested changes.

Thank You,

2025-01-24 11:36 UTC, audrasjb commented on src/wp-content/themes/twentyfourteen/css/ie.css
> +}
this change doesn't look relevant to the scope of the ticket :)

2025-01-24 11:37 UTC, audrasjb commented on src/wp-content/themes/twentytwelve/css/ie.css
> +
these changes don't look relevant given the scope of the ticket :)

2025-01-27 04:39 UTC, hbhalodia commented on src/wp-content/themes/twentyfourteen/css/ie.css
> +}
This is now resolved.

2025-01-27 04:39 UTC, hbhalodia commented on src/wp-content/themes/twentytwelve/css/ie.css
> +
This is now resolved.

2025-01-27 09:00 UTC, audrasjb requested changes, later dismissed
There are still some unrelated changes

2025-01-27 09:00 UTC, audrasjb commented on src/wp-content/themes/twentytwelve/css/ie.css
> +}
These changes look unrelated :)

2025-01-27 09:02 UTC, hbhalodia commented on src/wp-content/themes/twentytwelve/css/ie.css
> +}
Thanks @audrasjb, I would look all this unrelated changes and remove/revert them in next commit.

2025-01-27 09:07 UTC, hbhalodia commented on src/wp-content/themes/twentytwelve/css/ie.css
> +}
This is now resolved.

Thank You,

2025-01-27 19:55 UTC, joedolson approved these changes
I added coverage for a handful of additional cases, and with that I think this is pretty ready. There may be other things missed, but we shouldn't hold this up because of that.

2025-01-27 19:58 UTC, joedolson requested changes
This is not actually ready; instances of clip: auto that are used to render screen reader text visible also need to be updated.

2025-01-27 20:04 UTC, joedolson commented
Updated `:focus` states to not use `clip` if the related static state no longer uses `clip`.

2025-01-28 04:21 UTC, hbhalodia commented
Thanks @joedolson, to update the PR with required changes 🙇.

2025-02-17 17:38 UTC, joedolson approved these changes

2025-02-17 17:48 UTC, joedolson commented
In r59832

2025-02-17 17:48 UTC, closed without merging