Fix: The boolean attributes of video tag in `wp_video_shortcode`
WordPress/wordpress-develop pull request #7606
Opened 2024-10-21 21:49 UTC by Debarghya-Banerjee

Trac Ticket : Core-60178

## Overview

- This pull request introduces updates to the wp_video_shortcode function to enhance the handling of boolean attributes and the preload attribute in accordance with HTML5 standards. These changes aim to ensure that the generated video elements are more compliant with modern web practices.

## Changes Made

- Boolean Attributes Handling:

    - The loop, autoplay, and muted attributes are now output without values when their respective conditions are met. This aligns with HTML5 standards where these attributes can be treated as boolean.

- Preload Attribute

    - The preload attribute has been updated to accept only specific allowed values: none, metadata, and auto. If a value outside of this list is provided, it will be ignored, preventing invalid attribute outputs.

- Code Improvements

    - Enhanced readability and maintainability of the code, including better organization of attribute handling and validation.

## Benefits

- Improves compliance with HTML5 standards for video elements.

- Ensures cleaner and more efficient HTML output.

- Enhances user experience by properly managing video attributes based on their intended use.

## Testing:

- All existing tests related to video shortcode rendering have been updated to validate the new behavior of boolean attributes and the preload attribute.

- This pull request aims to improve the functionality and reliability of video embeds in WordPress while adhering to current web standards.

2024-10-22 16:13 UTC, Debarghya-Banerjee commented
Hi @joedolson , can you please take a look into this PR. Thanks.

2025-01-27 20:20 UTC, joedolson requested changes
Minor changes to make; mostly looks good.

2025-01-27 20:20 UTC, joedolson commented on src/wp-includes/media.php
> +			// If the value is not allowed, you can log a warning or handle it as needed
I think omit this comment.

2025-01-27 20:20 UTC, joedolson commented on src/wp-includes/media.php
> +			// Add boolean attributes without value for true
Comment needs a full stop at the end.

2025-01-27 20:20 UTC, joedolson commented on src/wp-includes/media.php
> +			// For non-boolean attributes, add with value
Comment needs a full stop at the end.

2025-01-28 07:57 UTC, Debarghya-Banerjee commented on src/wp-includes/media.php
> +			// For non-boolean attributes, add with value
Fixed

2025-01-28 07:57 UTC, Debarghya-Banerjee commented on src/wp-includes/media.php
> +			// Add boolean attributes without value for true
Fixed

2025-01-28 07:58 UTC, Debarghya-Banerjee commented on src/wp-includes/media.php
> +			// If the value is not allowed, you can log a warning or handle it as needed
Fixed

2025-01-28 09:18 UTC, Debarghya-Banerjee commented
Hi @joedolson , I have addressed the feedback.

2025-01-28 21:48 UTC, audrasjb commented
I tested the loop, autoplay and muted attributes and I can confirm they are rendered as defined in the scope of the ticket.
The preload attribute accepts only none, metadata or auto.

These tests were made using the [video] shortcode.

2025-01-28 21:49 UTC, audrasjb approved these changes
Changeset approved.

2025-03-09 08:58 UTC, audrasjb commented
Before patch:
<img width="910" alt="Capture d’écran 2025-03-09 à 09 53 59" src="https://github.com/user-attachments/assets/4c414578-d44e-42b6-8b82-5b3fc272f08e" />

After patch: 
<img width="918" alt="Capture d’écran 2025-03-09 à 09 56 51" src="https://github.com/user-attachments/assets/6bb50f63-8083-407d-bdb4-b3ec3335c541" />

The changeset addresses the issues.

2025-03-09 09:21 UTC, audrasjb commented
committed in https://core.trac.wordpress.org/changeset/59954

2025-03-09 09:21 UTC, closed without merging