Apply filters to auhor HTML link
WordPress/wordpress-develop pull request #772
Opened 2020-11-27 17:17 UTC by donmhico

Apply filter to author's HTML link using `author_html_link` filter.

**Example usage**

```php
/**
 * @param string $html_link       The default HTML author link.
 * @param string $author_url      The author's url.
 * @param string $display_name The author's display name. 
 */
add_filter( 'author_html_link', function( $html_link, $author_url, $display_name ) {
	return '<a href="https://wp.org">Mico</a>'; 
}, 10, 3 );
```

Trac ticket: https://core.trac.wordpress.org/ticket/51859

2022-03-21 13:28 UTC, audrasjb requested changes
The PR needs to be refreshed

2022-03-21 13:28 UTC, audrasjb commented on src/wp-includes/author-template.php
> + * @since 5.6.0 Apply filters to the author's HTML link.
Needs refresh

2022-03-21 13:28 UTC, audrasjb commented on src/wp-includes/author-template.php
> +		 * @since 5.6.0
Needs refresh

2022-04-11 23:38 UTC, dream-encode commented
Thanks for the PR!  This was merged into core in https://core.trac.wordpress.org/changeset/53147.

2022-04-11 23:38 UTC, closed without merging