Preserve `target="_blank"` in Biographical Info and Category Description
WordPress/wordpress-develop pull request #7792
Opened 2024-11-13 16:02 UTC by Sukhendu2002

## Preserve `target="_blank"` in Biographical Info and Category Description

### Description
This pull request ensures that the `target="_blank"` attribute is preserved when adding links in the Biographical Info and Category Description fields. Previously, this attribute was being stripped by the kses sanitization process.

Additionally, new unit tests have been added to verify the preservation of the `target="_blank"` attribute in these specific contexts.

### Changes Made
- Added the `target` attribute to the allowed tags in the `user_description` and `pre_term_description` contexts in `wp_kses_allowed_html()`.
- Added the following new unit tests:
  - `test_target_attribute_preserved_in_user_description()`
  - `test_target_attribute_preserved_in_term_description()`
  - `test_target_attribute_preserved_in_user_description_with_other_attributes()`
  - `test_target_attribute_preserved_in_term_description_with_other_attributes()`

Trac ticket: https://core.trac.wordpress.org/ticket/12056

2024-12-12 09:58 UTC, gturpin-dev commented
I just checked the implementation and tests

LGTM 🎉

2025-01-10 06:09 UTC, martinkrcho requested changes
It would be great to use data providers for the new tests.
https://phpunit.de/manual/3.7/en/appendixes.annotations.html#appendixes.annotations.dataProvider

The new test methods do very similar thing in each of them.

2025-01-10 07:04 UTC, Sukhendu2002 commented
@martinkrcho, Thanks for the suggestion! I’ve updated the tests to use data providers accordingly.

2025-01-10 08:06 UTC, martinkrcho approved these changes

2025-01-21 22:13 UTC, audrasjb approved these changes

2025-01-21 22:57 UTC, audrasjb commented
committed in https://core.trac.wordpress.org/changeset/59677

2025-01-21 22:57 UTC, closed without merging