Admin: Update admin notices to use 'notice notice-error' class
WordPress/wordpress-develop pull request #7800
Opened 2024-11-14 10:56 UTC by im3dabasia

Trac ticket: https://core.trac.wordpress.org/ticket/50402

This PR addresses by updating admin error notices to use the `notice notice-error` classes instead of the legacy `error` class. This change aligns error notice styling with current WordPress standards and improves visual consistency across the admin interface.

2025-01-28 20:58 UTC, audrasjb approved these changes
Thanks for the PR. These changes look good to me.

2025-01-29 18:12 UTC, joedolson requested changes
There are some cases here that should be changed. Adding a code comment that indicates why they aren't changed would probably be help for future PRs, though.

2025-01-29 18:12 UTC, joedolson commented on src/wp-content/themes/twentyfifteen/inc/back-compat.php
> +		'<div class="notice notice-error"><p>%s</p></div>',
Don't change back-compat classes, as the context where these run may not include the necessary support.

2025-01-29 18:12 UTC, joedolson commented on src/wp-content/themes/twentynineteen/inc/back-compat.php
> +		'<div class="notice notice-error"><p>%s</p></div>',
Don't change back-compat classes, as the context where these run may not include the necessary support.

2025-01-29 18:12 UTC, joedolson commented on src/wp-content/themes/twentyseventeen/inc/back-compat.php
> +		'<div class="notice notice-error"><p>%s</p></div>',
Don't change back-compat classes, as the context where these run may not include the necessary support.

2025-01-29 18:12 UTC, joedolson commented on src/wp-content/themes/twentyfourteen/inc/back-compat.php
> +		'<div class="notice notice-error"><p>%s</p></div>',
Don't change back-compat classes, as the context where these run may not include the necessary support.

2025-01-29 18:12 UTC, joedolson commented on src/wp-content/themes/twentysixteen/inc/back-compat.php
> +		'<div class="notice notice-error"><p>%s</p></div>',
Don't change back-compat classes, as the context where these run may not include the necessary support.

2025-01-29 18:12 UTC, joedolson commented on src/wp-content/themes/twentythirteen/inc/back-compat.php
> +		'<div class="notice notice-error"><p>%s</p></div>',
Don't change back-compat classes, as the context where these run may not include the necessary support.

2025-01-29 18:12 UTC, joedolson commented on src/wp-content/themes/twentytwentyone/inc/back-compat.php
> +	echo '<div class="notice notice-error"><p>';
Don't change back-compat classes, as the context where these run may not include the necessary support.

2025-01-29 18:12 UTC, joedolson commented on src/wp-signup.php
> +		echo '<p class="notice notice-error" id="wp-signup-blogname-error">' . $errmsg_blogname . '</p>';
In `wp-signup.php`, these classes are defined in the `wpmu_signup_stylesheet` function added to `wp_head`. They aren't part of the WP Admin style group. While we could change the styles in the function, removing the `.error` class is likely to break custom styles implemented by sites. Should probably revert this change and go back to `.error` in this file.

2025-01-29 18:24 UTC, im3dabasia commented
@joedolson , I have removed the changes related to the back-compat files.

Please let me know if you have any further feedback or suggestions for improvements.

2025-01-30 21:13 UTC, joedolson commented
Thanks, @im3dabasia! 

Still need to update the error classes used in `wp-signup.php`, per my comments on that file.

2025-01-30 21:14 UTC, joedolson requested changes, later dismissed
The classes in `wp-signup.php` need to use a class referenced in the generated CSS for that file; I recommend keeping .error but changing the styles to remove `font-weight: 600`.

2025-01-30 21:14 UTC, joedolson commented on src/wp-signup.php
> +		echo '<p class="notice notice-error" id="wp-signup-blogname-error">' . $errmsg_blogname . '</p>';
In keeping with the original purpose of the ticket, however, do remove `font-weight: 600` from the `.mu_register .error` class.

2025-03-06 16:08 UTC, shail-mehta commented
@im3dabasia Whenever you get a chance, Could you Please Resolve Conflicts and Rebase this PR with Latest trunk?

2025-03-06 20:27 UTC, joedolson commented on src/wp-signup.php
> +		echo '<p class="notice notice-error" id="wp-signup-blogname-error">' . $errmsg_blogname . '</p>';
Resolved with https://github.com/WordPress/wordpress-develop/pull/7800/commits/8a1a8f47d33bbdd2f7f832ed2573c15f7433e244

2025-03-10 16:57 UTC, joedolson approved these changes
Removed irrelevant changes & updated multisite broken theme to use wp_admin_notice;

2025-03-10 18:15 UTC, closed without merging