Post Thumbnails: Fix squashed featured image in wp-admin
WordPress/wordpress-develop pull request #7910
Opened 2024-11-28 10:49 UTC by SainathPoojary

Remove `height: auto` from `#postimagediv .inside img` to prevent distortion of featured images in the Classic Editor.

Trac ticket: [#62597](https://core.trac.wordpress.org/ticket/62597)

2024-11-28 13:00 UTC, maciejmackowiak approved these changes

2024-11-29 04:02 UTC, mukeshpanchal27 requested changes
Left comment on ticket

2025-01-22 22:57 UTC, joemcgill requested changes
Given that we're already constraining the width by 100%, I think removing `width: auto;` instead would be better, and keep the image ratio as expected.

2025-01-22 22:58 UTC, joemcgill commented
Alternately, I think we could consider disabling auto-sizes prior to generating this image markup in `_wp_post_thumbnail_html()` [here](https://github.com/WordPress/wordpress-develop/blob/9ad162e53ee9732c8ed63150650f7f9d3067a9d7/src/wp-admin/includes/post.php#L1662).

2025-01-23 01:56 UTC, joemcgill commented
Thanks @SainathPoojary. [bc6461f](https://github.com/WordPress/wordpress-develop/pull/7910/commits/bc6461fb8622d2ec53b409471ba0d351e4064b1a) is almost right. I think we need to keep `height: auto;` that was removed in [9e41eae](https://github.com/WordPress/wordpress-develop/pull/7910/commits/9e41eaeaa63ed93a45870cb7e9fa184eaae276be).

2025-02-07 14:23 UTC, joemcgill approved these changes
Testing this again and looks to fix the issue:

**Before**

<img width="510" alt="Screenshot 2025-02-07 at 8 22 11 AM" src="https://github.com/user-attachments/assets/48a9a438-c0d3-43e3-91ce-4d13f85bf15b" />

**After**

<img width="536" alt="Screenshot 2025-02-07 at 8 21 58 AM" src="https://github.com/user-attachments/assets/9e36e439-79db-46d9-a853-682d3fdf307c" />

2025-02-07 14:40 UTC, joemcgill commented
Merged in https://core.trac.wordpress.org/changeset/59773.

2025-02-07 14:40 UTC, closed without merging