Cache `count_user_posts()`
WordPress/wordpress-develop pull request #7993
Opened 2024-12-11 10:35 UTC by swissspidy

This is just a refresh of the previous patches & tests on the ticket. More work & testing is needed though.

Trac ticket: https://core.trac.wordpress.org/ticket/39242

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

2024-12-12 11:14 UTC, jonnynews requested changes

2024-12-12 11:14 UTC, jonnynews commented on src/wp-includes/default-filters.php
> +add_action( 'post_updated', '_clear_user_posts_count_cache_on_author_change', 10, 3 );
Did you consider using `clean_post_cache`. Lots of plugins do manaul sql updates and then call this function.

2024-12-12 12:24 UTC, swissspidy commented on src/wp-includes/default-filters.php
> +add_action( 'post_updated', '_clear_user_posts_count_cache_on_author_change', 10, 3 );
I did, but I think it runs too often. No reason to clear the cache unless the post status or author changes, or if the post is deleted.

2024-12-12 12:24 UTC, swissspidy commented on src/wp-includes/default-filters.php
> +add_action( 'post_updated', '_clear_user_posts_count_cache_on_author_change', 10, 3 );
Maybe I can add some conditions though

2024-12-12 15:26 UTC, jonnynews commented on src/wp-includes/default-filters.php
> +add_action( 'post_updated', '_clear_user_posts_count_cache_on_author_change', 10, 3 );
If you look at this list, there are a number of popular plugins that use that function. 

https://wpdirectory.net/search/01JEXQH4XW97YT5CZM38TKDPJB

Including
- Yoast SEO
- WooCommerce
- Jetpack
- Elementor

and other very popular plugins. Sadly I think we HAVE to use this hook.

2024-12-12 15:49 UTC, swissspidy commented on src/wp-includes/default-filters.php
> +add_action( 'post_updated', '_clear_user_posts_count_cache_on_author_change', 10, 3 );
Still only half of the equation.

2024-12-12 16:26 UTC, jonnynews commented on src/wp-includes/default-filters.php
> +add_action( 'post_updated', '_clear_user_posts_count_cache_on_author_change', 10, 3 );
> Still only half of the equation.

Can you expand of this, I am not sure I know what you mean?

2025-01-31 00:22 UTC, JJJ commented on src/wp-admin/includes/user.php
> +
This should also be added to `wpmu_delete_user()`, likely inside of the `get_blogs_for_user()` foreach loop because the blog & user posts are already being manipulated there.

https://github.com/WordPress/wordpress-develop/blob/7c6678f2c20a09edc10d10ab14665d26ebb01754/src/wp-admin/includes/ms.php#L176-L199

Note that this happens before `clean_user_cache()`, and I think that might be the better placement for this, too – it would avoid any _potential_ edge-case race-conditions with the `$user` object no longer having a cached value during the `clear_user_posts_count_cache()` calls, because functions like `wp_cache_delete()` are considered pluggable (hence predictably unpredictable).

2025-02-04 10:52 UTC, swissspidy commented
Closing in favor of #8233

2025-02-04 10:52 UTC, closed without merging