Add logic to sort posts by hierarchy
WordPress/wordpress-develop pull request #8014
Opened 2024-12-17 16:15 UTC by oandregal

See related Gutenberg PR https://github.com/WordPress/gutenberg/pull/66479

## What

This PR expands the post controller to allow returning the data by parent-child relationship (sort by hierarchy).

## Why 

We want to display data in a hierarchical way in the site editor, similarly to what we do in wp-admin:

| wp-admin | site editor |
| --- | --- |
| <img width="2545" alt="Screenshot 2024-12-17 at 17 15 12" src="https://github.com/user-attachments/assets/6facad5b-acad-4671-a166-9ececeba5ccc" /> | <img width="2545" alt="Screenshot 2024-12-17 at 17 14 43" src="https://github.com/user-attachments/assets/81f94e96-12c1-49f5-8c05-664f4ae27ddd" /> |

## How to test

Added a new test suite to test the logic. Without the related Gutenberg PR this is difficult to test.

2025-01-08 15:42 UTC, mcsf commented on src/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php
> +			$this->levels = $result['levels'];
@oandregal: Correct me if I'm wrong, but this is [the same problem](https://github.com/WordPress/gutenberg/pull/66479#discussion_r1883888204) that we had with static variables in the original Gutenberg PR. The concept of posts controller doesn't map 1:1 to the concept of a query, and so attaching the state of a query (`levels`) to a controller instance that can outlive it (`$this`) seems dangerous.

2025-01-27 17:23 UTC, joemcgill commented on src/wp-includes/class-hierarchical-sort.php
> +		);
Modifying the query args with these params look similar to what is happening in the current WP Admin when hierarchical post types are queried without any order. See: https://github.com/WordPress/wordpress-develop/blob/9ad162e53ee9732c8ed63150650f7f9d3067a9d7/src/wp-admin/includes/post.php#L1294-L1300

I suspect we might need to update the `is_eligible()` method with the same check for an empty `orderby` query. I also wonder if we need to continue supporting the `menu_order` property as the default sorting for these types of queries?

For sites with a lot of posts, doing a query that returns all posts, e.g. `posts_per_page => -1` could be very slow, so there should be a way for this to be disabled.

2025-01-27 18:01 UTC, spacedmonkey requested changes
Added some thoughts. This is a good start but I think this PR needs work.

2025-01-27 18:01 UTC, spacedmonkey commented on src/wp-includes/class-hierarchical-sort.php
> +class Hierarchical_Sort {
Why do any of the methods in this class need to be static? Static methods have a number of downside, including performance as static methods are not garbage collected in the same way that other methods are. For this one place where the class is used, we could just create an instance of the class and use public methods.

2025-01-27 18:01 UTC, spacedmonkey commented on src/wp-includes/class-hierarchical-sort.php
> +		);
+1

2025-01-27 18:01 UTC, spacedmonkey commented on src/wp-includes/class-hierarchical-sort.php
> +				}
Could we not use `get_post_parent` or  `get_ancestors`

2025-01-27 18:01 UTC, spacedmonkey commented on src/wp-includes/class-hierarchical-sort.php
> +class Hierarchical_Sort {
Why does this need to be another class? Why can't this be part of the `WP_REST_Posts_Controller` class?

2025-01-27 18:01 UTC, spacedmonkey commented on src/wp-includes/class-hierarchical-sort.php
> +	private static function add_hierarchical_ids( &$ids, &$levels, $level, $to_process, $children ) {
PHP Docs required

2025-01-27 18:01 UTC, spacedmonkey commented on src/wp-includes/class-hierarchical-sort.php
> +	private static function get_ancestor( $post_id ) {
Php docs required.

2025-01-27 18:01 UTC, spacedmonkey commented on src/wp-includes/class-hierarchical-sort.php
> +	public static function run( $args ) {
PHPdocs required.

2025-01-29 16:15 UTC, joemcgill reviewed
Two additional questions I have about this PR after thinking about it:

1. Is there a reason this should be implemented as a new request param, rather than extending the existing `orderby` to handle this use case?
2. Is there a reason why it's important to do the sorting and include the `levels` property in the return value, rather than doing that sorting in the client based on the returned post IDs and parents? Returning a REST response shape solely for the purpose of mapping to the visual display in the UI seems like code smell to me unless that value is necessary for some other purpose.

2025-01-31 15:27 UTC, oandregal commented
> Why does this need to be another class? Why can't this be part of the WP_REST_Posts_Controller class?

I'm not married to this implementation, it's just an artifact of having been developed in Gutenberg first.

It was backported verbatim from there, where there's no `WP_REST_Post_Controller` class. I used the existing filters so the changes were isolated. Merging them as part of the controller class could work, having a single function that calculates it all is also an option, etc. — don't have a strong opinion. My only suggestion would be to 1) keep the changes centralized in a single place as opposed to scattered through the controller class and 2) keep them testable. This is an important domain piece that can degrade easily if it's goes unchecked.

2025-01-31 15:34 UTC, oandregal commented
> Is there a reason this should be implemented as a new request param, rather than extending the existing orderby to handle this use case?

`orderby_hierarchy` _configures_ how `orderby` works: either normally or considering hierarchy. I didn't occur to me to overload `orderby` with this "new mode", and now that I think of it I don't see a clean way to do it either.

2025-01-31 15:48 UTC, oandregal commented
> Is there a reason why it's important to do the sorting and include the levels property in the return value, rather than doing that sorting in the client based on the returned post IDs and parents? Returning a REST response shape solely for the purpose of mapping to the visual display in the UI seems like code smell to me unless that value is necessary for some other purpose.

Levels need to be calculated absolutely (based on all the data) and not just relative to the page that is sent to the browser. Otherwise, we'll end up with the wrong levels.

For example, if we had the following dataset and each page sent to the client was of 5 items:

```
1
- 2
-- 3
-- 4
- 5
-- 6
--- 7
--- 8
- 9
- 10
```

The levels of the items in the first page (1 to 5) would be calculated properly. For calculating the levels of the items in the second page (6 to 10) we wouldn't have any information about their ancestors.

2025-08-26 21:53 UTC, TimothyBJacobs commented
Is there any prior art this was drawn from in other REST APIs? Is there prior art we should look at?

2025-08-27 07:53 UTC, oandregal commented
> Is there any prior art this was drawn from in other REST APIs? Is there prior art we should look at?

I haven't seen this implemented in any of our endpoints, or in other REST APIs. Happy to review alternatives. The goal is to support hierarchical data display in the site editor, like wp-admin does.

I'll probably have time to refresh this for the 6.9 cycle, so any feedback is welcome.

2025-10-06 18:07 UTC, ryanwelcher commented
This was reviewed in the bug scrub today for 6.9.

2025-10-07 12:42 UTC, oandregal commented
> This was reviewed in the bug scrub today for 6.9.

My recommendation would be to move it to 7.0. I've been focused on other things and didn't have time to look at this properly.

2026-09-09 09:13 UTC, oandregal commented
Over at https://github.com/WordPress/gutenberg/issues/80360 folks will start working on a new iteration to improve hierarchical relationship client-side (DataViews) and it's taken a different approach than this one. I'll close this.

2026-09-09 09:13 UTC, closed without merging